package com.lightspeedretail.common;

import com.fasterxml.jackson.databind.ObjectMapper;

import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class FreshServiceConstants {

    public static final String CONNECTOR_NAME = "FRESHSERVICES";
    public static final String API_BASE_PATH = "api/v2/";
    public static final String[] ID_HEADERS = {"DISPLAY_ID", "ID"};
    //
/*
    // This section is commented out as we are not using the delta sync based on timestamp fields.
    public static final String[] TIMESTAMP_FIELDS = {"UPDATED_AT", "CREATED_AT"};
    public static final DateTimeFormatter[] DATE_FORMATTERS = {
            DateTimeFormatter.ISO_DATE_TIME,
            DateTimeFormatter.ofPattern("yyyy-MM-dd'T'HH:mm:ss'Z'"),
            DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss"),
            DateTimeFormatter.ofPattern("yyyy-MM-dd'T'HH:mm:ssXXX")
    };*/

    public static final List<String> REQUIRED_SCOPES = List.of(
            "freshservice.agents.roles.view",
            "freshservice.tickets.fields.manage",
            "freshservice.tickets.view",
            "freshservice.tickets.time_entries.view",
            "freshservice.tickets.edit",
            "freshservice.tickets.tasks.view",
            "freshservice.tickets.conversations.view",
            "freshservice.problems.view",
            "freshservice.problems.fields.view",
            "freshservice.problems.notes.view",
            "freshservice.problems.time_entries.view",
            "freshservice.problems.tasks.view",
            "freshservice.changes.view",
            "freshservice.changes.edit",
            "freshservice.changes.notes.view",
            "freshservice.changes.time_entries.view",
            "freshservice.changes.tasks.view",
            "freshservice.releases.view",
            "freshservice.releases.notes.view",
            "freshservice.releases.time_entries.view",
            "freshservice.releases.tasks.view",
            "freshservice.workspaces.view",
            "freshservice.requesters.view",
            "freshservice.requesters.fields.view",
            "freshservice.agents.manage",
            "freshservice.agents.fields.view",
            "freshservice.agentgroups.manage",
            "freshservice.locations.view",
            "freshservice.products.view",
            "freshservice.vendors.view",
            "freshservice.assets.view",
            "freshservice.assets.manage",
            "freshservice.purchase_orders.view",
            "freshservice.contract_types.view",
            "freshservice.contracts.view",
            "freshservice.departments.view",
            "freshservice.departments.fields.view",
            "freshservice.business_hours.view",
            "freshservice.projects.view",
            "freshservice.projects.fields.view",
            "freshservice.projects.manage",
            "freshservice.solutions.view",
            "freshservice.service_catalog.edit",
            "freshservice.announcements.view",
            "freshservice.onboarding_requests.view",
            "freshservice.offboarding_requests.view",
            "freshservice.oncall.view",
            "freshservice.objects.manage",
            "freshservice.pir_template.manage",
            "freshservice.sla_policies.view",
            "freshservice.canned_responses.view"
    );

    public static final class FreshServiceEntityNames {
        public static final String AGENT_FIELDS = "AGENT_FIELDS";
        public static final String AGENTS = "AGENTS";
        public static final String ANNOUNCEMENTS = "ANNOUNCEMENTS";
        public static final String APPLICATION_INSTALLATIONS = "APPLICATION_INSTALLATIONS";
        public static final String APPLICATION_LICENSES = "APPLICATION_LICENSES";
        public static final String APPLICATION_RELATIONSHIPS = "APPLICATION_RELATIONSHIPS";
        public static final String APPLICATION_USERS = "APPLICATION_USERS";
        public static final String APPLICATIONS = "APPLICATIONS";
        public static final String ASSET_TYPES_FIELDS = "ASSET_TYPES_FIELDS";
        public static final String ASSET_TYPES = "ASSET_TYPES";
        public static final String ASSETS_COMPONENTS = "ASSETS_COMPONENTS";
        public static final String ASSETS_REQUESTS = "ASSETS_REQUESTS";
        public static final String ASSETS_CONTRACTS = "ASSETS_CONTRACTS";
        public static final String ASSETS = "ASSETS";
        public static final String BUSINESS_HOURS = "BUSINESS_HOURS";
        public static final String CABS = "CABS";
        public static final String CANNED_RESPONSES = "CANNED_RESPONSES";
        public static final String CANNED_RESPONSE_FOLDERS = "CANNED_RESPONSE_FOLDERS";
        public static final String CHANGES_APPROVAL_GROUPS = "CHANGES_APPROVAL_GROUPS";
        public static final String CHANGES_APPROVALS = "CHANGES_APPROVALS";
        public static final String CHANGES_FORM_FIELDS = "CHANGES_FORM_FIELDS";
        public static final String CHANGES_NOTES = "CHANGES_NOTES";
        public static final String CHANGES_TASKS = "CHANGES_TASKS";
        public static final String CHANGES_TIME_ENTRIES = "CHANGES_TIME_ENTRIES";
        public static final String CHANGES = "CHANGES";
        public static final String CONTRACT_ATTACHMENTS = "CONTRACT_ATTACHMENTS";
        public static final String CONTRACTS = "CONTRACTS";
        public static final String CSAT_RESPONSE = "CSAT_RESPONSE";
        public static final String CUSTOM_OBJECTS = "CUSTOM_OBJECTS";
        public static final String DEPARTMENT_FIELDS = "DEPARTMENT_FIELDS";
        public static final String DEPARTMENTS = "DEPARTMENTS";
        public static final String GROUPS = "GROUPS";
        public static final String JOURNEY_REQUEST_ACTIVITIES = "JOURNEY_REQUEST_ACTIVITIES";
        public static final String JOURNEY_REQUESTS = "JOURNEY_REQUESTS";
        public static final String JOURNEYS_CONFIGS_DATA_FIELDS = "JOURNEYS_CONFIGS_DATA_FIELDS";
        public static final String JOURNEYS_CONFIGS = "JOURNEYS_CONFIGS";
        public static final String LOCATIONS = "LOCATIONS";
        public static final String OBJECT_RECORDS = "OBJECT_RECORDS";
        public static final String OFFBOARDING_REQUESTS = "OFFBOARDING_REQUESTS";
        public static final String ONBOARDING_REQUESTS = "ONBOARDING_REQUESTS";
        public static final String ONCALL_SCHEDULES = "ONCALL_SCHEDULES";
        public static final String ONCALL_SHIFT_EVENTS = "ONCALL_SHIFT_EVENTS";
        public static final String POST_INCIDENT_REPORT_TEMPLATES = "POST_INCIDENT_REPORT_TEMPLATES";
        public static final String PROBLEM_FIELDS = "PROBLEM_FIELDS";
        public static final String PROBLEM_NOTES = "PROBLEM_NOTES";
        public static final String PROBLEM_TASKS = "PROBLEM_TASKS";
        public static final String PROBLEM_TIME_ENTRIES = "PROBLEM_TIME_ENTRIES";
        public static final String PROBLEMS = "PROBLEMS";
        public static final String PRODUCTS = "PRODUCTS";
        public static final String PROJECT_FIELDS = "PROJECT_FIELDS";
        public static final String PROJECT_SPRINTS = "PROJECT_SPRINTS";
        public static final String PROJECT_TASK_NOTES = "PROJECT_TASK_NOTES";
        public static final String PROJECT_TASK_PRIORITIES = "PROJECT_TASK_PRIORITIES";
        public static final String PROJECT_TASK_TYPE_FIELDS = "PROJECT_TASK_TYPE_FIELDS";
        public static final String PROJECT_TASKS = "PROJECT_TASKS";
        public static final String PROJECT_TEMPLATES = "PROJECT_TEMPLATES";
        public static final String PROJECT_VERSIONS = "PROJECT_VERSIONS";
        public static final String PROJECTS_MEMBERSHIPS = "PROJECTS_MEMBERSHIPS";
        public static final String PROJECTS_TASK_STATUES = "PROJECTS_TASK_STATUES";
        public static final String PROJECTS_TASK_TYPES = "PROJECTS_TASK_TYPES";
        public static final String PROJECTS = "PROJECTS";
        public static final String PURCHASE_ORDERS = "PURCHASE_ORDERS";
        public static final String RELATIONSHIP_TYPES = "RELATIONSHIP_TYPES";
        public static final String RELATIONSHIPS = "RELATIONSHIPS";
        public static final String RELEASE_FIELDS = "RELEASE_FIELDS";
        public static final String RELEASES_NOTES = "RELEASES_NOTES";
        public static final String RELEASES_TASKS = "RELEASES_TASKS";
        public static final String RELEASES_TIME_ENTRIES = "RELEASES_TIME_ENTRIES";
        public static final String RELEASES = "RELEASES";
        public static final String REQUESTER_FIELDS = "REQUESTER_FIELDS";
        public static final String REQUESTER_GROUPS = "REQUESTER_GROUPS";
        public static final String REQUESTERS = "REQUESTERS";
        public static final String ROLES = "ROLES";
        public static final String SERVICE_CATALOG_CATEGORIES = "SERVICE_CATALOG_CATEGORIES";
        public static final String SERVICE_CATALOG_ITEMS = "SERVICE_CATALOG_ITEMS";
        public static final String SERVICE_CATALOG_SHARED_FIELDS = "SERVICE_CATALOG_SHARED_FIELDS";
        public static final String SLA_POLICIES = "SLA_POLICIES";
        public static final String SOLUTION_ARTICLES = "SOLUTION_ARTICLES";
        public static final String SOLUTION_CATEGORIES = "SOLUTION_CATEGORIES";
        public static final String SOLUTION_FOLDERS = "SOLUTION_FOLDERS";
        public static final String TICKET_ACTIVITIES = "TICKET_ACTIVITIES";
        public static final String TICKET_APPROVAL_GROUPS = "TICKET_APPROVAL_GROUPS";
        public static final String TICKET_CONVERSATIONS = "TICKET_CONVERSATIONS";
        public static final String TICKET_FIELDS = "TICKET_FIELDS";
        public static final String TICKET_TASKS = "TICKET_TASKS";
        public static final String TICKET_TIME_ENTRIES = "TICKET_TIME_ENTRIES";
        public static final String TICKETS_REQUESTED_ITEMS = "TICKETS_REQUESTED_ITEMS";
        public static final String TICKETS = "TICKETS";
        public static final String VENDORS = "VENDORS";
        public static final String WORKSPACES = "WORKSPACES";

        private FreshServiceEntityNames() {}
    }


    public static final class FreshServiceHeaders {
        public static final String[] AGENT_FIELDS = {"NAME","USER_FIELD_GROUP_ID","LABEL_FOR_ADMINS","MANDATORY_FOR_ADMINS","EDITABLE_BY_ADMINS","LABEL_FOR_AGENTS","EDITABLE_BY_AGENTS","MANDATORY_FOR_AGENTS","VISIBLE_TO_AGENTS","TYPE","DEFAULT_FIELD","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] AGENTS = {"ID","FIRST_NAME","LAST_NAME","OCCASIONAL","ACTIVE","JOB_TITLE","EMAIL","WORK_PHONE_NUMBER","MOBILE_PHONE_NUMBER","DEPARTMENT_IDS","CAN_SEE_ALL_TICKETS_FROM_ASSOCIATED_DEPARTMENTS","REPORTING_MANAGER_ID","ADDRESS","TIME_ZONE","TIME_FORMAT","LANGUAGE","LOCATION_ID","BACKGROUND_INFORMATION","SCOREBOARD_LEVEL_ID","MEMBER_OF","OBSERVER_OF","MEMBER_OF_PENDING_APPROVAL","OBSERVER_OF_PENDING_APPROVAL","ROLES","LAST_LOGIN_AT","LAST_ACTIVE_AT","CUSTOM_FIELDS","HAS_LOGGED_IN","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] ANNOUNCEMENTS = {"TITLE","BODY","BODY_HTML","VISIBLE_FROM","VISIBLE_TILL","VISIBILITY","DEPARTMENTS","GROUPS","STATE","IS_READ","SEND_EMAIL","ADDITIONAL_EMAILS","CREATED_AT","UPDATED_AT","CREATED_BY","WORKSPACE_ID","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] APPLICATION_INSTALLATIONS = {"ID","CREATED_AT","UPDATED_AT","INSTALLATION_PATH","VERSION", "APPLICATION_ID","INSTALLATION_MACHINE_ID","USER_ID","DEPARTMENT_ID","INSTALLATION_DATE","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] APPLICATION_LICENSES = {"ID","CONTRACT_ID","CREATED_TIME","UPDATED_TIME", "APPLICATION_ID","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] APPLICATION_RELATIONSHIPS = {"ID","CREATED_AT","UPDATED_AT", "APPLICATION_ID","RELATIONSHIP_TYPE_ID","PRIMARY_ID","PRIMARY_TYPE","SECONDARY_ID","SECONDARY_TYPE", "__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] APPLICATION_USERS = {"ID","CREATED_AT","UPDATED_AT","USER_ID","LICENSE_ID","ALLOCATED_DATE","FIRST_USED","LAST_USED","SOURCE", "APPLICATION_ID","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] APPLICATIONS = {"ID","USER_COUNT","INSTALLATION_COUNT","CREATED_AT","UPDATED_AT","NAME","PUBLISHER_ID","DESCRIPTION","NOTES","APPLICATION_TYPE","STATUS","MANAGED_BY_ID","CATEGORY","SOURCE","WORKSPACE_ID","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] ASSET_TYPES_FIELDS = {"FIELD_HEADER","FIELDS", "ASSET_TYPES_ID","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] ASSET_TYPES = {"ID","NAME","PARENT_ASSET_TYPE_ID","DESCRIPTION","VISIBLE","CREATED_AT","UPDATED_AT","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] ASSETS_COMPONENTS = {"ID","CREATED_AT","UPDATED_AT","COMPONENT_TYPE","COMPONENT_DATA", "ASSETS_DISPLAY_ID", "__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] ASSETS_REQUESTS = {"ID","CREATED_AT","UPDATED_AT","REQUEST_TYPE","REQUEST_ID","REQUEST_DETAILS","REQUEST_STATUS", "ASSETS_DISPLAY_ID","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] ASSETS_CONTRACTS = {"ID","CONTRACT_ID","CONTRACT_TYPE","CONTRACT_NAME","CONTRACT_STATUS", "ASSETS_DISPLAY_ID", "__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] ASSETS = {"ID","DISPLAY_ID","NAME","DESCRIPTION","ASSET_TYPE_ID","IMPACT","AUTHOR_TYPE","USAGE_TYPE","ASSET_TAG","USER_ID","LOCATION_ID","DEPARTMENT_ID","AGENT_ID","ASSIGNED_ON","CREATED_AT","UPDATED_AT","WORKSPACE_ID","CREATED_BY_SOURCE","LAST_UPDATED_BY_SOURCE","CREATED_BY_USER","LAST_UPDATED_BY_USER","SOURCES","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] BUSINESS_HOURS = {"ID","CREATED_AT","UPDATED_AT","NAME","DESCRIPTION","IS_DEFAULT","TIME_ZONE","SERVICE_DESK_HOURS_MONDAY_BEGINNING_OF_WORKDAY","SERVICE_DESK_HOURS_MONDAY_END_OF_WORKDAY","SERVICE_DESK_HOURS_TUESDAY_BEGINNING_OF_WORKDAY","SERVICE_DESK_HOURS_TUESDAY_END_OF_WORKDAY","SERVICE_DESK_HOURS_WEDNESDAY_BEGINNING_OF_WORKDAY","SERVICE_DESK_HOURS_WEDNESDAY_END_OF_WORKDAY","SERVICE_DESK_HOURS_THURSDAY_BEGINNING_OF_WORKDAY","SERVICE_DESK_HOURS_THURSDAY_END_OF_WORKDAY","SERVICE_DESK_HOURS_FRIDAY_BEGINNING_OF_WORKDAY","SERVICE_DESK_HOURS_FRIDAY_END_OF_WORKDAY","LIST_OF_HOLIDAYS","WORKSPACE_ID","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] CABS = {"ID","NAME","DESCRIPTION","CREATED_AT","UPDATED_AT","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] CANNED_RESPONSES = {"ID","TITLE","FOLDER_ID","CONTENT","CONTENT_HTML","CREATED_AT","UPDATED_AT","WORKSPACE_ID","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] CANNED_RESPONSE_FOLDERS = {"ID","NAME","TYPE","RESPONSES_COUNT","CREATED_AT","UPDATED_AT","WORKSPACE_ID","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] CHANGES_APPROVAL_GROUPS = {"ID","NAME","APPROVAL_TYPE","APPROVAL_STATUS_ID","APPROVAL_STATUS_NAME","CHANGES_ID", "LEVEL","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] CHANGES_APPROVALS = {"ID","CREATED_AT","UPDATED_AT","APPROVER_ID","APPROVER_NAME","APPROVAL_TYPE","USER_ID","CHANGES_ID","LEVEL","USER_NAME","APPROVAL_STATUS_ID","APPROVAL_STATUS_NAME","DELEGATEE_ID","DELEGATEE_NAME","APPROVAL_GROUP_ID","APPROVAL_GROUP_NAME","LATEST_REMARK","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] CHANGES_FORM_FIELDS = {"ID","CREATED_AT","UPDATED_AT","NAME","LABEL","DESCRIPTION","FIELD_TYPE","REQUIRED","REQUIRED_FOR_CLOSURE","POSITION","DEFAULT_FIELD","CHOICES","NESTED_FIELDS","WORKSPACE_ID","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] CHANGES_NOTES = {"ID","CREATED_AT","UPDATED_AT","BODY","BODY_TEXT","USER_ID","NOTIFY_EMAILS","CHANGES_ID","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] CHANGES_TASKS = {"ID","AGENT_ID","STATUS","DUE_DATE","NOTIFY_BEFORE","TITLE","DESCRIPTION","CHANGES_ID","CREATED_AT","UPDATED_AT","CLOSED_AT","GROUP_ID","WORKSPACE_ID","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] CHANGES_TIME_ENTRIES = {"ID","CREATED_AT","UPDATED_AT","START_TIME","TIMER_RUNNING","BILLABLE","TIME_SPENT","EXECUTED_AT","TASK_ID","WORKSPACE_ID","NOTE","AGENT_ID","CUSTOM_FIELDS","CHANGES_ID","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] CHANGES = {"ID","AGENT_ID","DESCRIPTION","DESCRIPTION_TEXT","WORKSPACE_ID","REQUESTER_ID","GROUP_ID","PRIORITY","IMPACT","STATUS","RISK","CHANGE_TYPE","APPROVAL_STATUS","PLANNED_START_DATE","PLANNED_END_DATE","SUBJECT","DEPARTMENT_ID","CATEGORY","SUB_CATEGORY","ITEM_CATEGORY","CREATED_AT","UPDATED_AT","CUSTOM_FIELDS_CUSTOM_TEXT","CUSTOM_FIELDS_CUSTOM_PARAGRAPH","CUSTOM_FIELDS_CUSTOM_CHECKBOX","CUSTOM_FIELDS_CUSTOM_NUMBER","CUSTOM_FIELDS_CUSTOM_DROPDOWN","CUSTOM_FIELDS_CUSTOM_DATE","CUSTOM_FIELDS_CUSTOM_DECIMAL","ASSETS","IMPACTED_SERVICES","MAINTENANCE_WINDOW_ID","MAINTENANCE_WINDOW_NAME","MAINTENANCE_WINDOW_DESCRIPTION","MAINTENANCE_WINDOW_WINDOW_START_DATE","MAINTENANCE_WINDOW_WINDOW_END_DATE","BLACKOUT_WINDOW_ID","BLACKOUT_WINDOW_NAME","BLACKOUT_WINDOW_DESCRIPTION","BLACKOUT_WINDOW_WINDOW_START_DATE","BLACKOUT_WINDOW_WINDOW_END_DATE","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] CONTRACT_ATTACHMENTS = {"ID","NAME","CONTENT_TYPE","SIZE","ATTACHMENT_URL","CANONICAL_URL", "CONTRACTS_ID", "CREATED_AT","UPDATED_AT","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] CONTRACTS = {"ID","NAME","DESCRIPTION","VENDOR_ID","AUTO_RENEW","NOTIFY_EXPIRY","NOTIFY_BEFORE","APPROVER_ID","START_DATE","END_DATE","COST","STATUS","CONTRACT_NUMBER","CONTRACT_TYPE_ID","VISIBLE_TO_ID","NOTIFY_TO","CUSTOM_FIELDS_ID","FUTURE_CONTRACT_ID","HAS_ASSOCIATED_ASSETS","HAS_ATTACHMENTS","EXPIRY_NOTIFIED","REQUESTER_ID","DELEGATEE_ID","CREATED_AT","UPDATED_AT","WORKSPACE_ID","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] CSAT_RESPONSE = {"ID","OVERALL_RATING","OVERALL_RATING_TEXT","PRIMARY_QUESTION","QUESTIONNAIRE_RESPONSES","CREATED_AT","UPDATED_AT","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] CUSTOM_OBJECTS = {"ID","TITLE","DESCRIPTION","UPDATED_AT","LAST_UPDATED_BY_EMAIL","LAST_UPDATED_BY_ID","LAST_UPDATED_BY_NAME","WORKSPACE_ID","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] DEPARTMENT_FIELDS = {"CREATED_AT","UPDATED_AT","NAME","LABEL","MANDATORY","IS_DEFAULT_FIELD","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] DEPARTMENTS = {"ID","NAME","DESCRIPTION","HEAD_USER_ID","PRIME_USER_ID","DOMAINS","CUSTOM_FIELDS_LOCATION","WORKSPACE_ID","CREATED_AT","UPDATED_AT","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] GROUPS = {"ID","NAME","DESCRIPTION","BUSINESS_HOURS_ID","ESCALATE_TO","UNASSIGNED_FOR","WORKSPACE_ID","MEMBERS","OBSERVERS","RESTRICTED","APPROVAL_REQUIRED","LEADERS","MEMBERS_PENDING_APPROVAL","LEADERS_PENDING_APPROVAL","OBSERVERS_PENDING_APPROVAL","AUTO_TICKET_ASSIGN","CREATED_AT","UPDATED_AT","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] JOURNEY_REQUEST_ACTIVITIES = {"ID","ACCOUNT_ID","JOURNEY_REQUEST_ID","JOURNEY_REQUEST_PHASE_ID","ACTIVITY_CONFIG_ID","DISPLAY_ID","ASSIGNEE_ID","GROUP_ID","CONDITIONS","COMMENT","DATA","DUE_DATE","PARENT_ID","STATUS","STATE","TITLE","TYPE","CREATED_AT","UPDATED_AT","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] JOURNEY_REQUESTS = {"ID","DISPLAY_ID","ACCOUNT_ID","TITLE","HUMAN_DISPLAY_ID","JOURNEY_CONFIG_ID","JOURNEY_ID","VERSION","JOURNEY_TYPE_ID","STATUS","REQUESTER_ID","REQUESTED_FOR_ID","WORKSPACE_ID","CREATED_AT","UPDATED_AT","ADDITIONAL_INFO_STAKEHOLDERS","ADDITIONAL_INFO_SERVICE_FORM_ID","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] JOURNEYS_CONFIGS_DATA_FIELDS = {"PLACEHOLDER","LABEL","NAME","TYPE","POSITION","REQUIRED","CHOICES","DATA_SOURCE","FIELDS","DELETED","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] JOURNEYS_CONFIGS = {"ID","JOURNEY_ID","ACCOUNT_ID","NAME","DESCRIPTION","STATUS","JOURNEY_TYPE_ID","OWNER_ID","CREATED_BY","CREATED_AT","UPDATED_BY","UPDATED_AT","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] LOCATIONS = {"ID","NAME","PARENT_LOCATION_ID","PRIMARY_CONTACT_ID","ADDRESS_LINE1","ADDRESS_LINE2","ADDRESS_CITY","ADDRESS_STATE","ADDRESS_COUNTRY","ADDRESS_ZIPCODE","WORKSPACE_ID","CREATED_AT","UPDATED_AT","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] OBJECT_RECORDS = {"VERSION", "DATA", "OBJECT_ID", "__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] OFFBOARDING_REQUESTS = {"ID","CREATED_AT","UPDATED_AT","STATUS","SUBJECT","FIELDS_ACTOR_2","FIELDS_CF_EMPLOYEE_NAME","FIELDS_CF_EMPLOYEE_EMAIL","FIELDS_CF_SEPARATION_TYPE","FIELDS_CF_MOBILE_PHONE_NUMBER","FIELDS_CF_DEPARTMENT","FIELDS_CF_LOCATION","FIELDS_CF_HIERARCHY","FIELDS_CF_VERIFIED","FIELDS_CF_ASSETS","FIELDS_MSF_AREA_OF_EXPERTISE","FIELDS_MSF_PREFERRED_LOCATIONS","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] ONBOARDING_REQUESTS = {"ID","CREATED_AT","UPDATED_AT","STATUS","SUBJECT","FIELDS_CF_EMPLOYEE_NAME","FIELDS_CF_JOB_TITLE","FIELDS_CF_DATE_OF_JOINING","FIELDS_CF_DEPARTMENT","FIELDS_CF_LOCATION","FIELDS_MSF_AREA_OF_EXPERTISE","FIELDS_MSF_PREFERRED_LOCATIONS","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] ONCALL_SCHEDULES = {"ID","NAME","DESCRIPTION","AGENT_GROUP_ID","AGENT_GROUP_NAME","INVALID_NUMBERS_PRESENT","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] ONCALL_SHIFT_EVENTS = {"ID","USER_ID","USER_NAME","USER_EMAIL","USER_SECOND_EMAIL","USER_PRODUCT_USER_ID","USER_PHONE","USER_MOBILE","USER_AGENT","USER_GROUP_IDS","EVENT_START_DATE_TIME","EVENT_END_DATE_TIME","OVERRIDDEN","ROSTER_TYPE","SHIFT_ID","SHIFT_NAME","SHIFT_TIMEZONE","SHIFT_TIMEZONE_OFFSET","SCHEDULE_ID","SCHEDULE_NAME","SCHEDULE_AGENT_GROUP_ID","SCHEDULE_WORKSPACE_ID","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] POST_INCIDENT_REPORT_TEMPLATES = {"ID","CREATED_AT","UPDATED_AT","TITLE","STATE","UPDATED_BY","PRIMARY","WORKSPACE_ID","RELATED_INCIDENT_ENABLED","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] PROBLEM_FIELDS = {"ID","CREATED_AT","UPDATED_AT","NAME","LABEL","DESCRIPTION","FIELD_TYPE","REQUIRED","REQUIRED_FOR_CLOSURE","POSITION","DEFAULT_FIELD","CHOICES","NESTED_FIELDS", "WORKSPACE_ID","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] PROBLEM_NOTES = {"ID","CREATED_AT","UPDATED_AT","BODY","BODY_TEXT","USER_ID","NOTIFY_EMAILS","PROBLEM_ID","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] PROBLEM_TASKS = {"ID","AGENT_ID","STATUS","DUE_DATE","NOTIFY_BEFORE","TITLE","DESCRIPTION","PROBLEM_ID","CREATED_AT","UPDATED_AT","CLOSED_AT","GROUP_ID","WORKSPACE_ID","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] PROBLEM_TIME_ENTRIES = {"ID","CREATED_AT","UPDATED_AT","START_TIME","TIMER_RUNNING","BILLABLE","TIME_SPENT","EXECUTED_AT","TASK_ID","WORKSPACE_ID","NOTE","AGENT_ID","CUSTOM_FIELDS","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] PROBLEMS = {"ID","AGENT_ID","REQUESTER_ID","DESCRIPTION","DESCRIPTION_TEXT","DUE_BY","SUBJECT","GROUP_ID","PRIORITY","IMPACT","STATUS","KNOWN_ERROR","DEPARTMENT_ID","CATEGORY","SUB_CATEGORY","ITEM_CATEGORY","ASSETS","CREATED_AT","UPDATED_AT","WORKSPACE_ID","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] PRODUCTS = {"ID","NAME","ASSET_TYPE_ID","MANUFACTURER","STATUS","MODE_OF_PROCUREMENT","DEPRECIATION_TYPE_ID","DESCRIPTION","DESCRIPTION_TEXT","CREATED_AT","UPDATED_AT","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] PROJECT_FIELDS = {"LABEL","NAME","TYPE","DEFAULT","CHOICES","MANDATORY","CREATED_AT","UPDATED_AT","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] PROJECT_SPRINTS = {"ID","CREATED_AT","UPDATED_AT","TITLE","PLANNED_START_DATE","PLANNED_END_DATE","GOAL","STATE","PROJECT_ID","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] PROJECT_TASK_NOTES = {"ID","BODY","TASK_ID","USER_EMAIL_ID","ATTACHMENTS","PROJECTS_ID","CREATED_AT","UPDATED_AT","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] PROJECT_TASK_PRIORITIES = {"ID","CREATED_AT","UPDATED_AT","NAME","DESCRIPTION","PROJECT_ID","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] PROJECT_TASK_TYPE_FIELDS = {"DEFAULT","CREATED_AT","UPDATED_AT","MANDATORY","LABEL","NAME","CHOICES","TYPE","PROJECT_ID","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] PROJECT_TASKS = {"ID","TITLE","PROJECT_ID","DESCRIPTION","STATUS_ID","PRIORITY_ID","REPORTER_ID","CREATED_AT","UPDATED_AT","DISPLAY_KEY","PLANNED_START_DATE","TYPE_ID","ASSIGNEE_ID","PLANNED_END_DATE","PLANNED_EFFORT","PLANNED_DURATION","CUSTOM_FIELDS_CUSTOM_TEXT","VERSION_ID","PARENT_ID","STORY_POINTS","SPRINT_ID","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] PROJECT_TEMPLATES = {"ID","NAME","DESCRIPTION","TEMPLATE_TYPE","VISIBILITY","CREATED_AT","UPDATED_AT", "__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] PROJECT_VERSIONS = {"ID","CREATED_AT","UPDATED_AT","NAME","START_DATE","DUE_DATE","DESCRIPTION","STATUS_ID","OWNER_ID","PROJECT_ID","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] PROJECTS_MEMBERSHIPS = {"ID","PROJECT_ID","USER_ID","ACCESS_TYPE","MANAGE_SETTINGS","PROJECT_MANAGER","CREATED_AT","UPDATED_AT","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] PROJECTS_TASK_STATUES = {"ID","CREATED_AT","UPDATED_AT","NAME","DESCRIPTION","PROJECT_ID","CATEGORY_ID","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] PROJECTS_TASK_TYPES = {"ID","CREATED_AT","UPDATED_AT","NAME","DESCRIPTION","PROJECT_ID","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] PROJECTS = {"ID", "NAME", "KEY", "DESCRIPTION", "STATUS_ID", "PRIORITY_ID", "SPRINT_DURATION", "PROJECT_TYPE", "START_DATE", "END_DATE", "ARCHIVED", "VISIBILITY", "MANAGER_ID", "ATTACHMENTS", "CREATED_AT", "UPDATED_AT", "CUSTOM_FIELDS", "__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] PURCHASE_ORDERS = {"ID","VENDOR_ID","NAME","PO_NUMBER","VENDOR_DETAILS","EXPECTED_DELIVERY_DATE","CREATED_AT","UPDATED_AT","CREATED_BY","STATUS","SHIPPING_ADDRESS","BILLING_SAME_AS_SHIPPING","BILLING_ADDRESS","CURRENCY_CODE","DEPARTMENT_ID","DISCOUNT_PERCENTAGE","TAX_PERCENTAGE","SHIPPING_COST","WORKSPACE_ID","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] RELATIONSHIP_TYPES = {"ID","IS_DEFAULT","DESCRIPTION","CREATED_AT","UPDATED_AT","DOWNSTREAM_RELATION","UPSTREAM_RELATION","UPSTREAM_IMPACT","DOWNSTREAM_IMPACT","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] RELATIONSHIPS = {"ID","RELATIONSHIP_TYPE_ID","PRIMARY_ID","PRIMARY_TYPE","SECONDARY_ID","SECONDARY_TYPE","CREATED_AT","UPDATED_AT","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] RELEASE_FIELDS = {"ID","CREATED_AT","UPDATED_AT","NAME","LABEL","DESCRIPTION","FIELD_TYPE","REQUIRED","REQUIRED_FOR_CLOSURE","POSITION","DEFAULT_FIELD","CHOICES","NESTED_FIELDS","WORKSPACE_ID","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] RELEASES_NOTES = {"ID","CREATED_AT","UPDATED_AT","BODY","BODY_TEXT","USER_ID","NOTIFY_EMAILS", "RELEASES_ID","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] RELEASES_TASKS = {"ID","AGENT_ID","STATUS","DUE_DATE","NOTIFY_BEFORE","TITLE","DESCRIPTION","CREATED_AT","UPDATED_AT","CLOSED_AT","GROUP_ID", "RELEASES_ID","WORKSPACE_ID","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] RELEASES_TIME_ENTRIES = {"ID","CREATED_AT","UPDATED_AT","START_TIME","TIMER_RUNNING","BILLABLE","TIME_SPENT","EXECUTED_AT","TASK_ID","WORKSPACE_ID","NOTE","AGENT_ID","CUSTOM_FIELDS","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] RELEASES = {"ID","AGENT_ID","GROUP_ID","PRIORITY","STATUS","RELEASE_TYPE","SUBJECT","PLANNED_START_DATE","PLANNED_END_DATE","WORK_START_DATE","WORK_END_DATE","DEPARTMENT_ID","CATEGORY","SUB_CATEGORY","ITEM_CATEGORY","CREATED_AT","UPDATED_AT","WORKSPACE_ID","ASSETS","ASSOCIATED_ASSETS","ASSOCIATED_CHANGES","CUSTOM_FIELDS","PLANNING_FIELDS","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] REQUESTER_FIELDS = {"ID","EDITABLE_IN_SIGNUP","NAME","LABEL","POSITION","USER_FIELD_GROUP_ID","REQUIRED_FOR_AGENTS","TYPE","DEFAULT","CUSTOMERS_CAN_EDIT","LABEL_FOR_CUSTOMERS","REQUIRED_FOR_CUSTOMERS","DISPLAYED_FOR_CUSTOMERS","CREATED_AT","UPDATED_AT","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] REQUESTER_GROUPS = {"ID","NAME","DESCRIPTION","TYPE","WORKSPACE_ID","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] REQUESTERS = {"ID","IS_AGENT","FIRST_NAME","LAST_NAME","JOB_TITLE","PRIMARY_EMAIL","SECONDARY_EMAILS","WORK_PHONE_NUMBER","MOBILE_PHONE_NUMBER","DEPARTMENT_IDS","CAN_SEE_ALL_TICKETS_FROM_ASSOCIATED_DEPARTMENTS","REPORTING_MANAGER_ID","ADDRESS","TIME_ZONE","TIME_FORMAT","LANGUAGE","LOCATION_ID","BACKGROUND_INFORMATION","CUSTOM_FIELDS","ACTIVE","HAS_LOGGED_IN","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] ROLES = {"ID","NAME","DESCRIPTION", "PRIVILEGES", "DEFAULT", "ROLE_TYPE", "CREATED_AT", "UPDATED_AT", "__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] SERVICE_CATALOG_CATEGORIES = {"ID","DESCRIPTION","CREATED_AT","UPDATED_AT","NAME","POSITION","WORKSPACE_ID","PARENT_ID","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] SERVICE_CATALOG_ITEMS = {"ID","CREATED_AT","UPDATED_AT","NAME","DELIVERY_TIME","DISPLAY_ID","CATEGORY_ID","PRODUCT_ID","QUANTITY","DELETED","ICON_NAME","GROUP_VISIBILITY","ITEM_TYPE","CI_TYPE_ID","COST_VISIBILITY","DELIVERY_TIME_VISIBILITY","CONFIGS","BOTIFIED","VISIBILITY","ALLOW_ATTACHMENTS","ALLOW_QUANTITY","IS_BUNDLE","CREATE_CHILD","WORKSPACE_ID","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] SERVICE_CATALOG_SHARED_FIELDS = {"ID","FORM_ID","LABEL","ARCHIVED","TYPE","FIELD_TYPE","TRANSLATED_FIELD_TYPE","FIELD_OPTIONS","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] SLA_POLICIES = {"ID","WORKSPACE_ID","NAME","POSITION","IS_DEFAULT","ACTIVE","DELETED","DESCRIPTION","WORKSPACE_ID","SLA_TARGETS","APPLICABLE_TO_TICKET_TYPE","APPLICABLE_TO_SERVICE_ITEMS","APPLICABLE_TO_SERVICE_CATEGORIES","APPLICABLE_TO_DEPARTMENT_ID","APPLICABLE_TO_GROUP_ID","APPLICABLE_TO_SUB_CATEGORY","APPLICABLE_TO_ITEM_CATEGORY","APPLICABLE_TO_CATEGORY","APPLICABLE_TO_SOURCE","ESCALATION_RESPONSE","ESCALATION_RESOLUTION","CREATED_AT","UPDATED_AT","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] SOLUTION_ARTICLES = {"ID","DESCRIPTION","CREATED_AT","UPDATED_AT","TITLE","STATUS","APPROVAL_STATUS","POSITION","FOLDER_ID","CATEGORY_ID","THUMBS_UP","THUMBS_DOWN","MODIFIED_BY","MODIFIED_AT","INSERTED_INTO_TICKETS","URL","ARTICLE_TYPE","AGENT_ID","VIEWS","DESCRIPTION_TEXT"};
        public static final String[] SOLUTION_CATEGORIES = {"ID","CREATED_AT","UPDATED_AT","NAME","DESCRIPTION","DEFAULT_CATEGORY","POSITION","VISIBLE_IN_PORTALS","WORKSPACE_ID","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] SOLUTION_FOLDERS = {"ID","NAME","DESCRIPTION","CREATED_AT","UPDATED_AT","CATEGORY_ID","POSITION","VISIBILITY","APPROVAL_SETTINGS","DEFAULT_FOLDER","MANAGE_BY_GROUP_IDS","WORKSPACE_ID","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] TICKET_ACTIVITIES = {"ACTOR_ID","ACTOR_NAME","CONTENT","SUB_CONTENTS","CREATED_AT","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] TICKET_APPROVAL_GROUPS = {"ID","NAME","APPROVAL_TYPE","APPROVAL_STATUS_ID","APPROVAL_STATUS_NAME","LEVEL","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] TICKET_CONVERSATIONS = {"ID","BODY","BODY_TEXT","INCOMING","PRIVATE","CREATED_AT","UPDATED_AT","USER_ID","SUPPORT_EMAIL","SOURCE","TICKET_ID","TO_EMAILS","FROM_EMAIL","CC_EMAILS","BCC_EMAILS","ATTACHMENTS","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] TICKET_FIELDS = {"ID","LABEL","DESCRIPTION","FIELD_TYPE","CREATED_AT","UPDATED_AT","POSITION","REQUIRED_FOR_CLOSURE","NAME","DEFAULT_FIELD","REQUIRED_FOR_AGENTS","CUSTOMERS_CAN_EDIT","LABEL_FOR_CUSTOMERS","REQUIRED_FOR_CUSTOMERS","DISPLAYED_TO_CUSTOMERS","BELONGS_TO_SECTION","CHOICES","NESTED_FIELDS","SECTIONS","WORKSPACE_ID","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] TICKET_TASKS = {"ID","AGENT_ID","STATUS","DUE_DATE","NOTIFY_BEFORE","TITLE","DESCRIPTION","CREATED_AT","UPDATED_AT","CLOSED_AT", "TICKETS_ID", "GROUP_ID","WORKSPACE_ID","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] TICKET_TIME_ENTRIES = {"ID","CREATED_AT","UPDATED_AT","START_TIME","TIMER_RUNNING","BILLABLE","TIME_SPENT","EXECUTED_AT","TASK_ID","WORKSPACE_ID","NOTE","AGENT_ID","CUSTOM_FIELDS_ID","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] TICKETS_REQUESTED_ITEMS = {"ID","CUSTOM_FIELDS","CREATED_AT","UPDATED_AT","QUANTITY","STAGE","LOANED","COST_PER_REQUEST","REMARKS","DELIVERY_TIME","IS_PARENT","SERVICE_ITEM_ID","ATTACHMENTS","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] TICKETS = {"ID","CC_EMAILS","FWD_EMAILS","REPLY_CC_EMAILS","FR_ESCALATED","SPAM","EMAIL_CONFIG_ID","GROUP_ID","PRIORITY","REQUESTER_ID","REQUESTED_FOR_ID","RESPONDER_ID","SOURCE","STATUS","SUBJECT","TO_EMAILS","DEPARTMENT_ID","TYPE","DUE_BY","FR_DUE_BY","IS_ESCALATED","DESCRIPTION","DESCRIPTION_TEXT","CATEGORY","SUB_CATEGORY","ITEM_CATEGORY","CUSTOM_FIELDS","WORKSPACE_ID","CREATED_AT","UPDATED_AT","DELETED","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] VENDORS = {"ID","NAME","DESCRIPTION","PRIMARY_CONTACT_ID","ADDRESS_LINE1","ADDRESS_CITY","ADDRESS_STATE","ADDRESS_COUNTRY","ADDRESS_ZIPCODE","CREATED_AT","UPDATED_AT","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] WORKSPACES = {"ID","CREATED_AT","DESCRIPTION","NAME","PRIMARY","RESTRICTED","STATE","TEMPLATE_NAME","TYPE","UPDATED_AT","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};

        private FreshServiceHeaders() {}
    }

    public static List<String> excludedEntities = List.of();

    public static final Map<String, String[]> HEADERS_BY_ENTITY = Map.ofEntries(
        Map.entry(FreshServiceEntityNames.AGENT_FIELDS, FreshServiceHeaders.AGENT_FIELDS),
        Map.entry(FreshServiceEntityNames.AGENTS, FreshServiceHeaders.AGENTS),
        Map.entry(FreshServiceEntityNames.ANNOUNCEMENTS, FreshServiceHeaders.ANNOUNCEMENTS),
        Map.entry(FreshServiceEntityNames.APPLICATION_INSTALLATIONS, FreshServiceHeaders.APPLICATION_INSTALLATIONS),
        Map.entry(FreshServiceEntityNames.APPLICATION_LICENSES, FreshServiceHeaders.APPLICATION_LICENSES),
        Map.entry(FreshServiceEntityNames.APPLICATION_RELATIONSHIPS, FreshServiceHeaders.APPLICATION_RELATIONSHIPS),
        Map.entry(FreshServiceEntityNames.APPLICATION_USERS, FreshServiceHeaders.APPLICATION_USERS),
        Map.entry(FreshServiceEntityNames.APPLICATIONS, FreshServiceHeaders.APPLICATIONS),
        Map.entry(FreshServiceEntityNames.ASSET_TYPES_FIELDS, FreshServiceHeaders.ASSET_TYPES_FIELDS),
            Map.entry(FreshServiceEntityNames.ASSET_TYPES, FreshServiceHeaders.ASSET_TYPES),
            Map.entry(FreshServiceEntityNames.ASSETS_COMPONENTS, FreshServiceHeaders.ASSETS_COMPONENTS),
            Map.entry(FreshServiceEntityNames.ASSETS_REQUESTS, FreshServiceHeaders.ASSETS_REQUESTS),
            Map.entry(FreshServiceEntityNames.ASSETS_CONTRACTS, FreshServiceHeaders.ASSETS_CONTRACTS),
            Map.entry(FreshServiceEntityNames.ASSETS, FreshServiceHeaders.ASSETS),
            Map.entry(FreshServiceEntityNames.BUSINESS_HOURS, FreshServiceHeaders.BUSINESS_HOURS),
            Map.entry(FreshServiceEntityNames.CABS, FreshServiceHeaders.CABS),
            Map.entry(FreshServiceEntityNames.CANNED_RESPONSES, FreshServiceHeaders.CANNED_RESPONSES),
            Map.entry(FreshServiceEntityNames.CANNED_RESPONSE_FOLDERS, FreshServiceHeaders.CANNED_RESPONSE_FOLDERS),
            Map.entry(FreshServiceEntityNames.CHANGES_APPROVAL_GROUPS, FreshServiceHeaders.CHANGES_APPROVAL_GROUPS),
            Map.entry(FreshServiceEntityNames.CHANGES_FORM_FIELDS, FreshServiceHeaders.CHANGES_FORM_FIELDS),
            Map.entry(FreshServiceEntityNames.CHANGES_NOTES, FreshServiceHeaders.CHANGES_NOTES),
            Map.entry(FreshServiceEntityNames.CHANGES_TASKS, FreshServiceHeaders.CHANGES_TASKS),
            Map.entry(FreshServiceEntityNames.CHANGES_TIME_ENTRIES, FreshServiceHeaders.CHANGES_TIME_ENTRIES),
            Map.entry(FreshServiceEntityNames.CHANGES, FreshServiceHeaders.CHANGES),
            Map.entry(FreshServiceEntityNames.CONTRACT_ATTACHMENTS, FreshServiceHeaders.CONTRACT_ATTACHMENTS),
            Map.entry(FreshServiceEntityNames.CONTRACTS, FreshServiceHeaders.CONTRACTS),
            Map.entry(FreshServiceEntityNames.CSAT_RESPONSE, FreshServiceHeaders.CSAT_RESPONSE),
            Map.entry(FreshServiceEntityNames.CUSTOM_OBJECTS, FreshServiceHeaders.CUSTOM_OBJECTS),
            Map.entry(FreshServiceEntityNames.DEPARTMENT_FIELDS, FreshServiceHeaders.DEPARTMENT_FIELDS),
            Map.entry(FreshServiceEntityNames.DEPARTMENTS, FreshServiceHeaders.DEPARTMENTS),
            Map.entry(FreshServiceEntityNames.GROUPS, FreshServiceHeaders.GROUPS),
            Map.entry(FreshServiceEntityNames.LOCATIONS, FreshServiceHeaders.LOCATIONS),
            Map.entry(FreshServiceEntityNames.OBJECT_RECORDS, FreshServiceHeaders.OBJECT_RECORDS),
            Map.entry(FreshServiceEntityNames.OFFBOARDING_REQUESTS, FreshServiceHeaders.OFFBOARDING_REQUESTS),
            Map.entry(FreshServiceEntityNames.ONBOARDING_REQUESTS, FreshServiceHeaders.ONBOARDING_REQUESTS),
            Map.entry(FreshServiceEntityNames.ONCALL_SCHEDULES, FreshServiceHeaders.ONCALL_SCHEDULES),
            Map.entry(FreshServiceEntityNames.ONCALL_SHIFT_EVENTS, FreshServiceHeaders.ONCALL_SHIFT_EVENTS),
            Map.entry(FreshServiceEntityNames.POST_INCIDENT_REPORT_TEMPLATES, FreshServiceHeaders.POST_INCIDENT_REPORT_TEMPLATES),
            Map.entry(FreshServiceEntityNames.PROBLEM_FIELDS, FreshServiceHeaders.PROBLEM_FIELDS),
            Map.entry(FreshServiceEntityNames.PROBLEM_NOTES, FreshServiceHeaders.PROBLEM_NOTES),
            Map.entry(FreshServiceEntityNames.PROBLEM_TASKS, FreshServiceHeaders.PROBLEM_TASKS),
            Map.entry(FreshServiceEntityNames.PROBLEM_TIME_ENTRIES, FreshServiceHeaders.PROBLEM_TIME_ENTRIES),
            Map.entry(FreshServiceEntityNames.PROBLEMS, FreshServiceHeaders.PROBLEMS),
            Map.entry(FreshServiceEntityNames.PRODUCTS, FreshServiceHeaders.PRODUCTS),
            Map.entry(FreshServiceEntityNames.PROJECT_FIELDS, FreshServiceHeaders.PROJECT_FIELDS),
            Map.entry(FreshServiceEntityNames.PROJECT_SPRINTS, FreshServiceHeaders.PROJECT_SPRINTS),
            Map.entry(FreshServiceEntityNames.PROJECT_TASK_NOTES, FreshServiceHeaders.PROJECT_TASK_NOTES),
            Map.entry(FreshServiceEntityNames.PROJECT_TASK_PRIORITIES, FreshServiceHeaders.PROJECT_TASK_PRIORITIES),
            Map.entry(FreshServiceEntityNames.PROJECT_TASK_TYPE_FIELDS, FreshServiceHeaders.PROJECT_TASK_TYPE_FIELDS),
            Map.entry(FreshServiceEntityNames.PROJECT_TASKS, FreshServiceHeaders.PROJECT_TASKS),
            Map.entry(FreshServiceEntityNames.PROJECT_TEMPLATES, FreshServiceHeaders.PROJECT_TEMPLATES),
            Map.entry(FreshServiceEntityNames.PROJECT_VERSIONS, FreshServiceHeaders.PROJECT_VERSIONS),
            Map.entry(FreshServiceEntityNames.PROJECTS_MEMBERSHIPS, FreshServiceHeaders.PROJECTS_MEMBERSHIPS),
            Map.entry(FreshServiceEntityNames.PROJECTS_TASK_STATUES, FreshServiceHeaders.PROJECTS_TASK_STATUES),
            Map.entry(FreshServiceEntityNames.PROJECTS_TASK_TYPES, FreshServiceHeaders.PROJECTS_TASK_TYPES),
            Map.entry(FreshServiceEntityNames.PROJECTS, FreshServiceHeaders.PROJECTS),
            Map.entry(FreshServiceEntityNames.PURCHASE_ORDERS, FreshServiceHeaders.PURCHASE_ORDERS),
            Map.entry(FreshServiceEntityNames.RELATIONSHIP_TYPES, FreshServiceHeaders.RELATIONSHIP_TYPES),
            Map.entry(FreshServiceEntityNames.RELATIONSHIPS, FreshServiceHeaders.RELATIONSHIPS),
            Map.entry(FreshServiceEntityNames.RELEASE_FIELDS, FreshServiceHeaders.RELEASE_FIELDS),
            Map.entry(FreshServiceEntityNames.RELEASES_NOTES, FreshServiceHeaders.RELEASES_NOTES),
            Map.entry(FreshServiceEntityNames.RELEASES_TASKS, FreshServiceHeaders.RELEASES_TASKS),
            Map.entry(FreshServiceEntityNames.RELEASES_TIME_ENTRIES, FreshServiceHeaders.RELEASES_TIME_ENTRIES),
            Map.entry(FreshServiceEntityNames.RELEASES, FreshServiceHeaders.RELEASES),
            Map.entry(FreshServiceEntityNames.REQUESTER_FIELDS, FreshServiceHeaders.REQUESTER_FIELDS),
            Map.entry(FreshServiceEntityNames.REQUESTER_GROUPS, FreshServiceHeaders.REQUESTER_GROUPS),
            Map.entry(FreshServiceEntityNames.REQUESTERS, FreshServiceHeaders.REQUESTERS),
            Map.entry(FreshServiceEntityNames.ROLES, FreshServiceHeaders.ROLES),
            Map.entry(FreshServiceEntityNames.SERVICE_CATALOG_CATEGORIES, FreshServiceHeaders.SERVICE_CATALOG_CATEGORIES),
            Map.entry(FreshServiceEntityNames.SERVICE_CATALOG_ITEMS, FreshServiceHeaders.SERVICE_CATALOG_ITEMS),
            Map.entry(FreshServiceEntityNames.SERVICE_CATALOG_SHARED_FIELDS, FreshServiceHeaders.SERVICE_CATALOG_SHARED_FIELDS),
            Map.entry(FreshServiceEntityNames.SLA_POLICIES, FreshServiceHeaders.SLA_POLICIES),
            Map.entry(FreshServiceEntityNames.SOLUTION_CATEGORIES, FreshServiceHeaders.SOLUTION_CATEGORIES),
            Map.entry(FreshServiceEntityNames.TICKET_ACTIVITIES, FreshServiceHeaders.TICKET_ACTIVITIES),
            Map.entry(FreshServiceEntityNames.TICKET_CONVERSATIONS, FreshServiceHeaders.TICKET_CONVERSATIONS),
            Map.entry(FreshServiceEntityNames.TICKET_FIELDS, FreshServiceHeaders.TICKET_FIELDS),
            Map.entry(FreshServiceEntityNames.TICKET_TASKS, FreshServiceHeaders.TICKET_TASKS),
            Map.entry(FreshServiceEntityNames.TICKET_TIME_ENTRIES, FreshServiceHeaders.TICKET_TIME_ENTRIES),
            Map.entry(FreshServiceEntityNames.TICKETS, FreshServiceHeaders.TICKETS),
            Map.entry(FreshServiceEntityNames.VENDORS, FreshServiceHeaders.VENDORS),
            Map.entry(FreshServiceEntityNames.WORKSPACES, FreshServiceHeaders.WORKSPACES)

            // Tried to include below entities but they are causing issues mentioned in dev notes,will revisited later.
//            Map.entry(FreshServiceEntityNames.SOLUTION_ARTICLES, FreshServiceHeaders.SOLUTION_ARTICLES),
//            Map.entry(FreshServiceEntityNames.SOLUTION_FOLDERS, FreshServiceHeaders.SOLUTION_FOLDERS),
//        Map.entry(FreshServiceEntityNames.JOURNEY_REQUEST_ACTIVITIES, FreshServiceHeaders.JOURNEY_REQUEST_ACTIVITIES),
//        Map.entry(FreshServiceEntityNames.JOURNEY_REQUESTS, FreshServiceHeaders.JOURNEY_REQUESTS),
//        Map.entry(FreshServiceEntityNames.JOURNEYS_CONFIGS_DATA_FIELDS, FreshServiceHeaders.JOURNEYS_CONFIGS_DATA_FIELDS),
//        Map.entry(FreshServiceEntityNames.JOURNEYS_CONFIGS, FreshServiceHeaders.JOURNEYS_CONFIGS),
//        Map.entry(FreshServiceEntityNames.TICKET_APPROVAL_GROUPS, FreshServiceHeaders.TICKET_APPROVAL_GROUPS),
//        Map.entry(FreshServiceEntityNames.TICKETS_REQUESTED_ITEMS, FreshServiceHeaders.TICKETS_REQUESTED_ITEMS),
//        Map.entry(FreshServiceEntityNames.CHANGES_APPROVALS, FreshServiceHeaders.CHANGES_APPROVALS),
    );

    /**
     * Entities that support delta sync with updated_since parameter.
     * These entities can be incrementally synced based on the last sync timestamp.
     */
    public static final Map<String, String[]> DELTA_HEADERS_BY_ENTITY = Map.ofEntries(
            Map.entry(FreshServiceEntityNames.TICKETS, FreshServiceHeaders.TICKETS),
            Map.entry(FreshServiceEntityNames.PROBLEMS, FreshServiceHeaders.PROBLEMS),
            Map.entry(FreshServiceEntityNames.CHANGES, FreshServiceHeaders.CHANGES),
            Map.entry(FreshServiceEntityNames.RELEASES, FreshServiceHeaders.RELEASES)
    );

    /**
     * Entities that do NOT support delta sync and require full refresh.
     * These are typically configuration/reference entities that don't change frequently.
     */
    public static final Map<String, String[]> NON_DELTA_HEADERS_BY_ENTITY = Map.ofEntries(
            Map.entry(FreshServiceEntityNames.ASSETS, FreshServiceHeaders.ASSETS),
            Map.entry(FreshServiceEntityNames.REQUESTERS, FreshServiceHeaders.REQUESTERS),
            Map.entry(FreshServiceEntityNames.AGENTS, FreshServiceHeaders.AGENTS),
            Map.entry(FreshServiceEntityNames.AGENT_FIELDS, FreshServiceHeaders.AGENT_FIELDS),
            Map.entry(FreshServiceEntityNames.ANNOUNCEMENTS, FreshServiceHeaders.ANNOUNCEMENTS),
            Map.entry(FreshServiceEntityNames.APPLICATION_INSTALLATIONS, FreshServiceHeaders.APPLICATION_INSTALLATIONS),
            Map.entry(FreshServiceEntityNames.APPLICATION_LICENSES, FreshServiceHeaders.APPLICATION_LICENSES),
            Map.entry(FreshServiceEntityNames.APPLICATION_RELATIONSHIPS, FreshServiceHeaders.APPLICATION_RELATIONSHIPS),
            Map.entry(FreshServiceEntityNames.APPLICATION_USERS, FreshServiceHeaders.APPLICATION_USERS),
            Map.entry(FreshServiceEntityNames.APPLICATIONS, FreshServiceHeaders.APPLICATIONS),
            Map.entry(FreshServiceEntityNames.ASSET_TYPES_FIELDS, FreshServiceHeaders.ASSET_TYPES_FIELDS),
            Map.entry(FreshServiceEntityNames.ASSET_TYPES, FreshServiceHeaders.ASSET_TYPES),
            Map.entry(FreshServiceEntityNames.BUSINESS_HOURS, FreshServiceHeaders.BUSINESS_HOURS),
            Map.entry(FreshServiceEntityNames.CABS, FreshServiceHeaders.CABS),
            Map.entry(FreshServiceEntityNames.CANNED_RESPONSES, FreshServiceHeaders.CANNED_RESPONSES),
            Map.entry(FreshServiceEntityNames.CANNED_RESPONSE_FOLDERS, FreshServiceHeaders.CANNED_RESPONSE_FOLDERS),
            Map.entry(FreshServiceEntityNames.CHANGES_FORM_FIELDS, FreshServiceHeaders.CHANGES_FORM_FIELDS),
            Map.entry(FreshServiceEntityNames.CONTRACT_ATTACHMENTS, FreshServiceHeaders.CONTRACT_ATTACHMENTS),
            Map.entry(FreshServiceEntityNames.CONTRACTS, FreshServiceHeaders.CONTRACTS),
            Map.entry(FreshServiceEntityNames.CSAT_RESPONSE, FreshServiceHeaders.CSAT_RESPONSE),
            Map.entry(FreshServiceEntityNames.CUSTOM_OBJECTS, FreshServiceHeaders.CUSTOM_OBJECTS),
            Map.entry(FreshServiceEntityNames.DEPARTMENT_FIELDS, FreshServiceHeaders.DEPARTMENT_FIELDS),
            Map.entry(FreshServiceEntityNames.DEPARTMENTS, FreshServiceHeaders.DEPARTMENTS),
            Map.entry(FreshServiceEntityNames.GROUPS, FreshServiceHeaders.GROUPS),
            Map.entry(FreshServiceEntityNames.LOCATIONS, FreshServiceHeaders.LOCATIONS),
            Map.entry(FreshServiceEntityNames.OBJECT_RECORDS, FreshServiceHeaders.OBJECT_RECORDS),
            Map.entry(FreshServiceEntityNames.OFFBOARDING_REQUESTS, FreshServiceHeaders.OFFBOARDING_REQUESTS),
            Map.entry(FreshServiceEntityNames.ONBOARDING_REQUESTS, FreshServiceHeaders.ONBOARDING_REQUESTS),
            Map.entry(FreshServiceEntityNames.ONCALL_SCHEDULES, FreshServiceHeaders.ONCALL_SCHEDULES),
            Map.entry(FreshServiceEntityNames.ONCALL_SHIFT_EVENTS, FreshServiceHeaders.ONCALL_SHIFT_EVENTS),
            Map.entry(FreshServiceEntityNames.POST_INCIDENT_REPORT_TEMPLATES, FreshServiceHeaders.POST_INCIDENT_REPORT_TEMPLATES),
            Map.entry(FreshServiceEntityNames.PROBLEM_FIELDS, FreshServiceHeaders.PROBLEM_FIELDS),
            Map.entry(FreshServiceEntityNames.PRODUCTS, FreshServiceHeaders.PRODUCTS),
            Map.entry(FreshServiceEntityNames.PROJECT_FIELDS, FreshServiceHeaders.PROJECT_FIELDS),
            Map.entry(FreshServiceEntityNames.PROJECT_SPRINTS, FreshServiceHeaders.PROJECT_SPRINTS),
            Map.entry(FreshServiceEntityNames.PROJECT_TASK_NOTES, FreshServiceHeaders.PROJECT_TASK_NOTES),
            Map.entry(FreshServiceEntityNames.PROJECT_TASK_PRIORITIES, FreshServiceHeaders.PROJECT_TASK_PRIORITIES),
            Map.entry(FreshServiceEntityNames.PROJECT_TASK_TYPE_FIELDS, FreshServiceHeaders.PROJECT_TASK_TYPE_FIELDS),
            Map.entry(FreshServiceEntityNames.PROJECT_TASKS, FreshServiceHeaders.PROJECT_TASKS),
            Map.entry(FreshServiceEntityNames.PROJECT_TEMPLATES, FreshServiceHeaders.PROJECT_TEMPLATES),
            Map.entry(FreshServiceEntityNames.PROJECT_VERSIONS, FreshServiceHeaders.PROJECT_VERSIONS),
            Map.entry(FreshServiceEntityNames.PROJECTS_MEMBERSHIPS, FreshServiceHeaders.PROJECTS_MEMBERSHIPS),
            Map.entry(FreshServiceEntityNames.PROJECTS_TASK_STATUES, FreshServiceHeaders.PROJECTS_TASK_STATUES),
            Map.entry(FreshServiceEntityNames.PROJECTS_TASK_TYPES, FreshServiceHeaders.PROJECTS_TASK_TYPES),
            Map.entry(FreshServiceEntityNames.PROJECTS, FreshServiceHeaders.PROJECTS),
            Map.entry(FreshServiceEntityNames.PURCHASE_ORDERS, FreshServiceHeaders.PURCHASE_ORDERS),
            Map.entry(FreshServiceEntityNames.RELATIONSHIP_TYPES, FreshServiceHeaders.RELATIONSHIP_TYPES),
            Map.entry(FreshServiceEntityNames.RELATIONSHIPS, FreshServiceHeaders.RELATIONSHIPS),
            Map.entry(FreshServiceEntityNames.RELEASE_FIELDS, FreshServiceHeaders.RELEASE_FIELDS),
            Map.entry(FreshServiceEntityNames.REQUESTER_FIELDS, FreshServiceHeaders.REQUESTER_FIELDS),
            Map.entry(FreshServiceEntityNames.REQUESTER_GROUPS, FreshServiceHeaders.REQUESTER_GROUPS),
            Map.entry(FreshServiceEntityNames.ROLES, FreshServiceHeaders.ROLES),
            Map.entry(FreshServiceEntityNames.SERVICE_CATALOG_CATEGORIES, FreshServiceHeaders.SERVICE_CATALOG_CATEGORIES),
            Map.entry(FreshServiceEntityNames.SERVICE_CATALOG_ITEMS, FreshServiceHeaders.SERVICE_CATALOG_ITEMS),
            Map.entry(FreshServiceEntityNames.SERVICE_CATALOG_SHARED_FIELDS, FreshServiceHeaders.SERVICE_CATALOG_SHARED_FIELDS),
            Map.entry(FreshServiceEntityNames.SLA_POLICIES, FreshServiceHeaders.SLA_POLICIES),
            Map.entry(FreshServiceEntityNames.SOLUTION_ARTICLES, FreshServiceHeaders.SOLUTION_ARTICLES),
            Map.entry(FreshServiceEntityNames.SOLUTION_CATEGORIES, FreshServiceHeaders.SOLUTION_CATEGORIES),
            Map.entry(FreshServiceEntityNames.SOLUTION_FOLDERS, FreshServiceHeaders.SOLUTION_FOLDERS),
            Map.entry(FreshServiceEntityNames.TICKET_FIELDS, FreshServiceHeaders.TICKET_FIELDS),
            Map.entry(FreshServiceEntityNames.VENDORS, FreshServiceHeaders.VENDORS),
            Map.entry(FreshServiceEntityNames.WORKSPACES, FreshServiceHeaders.WORKSPACES)
    );

    /**
     * Common response wrapper keys used by FreshServices API.
     * The API typically wraps data in these keys.
     */
    public static final String[] COMMON_RESPONSE_KEYS = {
        "data",
        "items",
        "results",
        "records"
    };

    /**
     * Maps entity names to their expected response wrapper keys.
     * This allows entity-specific response key configurations.
     *
     * Format: entity_name -> response_wrapper_key
     * Example: "CONTRACTS" -> "contracts"
     */
    public static final Map<String, String> ENTITY_RESPONSE_KEY_MAP = Map.ofEntries(
        Map.entry(FreshServiceEntityNames.AGENTS, "agents"),
        Map.entry(FreshServiceEntityNames.ANNOUNCEMENTS, "announcements"),
        Map.entry(FreshServiceEntityNames.APPLICATIONS, "applications"),
        Map.entry(FreshServiceEntityNames.APPLICATION_INSTALLATIONS, "installations"),
        Map.entry(FreshServiceEntityNames.APPLICATION_USERS, "application_users"),
        Map.entry(FreshServiceEntityNames.APPLICATION_RELATIONSHIPS, "relationships"),
        Map.entry(FreshServiceEntityNames.APPLICATION_LICENSES, "licenses"),
        Map.entry(FreshServiceEntityNames.ASSETS, "assets"),
        Map.entry(FreshServiceEntityNames.ASSETS_COMPONENTS, "components"),
        Map.entry(FreshServiceEntityNames.ASSETS_CONTRACTS, "contracts"),
        Map.entry(FreshServiceEntityNames.ASSETS_REQUESTS, "requests"),
        Map.entry(FreshServiceEntityNames.CHANGES_FORM_FIELDS, "change_fields"),
        Map.entry(FreshServiceEntityNames.RELEASE_FIELDS, "release_fields"),
        Map.entry(FreshServiceEntityNames.AGENT_FIELDS, "agent_fields"),
        Map.entry(FreshServiceEntityNames.BUSINESS_HOURS, "business_hours"),
        Map.entry(FreshServiceEntityNames.CANNED_RESPONSES, "canned_responses"),
        Map.entry(FreshServiceEntityNames.CHANGES, "changes"),
        Map.entry(FreshServiceEntityNames.CHANGES_APPROVALS, "approvals"),
        Map.entry(FreshServiceEntityNames.CHANGES_APPROVAL_GROUPS, "approval_groups"),
        Map.entry(FreshServiceEntityNames.CHANGES_NOTES, "notes"),
        Map.entry(FreshServiceEntityNames.CHANGES_TASKS, "tasks"),
        Map.entry(FreshServiceEntityNames.CHANGES_TIME_ENTRIES, "time_entries"),
        Map.entry(FreshServiceEntityNames.CONTRACTS, "contracts"),
        Map.entry(FreshServiceEntityNames.CONTRACT_ATTACHMENTS, "attachments"),
        Map.entry(FreshServiceEntityNames.CSAT_RESPONSE, "csat_response"),
        Map.entry(FreshServiceEntityNames.CUSTOM_OBJECTS, "custom_objects"),
        Map.entry(FreshServiceEntityNames.DEPARTMENTS, "departments"),
        Map.entry(FreshServiceEntityNames.DEPARTMENT_FIELDS, "department_fields"),
        Map.entry(FreshServiceEntityNames.GROUPS, "groups"),
        Map.entry(FreshServiceEntityNames.LOCATIONS, "locations"),
        Map.entry(FreshServiceEntityNames.PROBLEMS, "problems"),
        Map.entry(FreshServiceEntityNames.PROBLEM_NOTES, "notes"),
        Map.entry(FreshServiceEntityNames.PROBLEM_TASKS, "tasks"),
        Map.entry(FreshServiceEntityNames.PROBLEM_TIME_ENTRIES, "time_entries"),
        Map.entry(FreshServiceEntityNames.ASSET_TYPES_FIELDS, "asset_type_fields"),
        Map.entry(FreshServiceEntityNames.PRODUCTS, "products"),
        Map.entry(FreshServiceEntityNames.PROJECTS, "projects"),
        Map.entry(FreshServiceEntityNames.PROJECT_FIELDS, "project_fields"),
        Map.entry(FreshServiceEntityNames.PROJECT_SPRINTS, "sprints"),
        Map.entry(FreshServiceEntityNames.PROJECT_TASKS, "tasks"),
        Map.entry(FreshServiceEntityNames.PROJECT_TASK_PRIORITIES, "task_priorities"),
        Map.entry(FreshServiceEntityNames.PROJECT_TEMPLATES, "project_templates"),
        Map.entry(FreshServiceEntityNames.PROJECT_VERSIONS, "versions"),
        Map.entry(FreshServiceEntityNames.PROJECTS_MEMBERSHIPS, "memberships"),
        Map.entry(FreshServiceEntityNames.PROJECTS_TASK_STATUES, "task_statuses"),
        Map.entry(FreshServiceEntityNames.PROJECTS_TASK_TYPES, "task_types"),
        Map.entry(FreshServiceEntityNames.RELEASES, "releases"),
        Map.entry(FreshServiceEntityNames.RELEASES_NOTES, "notes"),
        Map.entry(FreshServiceEntityNames.RELEASES_TASKS, "tasks"),
        Map.entry(FreshServiceEntityNames.RELEASES_TIME_ENTRIES, "time_entries"),
        Map.entry(FreshServiceEntityNames.RELATIONSHIP_TYPES, "relationship_types"),
        Map.entry(FreshServiceEntityNames.RELATIONSHIPS, "relationships"),
        Map.entry(FreshServiceEntityNames.REQUESTERS, "requesters"),
        Map.entry(FreshServiceEntityNames.REQUESTER_FIELDS, "requester_fields"),
        Map.entry(FreshServiceEntityNames.SERVICE_CATALOG_CATEGORIES, "service_categories"),
        Map.entry(FreshServiceEntityNames.SERVICE_CATALOG_ITEMS, "service_items"),
        Map.entry(FreshServiceEntityNames.SERVICE_CATALOG_SHARED_FIELDS, "fields"),
        Map.entry(FreshServiceEntityNames.SLA_POLICIES, "sla_policies"),
        Map.entry(FreshServiceEntityNames.SOLUTION_ARTICLES, "articles"),
        Map.entry(FreshServiceEntityNames.SOLUTION_CATEGORIES, "categories"),
        Map.entry(FreshServiceEntityNames.SOLUTION_FOLDERS, "folders"),
        Map.entry(FreshServiceEntityNames.ROLES, "roles"),
        Map.entry(FreshServiceEntityNames.TICKETS, "tickets"),
        Map.entry(FreshServiceEntityNames.TICKET_ACTIVITIES, "activities"),
        Map.entry(FreshServiceEntityNames.TICKET_APPROVAL_GROUPS, "approval_groups"),
        Map.entry(FreshServiceEntityNames.TICKET_CONVERSATIONS, "conversations"),
        Map.entry(FreshServiceEntityNames.TICKET_FIELDS, "ticket_fields"),
        Map.entry(FreshServiceEntityNames.TICKET_TASKS, "tasks"),
        Map.entry(FreshServiceEntityNames.TICKET_TIME_ENTRIES, "time_entries"),
        Map.entry(FreshServiceEntityNames.TICKETS_REQUESTED_ITEMS, "requested_items"),
        Map.entry(FreshServiceEntityNames.OBJECT_RECORDS, "records"),
        Map.entry(FreshServiceEntityNames.OFFBOARDING_REQUESTS, "offboarding_requests"),
        Map.entry(FreshServiceEntityNames.ONBOARDING_REQUESTS, "onboarding_requests"),
        Map.entry(FreshServiceEntityNames.ONCALL_SCHEDULES, "schedules"),
        Map.entry(FreshServiceEntityNames.POST_INCIDENT_REPORT_TEMPLATES, "post_incident_report_templates"),
        Map.entry(FreshServiceEntityNames.VENDORS, "vendors"),
        Map.entry(FreshServiceEntityNames.WORKSPACES, "workspaces")
        // Add more mappings as needed
    );

    /**
     * Gets possible response wrapper keys for a given entity.
     * Returns entity-specific key if configured, otherwise returns common keys.
     *
     * @param entityName The entity name
     * @return Array of possible response wrapper keys to try
     */
    public static String[] getPossibleResponseKeys(String entityName) {
        List<String> keys = new ArrayList<>();

        // Add entity-specific key if configured
        if (ENTITY_RESPONSE_KEY_MAP.containsKey(entityName)) {
            keys.add(ENTITY_RESPONSE_KEY_MAP.get(entityName));
        }

        // Add normalized variations of entity name
        if (entityName != null) {
            keys.add(entityName.toLowerCase());
            keys.add(entityName.toLowerCase().replace("-", "_"));
            keys.add(entityName.toLowerCase().replace("/", "_"));
            keys.add(entityName.toUpperCase());
            keys.add(entityName); // Original case
        }

        // Add common response keys
        for (String commonKey : COMMON_RESPONSE_KEYS) {
            if (!keys.contains(commonKey)) {
                keys.add(commonKey);
            }
        }

        return keys.toArray(new String[0]);
    }

    /**
     * Gets the expected response wrapper key for an entity.
     * Returns null if not specifically configured.
     */
    public static String getEntityResponseKey(String entityName) {
        return ENTITY_RESPONSE_KEY_MAP.get(entityName);
    }

    public static String getUriPath(String entityName){
        return API_BASE_PATH + entityName.toLowerCase();
    }

    public static final Map<String, List<String>> ENTITY_DEPENDENCY_MAP = Map.ofEntries(
            Map.entry(FreshServiceEntityNames.APPLICATIONS, List.of(FreshServiceEntityNames.APPLICATION_INSTALLATIONS,
                    FreshServiceEntityNames.APPLICATION_LICENSES, FreshServiceEntityNames.APPLICATION_RELATIONSHIPS,
                    FreshServiceEntityNames.APPLICATION_USERS)),
            Map.entry(FreshServiceEntityNames.ASSET_TYPES, List.of(FreshServiceEntityNames.ASSET_TYPES_FIELDS)),
            Map.entry(FreshServiceEntityNames.ASSETS, List.of(FreshServiceEntityNames.ASSETS_COMPONENTS, FreshServiceEntityNames.ASSETS_REQUESTS,
                    FreshServiceEntityNames.ASSETS_CONTRACTS)),
            Map.entry(FreshServiceEntityNames.CHANGES, List.of(FreshServiceEntityNames.CHANGES_APPROVAL_GROUPS,
                    FreshServiceEntityNames.CHANGES_APPROVALS, FreshServiceEntityNames.CHANGES_NOTES,
                    FreshServiceEntityNames.CHANGES_TASKS, FreshServiceEntityNames.CHANGES_TIME_ENTRIES)),
            Map.entry(FreshServiceEntityNames.CONTRACTS, List.of(FreshServiceEntityNames.CONTRACT_ATTACHMENTS)),
            Map.entry(FreshServiceEntityNames.CUSTOM_OBJECTS, List.of(FreshServiceEntityNames.OBJECT_RECORDS)),
            Map.entry(FreshServiceEntityNames.PROBLEMS, List.of(FreshServiceEntityNames.PROBLEM_NOTES,
                    FreshServiceEntityNames.PROBLEM_TASKS, FreshServiceEntityNames.PROBLEM_TIME_ENTRIES)),
            Map.entry(FreshServiceEntityNames.PROJECTS, List.of(FreshServiceEntityNames.PROJECT_SPRINTS,
                    FreshServiceEntityNames.PROJECT_TASK_PRIORITIES, FreshServiceEntityNames.PROJECT_TASKS,
                    FreshServiceEntityNames.PROJECT_VERSIONS, FreshServiceEntityNames.PROJECTS_MEMBERSHIPS,
                    FreshServiceEntityNames.PROJECTS_TASK_STATUES, FreshServiceEntityNames.PROJECTS_TASK_TYPES)),
            Map.entry(FreshServiceEntityNames.RELEASES, List.of(FreshServiceEntityNames.RELEASES_NOTES,
                    FreshServiceEntityNames.RELEASES_TASKS, FreshServiceEntityNames.RELEASES_TIME_ENTRIES)),
            Map.entry(FreshServiceEntityNames.SOLUTION_CATEGORIES, List.of(FreshServiceEntityNames.SOLUTION_FOLDERS)),
            Map.entry(FreshServiceEntityNames.TICKETS, List.of(FreshServiceEntityNames.TICKET_ACTIVITIES,
                    FreshServiceEntityNames.TICKET_APPROVAL_GROUPS, FreshServiceEntityNames.TICKET_CONVERSATIONS,
                    FreshServiceEntityNames.TICKET_TASKS, FreshServiceEntityNames.TICKET_TIME_ENTRIES,
                    FreshServiceEntityNames.TICKETS_REQUESTED_ITEMS)),
            Map.entry(FreshServiceEntityNames.ONCALL_SCHEDULES, List.of(FreshServiceEntityNames.ONCALL_SHIFT_EVENTS))
    );


    public static Map<String, String> ENTITY_API_PATH_MAP = new HashMap<>();

    public static Map<String, String> getEntityApiPathMap() {

        ENTITY_API_PATH_MAP.put(FreshServiceEntityNames.PROBLEM_FIELDS, API_BASE_PATH + "problem_form_fields");
        ENTITY_API_PATH_MAP.put(FreshServiceEntityNames.CHANGES_FORM_FIELDS, API_BASE_PATH + "change_form_fields");
        ENTITY_API_PATH_MAP.put(FreshServiceEntityNames.RELEASE_FIELDS, API_BASE_PATH + "release_form_fields");
        ENTITY_API_PATH_MAP.put(FreshServiceEntityNames.SOLUTION_CATEGORIES, API_BASE_PATH + "solutions/categories");
        ENTITY_API_PATH_MAP.put(FreshServiceEntityNames.SERVICE_CATALOG_CATEGORIES, API_BASE_PATH + "service_catalog/categories");
        ENTITY_API_PATH_MAP.put(FreshServiceEntityNames.APPLICATION_INSTALLATIONS, API_BASE_PATH + "applications/{application_id}/installations");
        ENTITY_API_PATH_MAP.put(FreshServiceEntityNames.APPLICATION_LICENSES, API_BASE_PATH + "applications/{application_id}/licenses");
        ENTITY_API_PATH_MAP.put(FreshServiceEntityNames.APPLICATION_USERS, API_BASE_PATH + "applications/{application_id}/users");
        ENTITY_API_PATH_MAP.put(FreshServiceEntityNames.APPLICATION_RELATIONSHIPS, API_BASE_PATH + "applications/{application_id}/relationships");
        ENTITY_API_PATH_MAP.put(FreshServiceEntityNames.ASSET_TYPES_FIELDS, API_BASE_PATH + "asset_types/{asset_types_id}/fields");
        ENTITY_API_PATH_MAP.put(FreshServiceEntityNames.ASSETS_COMPONENTS, API_BASE_PATH + "assets/{assets_display_id}/components");
        ENTITY_API_PATH_MAP.put(FreshServiceEntityNames.ASSETS_REQUESTS, API_BASE_PATH + "assets/{assets_display_id}/requests");
        ENTITY_API_PATH_MAP.put(FreshServiceEntityNames.ASSETS_CONTRACTS, API_BASE_PATH + "assets/{assets_display_id}/contracts");
        ENTITY_API_PATH_MAP.put(FreshServiceEntityNames.CHANGES_NOTES, API_BASE_PATH + "changes/{changes_id}/notes");
        ENTITY_API_PATH_MAP.put(FreshServiceEntityNames.CHANGES_APPROVALS, API_BASE_PATH + "changes/{changes_id}/approvals");
        ENTITY_API_PATH_MAP.put(FreshServiceEntityNames.CHANGES_TASKS, API_BASE_PATH + "changes/{changes_id}/tasks");
        ENTITY_API_PATH_MAP.put(FreshServiceEntityNames.CHANGES_APPROVAL_GROUPS, API_BASE_PATH + "changes/{changes_id}/approval-groups");
        ENTITY_API_PATH_MAP.put(FreshServiceEntityNames.CHANGES_TIME_ENTRIES, API_BASE_PATH + "changes/{changes_id}/time_entries");
        ENTITY_API_PATH_MAP.put(FreshServiceEntityNames.CONTRACT_ATTACHMENTS, API_BASE_PATH + "contracts/{contract_id}/attachments");
        ENTITY_API_PATH_MAP.put(FreshServiceEntityNames.DEPARTMENT_FIELDS, API_BASE_PATH + "department_fields");
        ENTITY_API_PATH_MAP.put(FreshServiceEntityNames.PROBLEM_NOTES, API_BASE_PATH + "problems/{problem_id}/notes");
        ENTITY_API_PATH_MAP.put(FreshServiceEntityNames.PROBLEM_TASKS, API_BASE_PATH + "problems/{problem_id}/tasks");
        ENTITY_API_PATH_MAP.put(FreshServiceEntityNames.PROBLEM_TIME_ENTRIES, API_BASE_PATH + "problems/{problem_id}/time_entries");
        ENTITY_API_PATH_MAP.put(FreshServiceEntityNames.PROJECTS, API_BASE_PATH + "pm/projects");
        ENTITY_API_PATH_MAP.put(FreshServiceEntityNames.PROJECT_FIELDS, API_BASE_PATH + "pm/project-fields");
        ENTITY_API_PATH_MAP.put(FreshServiceEntityNames.PROJECT_SPRINTS, API_BASE_PATH + "pm/projects/{projects_id}/sprints");
        ENTITY_API_PATH_MAP.put(FreshServiceEntityNames.PROJECT_TASK_PRIORITIES, API_BASE_PATH + "pm/projects/{projects_id}/task-priorities");
        ENTITY_API_PATH_MAP.put(FreshServiceEntityNames.PROJECT_TASKS, API_BASE_PATH + "pm/projects/{projects_id}/tasks");
        ENTITY_API_PATH_MAP.put(FreshServiceEntityNames.PROJECT_TEMPLATES, API_BASE_PATH + "pm/project_templates");
        ENTITY_API_PATH_MAP.put(FreshServiceEntityNames.PROJECT_VERSIONS, API_BASE_PATH + "pm/projects/{projects_id}/versions");
        ENTITY_API_PATH_MAP.put(FreshServiceEntityNames.PROJECTS_MEMBERSHIPS, API_BASE_PATH + "pm/projects/{projects_id}/memberships");
        ENTITY_API_PATH_MAP.put(FreshServiceEntityNames.PROJECTS_TASK_STATUES, API_BASE_PATH + "pm/projects/{projects_id}/task-statuses");
        ENTITY_API_PATH_MAP.put(FreshServiceEntityNames.PROJECTS_TASK_TYPES, API_BASE_PATH + "pm/projects/{projects_id}/task-types");
        ENTITY_API_PATH_MAP.put(FreshServiceEntityNames.RELEASES_NOTES, API_BASE_PATH + "releases/{release_id}/notes");
        ENTITY_API_PATH_MAP.put(FreshServiceEntityNames.RELEASES_TASKS, API_BASE_PATH + "releases/{release_id}/tasks");
        ENTITY_API_PATH_MAP.put(FreshServiceEntityNames.RELEASES_TIME_ENTRIES, API_BASE_PATH + "releases/{release_id}/time_entries");
        ENTITY_API_PATH_MAP.put(FreshServiceEntityNames.RELATIONSHIP_TYPES, API_BASE_PATH + "relationship_types");
        ENTITY_API_PATH_MAP.put(FreshServiceEntityNames.RELATIONSHIPS, API_BASE_PATH + "relationships");
        ENTITY_API_PATH_MAP.put(FreshServiceEntityNames.REQUESTER_FIELDS, API_BASE_PATH + "requester_fields");
        ENTITY_API_PATH_MAP.put(FreshServiceEntityNames.REQUESTERS, API_BASE_PATH + "requesters");
        ENTITY_API_PATH_MAP.put(FreshServiceEntityNames.TICKET_FIELDS, API_BASE_PATH + "ticket_form_fields");
        ENTITY_API_PATH_MAP.put(FreshServiceEntityNames.TICKET_ACTIVITIES, API_BASE_PATH + "tickets/{ticket_id}/activities");
        ENTITY_API_PATH_MAP.put(FreshServiceEntityNames.TICKET_APPROVAL_GROUPS, API_BASE_PATH + "tickets/{ticket_id}/approval-groups");
        ENTITY_API_PATH_MAP.put(FreshServiceEntityNames.TICKET_CONVERSATIONS, API_BASE_PATH + "tickets/{ticket_id}/conversations");
        ENTITY_API_PATH_MAP.put(FreshServiceEntityNames.TICKET_TASKS, API_BASE_PATH + "tickets/{ticket_id}/tasks");
        ENTITY_API_PATH_MAP.put(FreshServiceEntityNames.TICKET_TIME_ENTRIES, API_BASE_PATH + "tickets/{ticket_id}/time_entries");
        ENTITY_API_PATH_MAP.put(FreshServiceEntityNames.TICKETS_REQUESTED_ITEMS, API_BASE_PATH + "tickets/{ticket_id}/requested_items");
        ENTITY_API_PATH_MAP.put(FreshServiceEntityNames.CUSTOM_OBJECTS, API_BASE_PATH + "objects");
        ENTITY_API_PATH_MAP.put(FreshServiceEntityNames.OBJECT_RECORDS, API_BASE_PATH + "objects/{object_id}/records");
        ENTITY_API_PATH_MAP.put(FreshServiceEntityNames.SERVICE_CATALOG_ITEMS, API_BASE_PATH + "service_catalog/items");
        ENTITY_API_PATH_MAP.put(FreshServiceEntityNames.SERVICE_CATALOG_SHARED_FIELDS, API_BASE_PATH + "service_catalog/fields");
        ENTITY_API_PATH_MAP.put(FreshServiceEntityNames.SLA_POLICIES, API_BASE_PATH + "sla_policies");
        ENTITY_API_PATH_MAP.put(FreshServiceEntityNames.SOLUTION_ARTICLES, API_BASE_PATH + "solutions/articles");
        ENTITY_API_PATH_MAP.put(FreshServiceEntityNames.SOLUTION_FOLDERS, API_BASE_PATH + "solutions/folders");
        ENTITY_API_PATH_MAP.put(FreshServiceEntityNames.OFFBOARDING_REQUESTS, API_BASE_PATH + "offboarding_requests");
        ENTITY_API_PATH_MAP.put(FreshServiceEntityNames.ONBOARDING_REQUESTS, API_BASE_PATH + "onboarding_requests");
        ENTITY_API_PATH_MAP.put(FreshServiceEntityNames.ONCALL_SCHEDULES, API_BASE_PATH + "on_call_schedules");
        ENTITY_API_PATH_MAP.put(FreshServiceEntityNames.ONCALL_SHIFT_EVENTS, API_BASE_PATH + "on_call_schedules/{schedule_id}/events");
        ENTITY_API_PATH_MAP.put(FreshServiceEntityNames.POST_INCIDENT_REPORT_TEMPLATES, API_BASE_PATH + "post-incident-reports/templates");

        HEADERS_BY_ENTITY.keySet().forEach(entity -> ENTITY_API_PATH_MAP.putIfAbsent(entity, getUriPath(entity)));
        return ENTITY_API_PATH_MAP;
    }

    private FreshServiceConstants() {}
}
