package io.datalakehouse.common;

import com.fasterxml.jackson.databind.ObjectMapper;

import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class FreshServiceConstants {

    public static final String CONNECTOR_NAME = "FRESHSERVICES";
    public static final String API_BASE_PATH = "api/v2/";
    public static final String[] ID_HEADERS = {"DISPLAY_ID", "ID"};
    //
/*
    // This section is commented out as we are not using the delta sync based on timestamp fields.
    public static final String[] TIMESTAMP_FIELDS = {"UPDATED_AT", "CREATED_AT"};
    public static final DateTimeFormatter[] DATE_FORMATTERS = {
            DateTimeFormatter.ISO_DATE_TIME,
            DateTimeFormatter.ofPattern("yyyy-MM-dd'T'HH:mm:ss'Z'"),
            DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss"),
            DateTimeFormatter.ofPattern("yyyy-MM-dd'T'HH:mm:ssXXX")
    };*/

    public static final class FreshServiceEntityNames {
        public static final String AGENT_FIELDS = "AGENT_FIELDS";
        public static final String AGENTS = "AGENTS";
        public static final String AGENTS_ROLES = "AGENTS_ROLES";
        public static final String AGENTS_DEPARTMENTS = "AGENTS_DEPARTMENTS";
        public static final String AGENTS_GROUPS = "AGENTS_GROUPS";
        public static final String ANNOUNCEMENTS = "ANNOUNCEMENTS";
        public static final String APPLICATION_INSTALLATIONS = "APPLICATION_INSTALLATIONS";
        public static final String APPLICATION_LICENSES = "APPLICATION_LICENSES";
        public static final String APPLICATION_RELATIONSHIPS = "APPLICATION_RELATIONSHIPS";
        public static final String APPLICATION_USERS = "APPLICATION_USERS";
        public static final String APPLICATIONS = "APPLICATIONS";
        public static final String ASSET_TYPES = "ASSET_TYPES";
        public static final String ASSETS_COMPONENTS = "ASSETS_COMPONENTS";
        public static final String ASSETS_REQUESTS = "ASSETS_REQUESTS";
        public static final String ASSETS_CONTRACTS = "ASSETS_CONTRACTS";
        public static final String ASSETS = "ASSETS";
        public static final String BUSINESS_HOURS = "BUSINESS_HOURS";
        public static final String CANNED_RESPONSES = "CANNED_RESPONSES";
        public static final String CANNED_RESPONSE_FOLDERS = "CANNED_RESPONSE_FOLDERS";
        public static final String CHANGES_FORM_FIELDS = "CHANGES_FORM_FIELDS";
        public static final String CHANGES_NOTES = "CHANGES_NOTES";
        public static final String CHANGES_TASKS = "CHANGES_TASKS";
        public static final String CHANGES_TIME_ENTRIES = "CHANGES_TIME_ENTRIES";
        public static final String CHANGES = "CHANGES";
        public static final String CONTRACT_ATTACHMENTS = "CONTRACT_ATTACHMENTS";
        public static final String CONTRACTS = "CONTRACTS";
        public static final String CSAT_RESPONSE = "CSAT_RESPONSE";
        public static final String CUSTOM_OBJECTS = "CUSTOM_OBJECTS";
        public static final String DEPARTMENT_FIELDS = "DEPARTMENT_FIELDS";
        public static final String DEPARTMENTS = "DEPARTMENTS";
        public static final String GROUPS = "GROUPS";
        public static final String LOCATIONS = "LOCATIONS";
        public static final String OBJECT_RECORDS = "OBJECT_RECORDS";
        public static final String POST_INCIDENT_REPORT_TEMPLATES = "POST_INCIDENT_REPORT_TEMPLATES";
        public static final String PROBLEM_FIELDS = "PROBLEM_FIELDS";
        public static final String PROBLEM_NOTES = "PROBLEM_NOTES";
        public static final String PROBLEM_TASKS = "PROBLEM_TASKS";
        public static final String PROBLEM_TIME_ENTRIES = "PROBLEM_TIME_ENTRIES";
        public static final String PROBLEMS = "PROBLEMS";
        public static final String PRODUCTS = "PRODUCTS";
        public static final String PROJECT_FIELDS = "PROJECT_FIELDS";
        public static final String PROJECT_SPRINTS = "PROJECT_SPRINTS";
        public static final String PROJECT_TASK_NOTES = "PROJECT_TASK_NOTES";
        public static final String PROJECT_TASK_PRIORITIES = "PROJECT_TASK_PRIORITIES";
        public static final String PROJECT_TASK_TYPE_FIELDS = "PROJECT_TASK_TYPE_FIELDS";
        public static final String PROJECT_TASKS = "PROJECT_TASKS";
        public static final String PROJECT_TEMPLATES = "PROJECT_TEMPLATES";
        public static final String PROJECT_VERSIONS = "PROJECT_VERSIONS";
        public static final String PROJECTS_MEMBERSHIPS = "PROJECTS_MEMBERSHIPS";
        public static final String PROJECTS_TASK_STATUES = "PROJECTS_TASK_STATUES";
        public static final String PROJECTS_TASK_TYPES = "PROJECTS_TASK_TYPES";
        public static final String PROJECTS = "PROJECTS";
        public static final String PURCHASE_ORDERS = "PURCHASE_ORDERS";
        public static final String RELATIONSHIP_TYPES = "RELATIONSHIP_TYPES";
        public static final String RELATIONSHIPS = "RELATIONSHIPS";
        public static final String RELEASE_FIELDS = "RELEASE_FIELDS";
        public static final String RELEASES_NOTES = "RELEASES_NOTES";
        public static final String RELEASES_TASKS = "RELEASES_TASKS";
        public static final String RELEASES_TIME_ENTRIES = "RELEASES_TIME_ENTRIES";
        public static final String RELEASES = "RELEASES";
        public static final String REQUESTER_FIELDS = "REQUESTER_FIELDS";
        public static final String REQUESTER_GROUPS = "REQUESTER_GROUPS";
        public static final String REQUESTERS = "REQUESTERS";
        public static final String ROLES = "ROLES";
        public static final String SERVICE_CATALOG_CATEGORIES = "SERVICE_CATALOG_CATEGORIES";
        public static final String SERVICE_CATALOG_ITEMS = "SERVICE_CATALOG_ITEMS";
        public static final String SLA_POLICIES = "SLA_POLICIES";
        public static final String SOLUTION_CATEGORIES = "SOLUTION_CATEGORIES";
        public static final String TICKET_ACTIVITIES = "TICKET_ACTIVITIES";
        public static final String TICKET_CONVERSATIONS = "TICKET_CONVERSATIONS";
        public static final String TICKET_FIELDS = "TICKET_FIELDS";
        public static final String TICKET_TASKS = "TICKET_TASKS";
        public static final String TICKET_TIME_ENTRIES = "TICKET_TIME_ENTRIES";
        public static final String TICKETS = "TICKETS";
        public static final String VENDORS = "VENDORS";
        public static final String WORKSPACES = "WORKSPACES";
        public static final String AGENTS_WORKSPACES = "AGENTS_WORKSPACES";
        public static final String AGENTS_WORKLOAD_CONFIGS = "AGENTS_WORKLOAD_CONFIGS";

        private FreshServiceEntityNames() {}
    }


    public static final class FreshServiceHeaders {
        public static final String[] AGENT_FIELDS = {"NAME","AGENT_FIELDS_POSITION","USER_FIELD_GROUP_ID","LABEL_FOR_ADMINS","MANDATORY_FOR_ADMINS","EDITABLE_BY_ADMINS","LABEL_FOR_AGENTS","EDITABLE_BY_AGENTS","MANDATORY_FOR_AGENTS","VISIBLE_TO_AGENTS","AGENT_FIELDS_TYPE","DEFAULT_FIELD","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] AGENTS = {"ID","ACTIVE","ADDRESS","API_KEY_ENABLED","AUTO_ASSIGN_STATUS_CHANGED_AT","AUTO_ASSIGN_TICKETS","BACKGROUND_INFORMATION","CAN_SEE_ALL_TICKETS_FROM_ASSOCIATED_DEPARTMENTS","CREATED_AT","CUSTOM_FIELDS","DEPARTMENT_NAMES","EMAIL","EXTERNAL_ID","FIRST_NAME","HAS_LOGGED_IN","JOB_TITLE","AGENTS_LANGUAGE","LAST_ACTIVE_AT","LAST_LOGIN_AT","LAST_NAME","LOCATION_ID","LOCATION_NAME","MOBILE_PHONE_NUMBER","OCCASIONAL","REPORTING_MANAGER_ID","SCOREBOARD_LEVEL_ID","SCOREBOARD_POINTS","SIGNATURE","TIME_FORMAT","TIME_ZONE","UPDATED_AT","VIP_USER","WORK_PHONE_NUMBER","WORK_SCHEDULE_ID","OBSERVER_OF","MEMBER_OF_PENDING_APPROVAL","OBSERVER_OF_PENDING_APPROVAL","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] AGENTS_DEPARTMENTS = {"AGENT_ID","DEPARTMENT_ID","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] AGENTS_GROUPS = {"AGENT_ID","GROUP_ID","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] AGENTS_ROLES = {"AGENT_ID","ROLE_ID", "ASSIGNMENT_SCOPE", "GROUPS", "__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] AGENTS_WORKSPACES = {"AGENT_ID","WORKSPACE_ID", "__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] AGENTS_WORKLOAD_CONFIGS = {"AGENT_ID","LOAD_LIMIT", "MODULE_NAME", "__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] ANNOUNCEMENTS = {"ID","CREATED_AT","UPDATED_AT","TITLE","GROUPED_VISIBILITY_OPTIONS","VISIBLE_IN_PORTAL","ADDITIONAL_CONFIG","WORKSPACE_ID","CREATED_BY","VISIBLE_FROM","VISIBLE_TILL","BODY","BODY_HTML","VISIBILITY","ANNOUNCEMENTS_STATE","ANNOUNCEMENTS_GROUPS","DEPARTMENTS","AGENT_GROUPS","IS_READ","SEND_EMAIL","ADDITIONAL_EMAILS","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] APPLICATION_INSTALLATIONS = {"ID","CREATED_AT","UPDATED_AT","INSTALLATION_PATH","VERSION","APPLICATION_ID","INSTALLATION_MACHINE_ID","USER_ID","DEPARTMENT_ID","INSTALLATION_DATE","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] APPLICATION_LICENSES = {"ID","CONTRACT_ID","CREATED_TIME","UPDATED_TIME","APPLICATION_ID","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] APPLICATION_RELATIONSHIPS = {"ID","CREATED_AT","UPDATED_AT","APPLICATION_ID","RELATIONSHIP_TYPE_ID","PRIMARY_ID","PRIMARY_TYPE","SECONDARY_ID","SECONDARY_TYPE","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] APPLICATION_USERS = {"ID","CREATED_AT","UPDATED_AT","USER_ID","LICENSE_ID","ALLOCATED_DATE","FIRST_USED","LAST_USED","SOURCE","APPLICATION_ID","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] APPLICATIONS = {"ID","USER_COUNT","INSTALLATION_COUNT","CREATED_AT","UPDATED_AT","NAME","PUBLISHER_ID","DESCRIPTION","NOTES","APPLICATION_TYPE","STATUS","MANAGED_BY_ID","CATEGORY","SOURCE","WORKSPACE_ID","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] ASSET_TYPES = {"ID","NAME","PARENT_ASSET_TYPE_ID","DESCRIPTION","VISIBLE","CREATED_AT","UPDATED_AT","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] ASSETS_COMPONENTS = {"ID","CREATED_AT","UPDATED_AT","ASSETS_DISPLAY_ID","COMPONENT_TYPE","COMPONENT_DATA","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] ASSETS_REQUESTS = {"ID","CREATED_AT","UPDATED_AT","REQUEST_TYPE","REQUEST_ID","REQUEST_DETAILS","REQUEST_STATUS","ASSETS_DISPLAY_ID","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] ASSETS_CONTRACTS = {"ID","CONTRACT_ID","CONTRACT_TYPE","CONTRACT_NAME","CONTRACT_STATUS","ASSETS_DISPLAY_ID","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS", "__DLH_IS_ACTIVE"};
        public static final String[] ASSETS = {"ID","NAME","ASSET_TYPE_ID","ASSET_TAG","IMPACT","DESCRIPTION","END_OF_LIFE","DISCOVERY_ENABLED","USAGE_TYPE","CREATED_BY_SOURCE","CREATED_BY_USER","CREATED_AT","LAST_UPDATED_BY_SOURCE","LAST_UPDATED_BY_USER","UPDATED_AT","SOURCES","LOCATION_ID","DEPARTMENT_ID","AGENT_ID","USER_ID","GROUP_ID","ASSIGNED_ON","AUTHOR_TYPE","DISPLAY_ID","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] BUSINESS_HOURS = {"ID","CREATED_AT","UPDATED_AT","NAME","DESCRIPTION","IS_DEFAULT","TIME_ZONE","SERVICE_DESK_HOURS_MONDAY_BEGINNING_OF_WORKDAY","SERVICE_DESK_HOURS_MONDAY_END_OF_WORKDAY","SERVICE_DESK_HOURS_TUESDAY_BEGINNING_OF_WORKDAY","SERVICE_DESK_HOURS_TUESDAY_END_OF_WORKDAY","SERVICE_DESK_HOURS_WEDNESDAY_BEGINNING_OF_WORKDAY","SERVICE_DESK_HOURS_WEDNESDAY_END_OF_WORKDAY","SERVICE_DESK_HOURS_THURSDAY_BEGINNING_OF_WORKDAY","SERVICE_DESK_HOURS_THURSDAY_END_OF_WORKDAY","SERVICE_DESK_HOURS_FRIDAY_BEGINNING_OF_WORKDAY","SERVICE_DESK_HOURS_FRIDAY_END_OF_WORKDAY","LIST_OF_HOLIDAYS","WORKSPACE_ID","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] CANNED_RESPONSES = {"ID","TITLE","FOLDER_ID","CONTENT","CONTENT_HTML","CREATED_AT","UPDATED_AT","WORKSPACE_ID","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] CANNED_RESPONSE_FOLDERS = {"ID","NAME","CANNED_RESPONSE_FOLDERS_TYPE","RESPONSES_COUNT","CREATED_AT","UPDATED_AT","WORKSPACE_ID","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] CHANGES_FORM_FIELDS = {"ID","CREATED_AT","UPDATED_AT","NAME","LABEL","DESCRIPTION","FIELD_TYPE","CHANGES_FORM_FIELDS_REQUIRED","REQUIRED_FOR_CLOSURE","POSITION","DEFAULT_FIELD","CHOICES","NESTED_FIELDS","WORKSPACE_ID","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] CHANGES_NOTES = {"ID","CREATED_AT","UPDATED_AT","BODY","BODY_TEXT","USER_ID","NOTIFY_EMAILS","CHANGES_ID","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] CHANGES_TASKS = {"ID","PLANNED_START_DATE","PLANNED_END_DATE","PLANNED_EFFORT","AGENT_ID","STATUS","DUE_DATE","NOTIFY_BEFORE","TITLE","DESCRIPTION","CREATED_AT","UPDATED_AT","CLOSED_AT","GROUP_ID","WORKSPACE_ID","CHANGES_ID","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] CHANGES_TIME_ENTRIES = {"ID","CREATED_AT","UPDATED_AT","START_TIME","TIMER_RUNNING","BILLABLE","TIME_SPENT","EXECUTED_AT","TASK_ID","WORKSPACE_ID","NOTE","AGENT_ID","CUSTOM_FIELDS","CHANGES_ID","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] CHANGES = {"ID","AGENT_ID","GROUP_ID","PRIORITY","IMPACT","STATUS","RISK","CHANGE_TYPE","PLANNED_START_DATE","PLANNED_END_DATE","SUBJECT","DEPARTMENT_ID","CATEGORY","SUB_CATEGORY","ITEM_CATEGORY", "DESCRIPTION","DESCRIPTION_TEXT","PLANNED_EFFORT","CUSTOM_FIELDS","DUE_BY","REQUESTER_ID","APPROVAL_STATUS","CHANGE_WINDOW_ID","CREATED_AT","UPDATED_AT","WORKSPACE_ID","ATTACHMENTS","MAINTENANCE_WINDOW","BLACKOUT_WINDOW","ASSETS","IMPACTED_SERVICES","TASKS_DEPENDENCY_TYPE","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] CONTRACT_ATTACHMENTS = {"ID","NAME","CONTENT_TYPE","CONTRACT_ATTACHMENTS_SIZE","ATTACHMENT_URL","CANONICAL_URL","CREATED_AT","UPDATED_AT","CONTRACT_ID","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] CONTRACTS = {"ID","NAME","DESCRIPTION","VENDOR_ID","AUTO_RENEW","NOTIFY_EXPIRY","NOTIFY_BEFORE","APPROVER_ID","START_DATE","END_DATE","COST","STATUS","CONTRACT_NUMBER","CONTRACT_TYPE_ID","VISIBLE_TO_ID","NOTIFY_TO","CUSTOM_FIELDS","SOFTWARE_ID","LICENSE_TYPE","BILLING_CYCLE","LICENSE_KEY","FUTURE_CONTRACT_ID","HAS_ASSOCIATED_ASSETS","HAS_ATTACHMENTS","EXPIRY_NOTIFIED","REQUESTER_ID","DELEGATEE_ID","CREATED_AT","UPDATED_AT","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] CSAT_RESPONSE = {"ID","OVERALL_RATING","OVERALL_RATING_TEXT","PRIMARY_QUESTION","QUESTIONNAIRE_RESPONSES","CREATED_AT","UPDATED_AT","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] CUSTOM_OBJECTS = {"ID","TITLE","DESCRIPTION","UPDATED_AT","LAST_UPDATED_BY_EMAIL","LAST_UPDATED_BY_ID","LAST_UPDATED_BY_NAME","WORKSPACE_ID","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] DEPARTMENT_FIELDS = {"CREATED_AT","UPDATED_AT","NAME","LABEL","MANDATORY","IS_DEFAULT_FIELD","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] DEPARTMENTS = {"ID","NAME","DESCRIPTION","HEAD_NAME","PRIME_USER_ID","PRIME_USER_NAME","DOMAINS","CUSTOM_FIELDS","WORKSPACE_ID","CREATED_AT","UPDATED_AT","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] GROUPS = {"ID","NAME","DESCRIPTION","BUSINESS_HOURS_ID","ESCALATE_TO","UNASSIGNED_FOR","WORKSPACE_ID","OCS_SCHEDULE_ID","OBSERVERS","RESTRICTED","APPROVAL_REQUIRED","LEADERS","MEMBERS_PENDING_APPROVAL","LEADERS_PENDING_APPROVAL","OBSERVERS_PENDING_APPROVAL","AUTO_TICKET_ASSIGN","CREATED_AT","UPDATED_AT","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] LOCATIONS = {"ID","NAME","PARENT_LOCATION_ID","CONTACT_NAME","EMAIL","PHONE","ADDRESS_LINE1","ADDRESS_LINE2","ADDRESS_CITY","ADDRESS_STATE","ADDRESS_COUNTRY","ADDRESS_ZIPCODE","WORKSPACE_ID","CREATED_AT","UPDATED_AT","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] OBJECT_RECORDS = {"VERSION","OBJECT_RECORDS_DATA","OBJECT_ID","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] POST_INCIDENT_REPORT_TEMPLATES = {"ID","CREATED_AT","UPDATED_AT","TITLE","POST_INCIDENT_REPORT_TEMPLATES_STATE","UPDATED_BY","POST_INCIDENT_REPORT_TEMPLATES_PRIMARY","WORKSPACE_ID","RELATED_INCIDENT_ENABLED","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] PROBLEM_FIELDS = {"ID","CREATED_AT","UPDATED_AT","NAME","LABEL","DESCRIPTION","FIELD_TYPE","PROBLEM_FIELDS_REQUIRED","REQUIRED_FOR_CLOSURE","POSITION","DEFAULT_FIELD","CHOICES","NESTED_FIELDS","WORKSPACE_ID","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] PROBLEM_NOTES = {"ID","CREATED_AT","UPDATED_AT","BODY","BODY_TEXT","USER_ID","NOTIFY_EMAILS","PROBLEM_ID","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] PROBLEM_TASKS = {"ID","PLANNED_START_DATE","PLANNED_END_DATE","PLANNED_EFFORT","AGENT_ID","STATUS","DUE_DATE","NOTIFY_BEFORE","TITLE","DESCRIPTION","CREATED_AT","UPDATED_AT","CLOSED_AT","GROUP_ID","DELETED","PROBLEM_ID","WORKSPACE_ID","CUSTOM_FIELDS","STACK_RANK","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] PROBLEM_TIME_ENTRIES = {"ID","CREATED_AT","UPDATED_AT","START_TIME","TIMER_RUNNING","BILLABLE","TIME_SPENT","EXECUTED_AT","TASK_ID","WORKSPACE_ID","NOTE","PROBLEM_ID","AGENT_ID","CUSTOM_FIELDS","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] PROBLEMS = {"ID","AGENT_ID","REQUESTER_ID","PLANNED_START_DATE","PLANNED_END_DATE","PLANNED_EFFORT","DESCRIPTION","DESCRIPTION_TEXT","DUE_BY","SUBJECT","GROUP_ID","PRIORITY","IMPACT","STATUS","KNOWN_ERROR","DEPARTMENT_ID","CATEGORY","SUB_CATEGORY","ITEM_CATEGORY","ASSETS","CREATED_AT","UPDATED_AT","WORKSPACE_ID","ATTACHMENTS","TASK_DEPENDENCY_TYPE","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] PRODUCTS = {"ID","NAME","ASSET_TYPE_ID","MANUFACTURER","STATUS","MODE_OF_PROCUREMENT","DEPRECIATION_TYPE_ID","DESCRIPTION","DESCRIPTION_TEXT","CREATED_AT","UPDATED_AT","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] PROJECT_FIELDS = {"LABEL","NAME","PROJECT_FIELDS_TYPE","PROJECT_FIELDS_DEFAULT","CHOICES","MANDATORY","CREATED_AT","UPDATED_AT","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] PROJECT_SPRINTS = {"ID","CREATED_AT","UPDATED_AT","TITLE","PLANNED_START_DATE","PLANNED_END_DATE","GOAL","PROJECT_SPRINTS_STATE","PROJECT_ID","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] PROJECT_TASK_NOTES = {"ID","BODY","TASK_ID","USER_EMAIL_ID","ATTACHMENTS","CREATED_AT","UPDATED_AT","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] PROJECT_TASK_PRIORITIES = {"ID","CREATED_AT","UPDATED_AT","NAME","DESCRIPTION","PROJECT_ID","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] PROJECT_TASK_TYPE_FIELDS = {"PROJECT_TASK_TYPE_FIELDS_DEFAULT","CREATED_AT","UPDATED_AT","MANDATORY","LABEL","NAME","CHOICES","PROJECT_TASK_TYPE_FIELDS_TYPE","PROJECT_ID","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] PROJECT_TASKS = {"ID","TITLE","PROJECT_ID","DESCRIPTION","STATUS_ID","PRIORITY_ID","REPORTER_ID","CREATED_AT","UPDATED_AT","DISPLAY_KEY","PLANNED_START_DATE","TYPE_ID","ASSIGNEE_ID","PLANNED_END_DATE","PLANNED_EFFORT","PLANNED_DURATION","CUSTOM_FIELDS","VERSION_ID","PARENT_ID","STORY_POINTS","SPRINT_ID","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] PROJECT_TEMPLATES = {"ID","NAME","DESCRIPTION","TEMPLATE_TYPE","VISIBILITY","CREATED_AT","UPDATED_AT","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] PROJECT_VERSIONS = {"ID","CREATED_AT","UPDATED_AT","NAME","START_DATE","DUE_DATE","DESCRIPTION","STATUS_ID","OWNER_ID","PROJECT_ID","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] PROJECTS_MEMBERSHIPS = {"ID","PROJECT_ID","USER_ID","ACCESS_TYPE","MANAGE_SETTINGS","PROJECT_MANAGER","CREATED_AT","UPDATED_AT","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] PROJECTS_TASK_STATUES = {"ID","CREATED_AT","UPDATED_AT","NAME","DESCRIPTION","PROJECT_ID","CATEGORY_ID","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] PROJECTS_TASK_TYPES = {"ID","CREATED_AT","UPDATED_AT","NAME","DESCRIPTION","PROJECT_ID","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] PROJECTS = {"ID","NAME","PROJECTS_KEY","DESCRIPTION","STATUS_ID","PRIORITY_ID","SPRINT_DURATION","PROJECT_TYPE","START_DATE","END_DATE","ARCHIVED","VISIBILITY","MANAGER_ID","CREATED_AT","UPDATED_AT","CUSTOM_FIELDS","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] PURCHASE_ORDERS = {"ID","VENDOR_ID","NAME","PO_NUMBER","WORKSPACE_ID","TOTAL_COST","EXPECTED_DELIVERY_DATE","CREATED_AT","UPDATED_AT","CREATED_BY","STATUS","DEPARTMENT_ID","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] RELATIONSHIP_TYPES = {"ID","IS_DEFAULT","DESCRIPTION","CREATED_AT","UPDATED_AT","DOWNSTREAM_RELATION","UPSTREAM_RELATION","UPSTREAM_IMPACT","DOWNSTREAM_IMPACT","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] RELATIONSHIPS = {"ID","RELATIONSHIP_TYPE_ID","PRIMARY_ID","PRIMARY_TYPE","SECONDARY_ID","SECONDARY_TYPE","CREATED_AT","UPDATED_AT","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] RELEASE_FIELDS = {"ID","CREATED_AT","UPDATED_AT","NAME","LABEL","DESCRIPTION","FIELD_TYPE","RELEASE_FIELDS_REQUIRED","REQUIRED_FOR_CLOSURE","POSITION","DEFAULT_FIELD","CHOICES","NESTED_FIELDS","WORKSPACE_ID","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] RELEASES_NOTES = {"ID","CREATED_AT","UPDATED_AT","BODY","BODY_TEXT","USER_ID","RELEASE_ID","NOTIFY_EMAILS","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] RELEASES_TASKS = {"ID","PLANNED_START_DATE","PLANNED_END_DATE","PLANNED_EFFORT","AGENT_ID","STATUS","DUE_DATE","NOTIFY_BEFORE","TITLE","DESCRIPTION","CREATED_AT","UPDATED_AT","CLOSED_AT","RELEASE_ID","GROUP_ID","DELETED","WORKSPACE_ID","CUSTOM_FIELDS","STACK_RANK","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] RELEASES_TIME_ENTRIES = {"ID","CREATED_AT","UPDATED_AT","START_TIME","TIMER_RUNNING","BILLABLE","TIME_SPENT","EXECUTED_AT","TASK_ID","WORKSPACE_ID", "RELEASE_ID", "NOTE","AGENT_ID","CUSTOM_FIELDS","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] RELEASES = {"ID", "AGENT_ID", "DESCRIPTION", "DESCRIPTION_TEXT", "GROUP_ID", "PRIORITY", "STATUS", "RELEASE_TYPE", "SUBJECT", "PLANNED_START_DATE", "PLANNED_END_DATE", "DEPARTMENT_ID", "CATEGORY", "SUB_CATEGORY", "ITEM_CATEGORY", "WORK_START_DATE", "WORK_END_DATE", "CREATED_AT", "UPDATED_AT", "WORKSPACE_ID", "ASSETS", "ASSOCIATED_CHANGE_IDS", "CUSTOM_FIELDS", "PLANNING_EFFORT", "ATTACHMENTS", "__ROW_MD5", "__DLH_IS_DELETED", "__DLH_SYNC_TS", "__DLH_START_TS", "__DLH_FINISH_TS", "__DLH_IS_ACTIVE"};
        public static final String[] REQUESTER_FIELDS = {"ID","EDITABLE_IN_SIGNUP","NAME","LABEL","POSITION","USER_FIELD_GROUP_ID","REQUIRED_FOR_AGENTS","REQUESTER_FIELDS_TYPE","REQUESTER_FIELDS_DEFAULT","REQUESTERS_CAN_EDIT","LABEL_FOR_REQUESTERS","REQUIRED_FOR_REQUESTERS","DISPLAYED_FOR_REQUESTERS","CREATED_AT","UPDATED_AT","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] REQUESTER_GROUPS = {"ID","NAME","DESCRIPTION","REQUESTER_GROUPS_TYPE","WORKSPACE_ID","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] REQUESTERS = {"ID", "IS_AGENT", "FIRST_NAME", "LAST_NAME", "JOB_TITLE", "PRIMARY_EMAIL", "SECONDARY_EMAILS", "WORK_PHONE_NUMBER", "MOBILE_PHONE_NUMBER", "DEPARTMENT_IDS", "DEPARTMENT_NAMES", "CAN_SEE_ALL_TICKETS_FROM_ASSOCIATED_DEPARTMENTS", "CAN_SEE_ALL_CHANGES_FROM_ASSOCIATED_DEPARTMENTS", "CREATED_AT", "REPORTING_MANAGER_ID", "ADDRESS", "TIME_ZONE", "TIME_FORMAT", "REQUESTERS_LANGUAGE", "LOCATION_ID", "LOCATION_NAME", "VIP_USER", "CUSTOM_FIELDS", "ACTIVE", "HAS_LOGGED_IN", "__ROW_MD5", "__DLH_IS_DELETED", "__DLH_SYNC_TS", "__DLH_START_TS", "__DLH_FINISH_TS", "__DLH_IS_ACTIVE"};
        public static final String[] ROLES = {"ID","NAME","DESCRIPTION","ROLES_DEFAULT","ROLES_PRIVILEGES","ROLE_TYPE","CREATED_AT","UPDATED_AT","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] SERVICE_CATALOG_CATEGORIES = {"ID","DESCRIPTION","CREATED_AT","UPDATED_AT","NAME","POSITION","WORKSPACE_ID","PARENT_ID","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] SERVICE_CATALOG_ITEMS = {"ID","CREATED_AT","UPDATED_AT","NAME","DELIVERY_TIME","DISPLAY_ID","CATEGORY_ID","PRODUCT_ID","QUANTITY","DELETED","ICON_NAME","GROUP_VISIBILITY","ITEM_TYPE","CI_TYPE_ID","COST_VISIBILITY","DELIVERY_TIME_VISIBILITY","CONFIGS","BOTIFIED","VISIBILITY","ALLOW_ATTACHMENTS","ALLOW_QUANTITY","IS_BUNDLE","CREATE_CHILD","WORKSPACE_ID","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] SLA_POLICIES = {"ID","WORKSPACE_ID","NAME","POSITION","IS_DEFAULT","ACTIVE","DELETED","PARENT_ENTITY","DESCRIPTION","SLA_TARGETS","APPLICABLE_TO","ESCALATION","CREATED_AT","UPDATED_AT","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] SOLUTION_ARTICLES = {"ID","DESCRIPTION","CREATED_AT","UPDATED_AT","TITLE","STATUS","APPROVAL_STATUS","POSITION","FOLDER_ID","CATEGORY_ID","THUMBS_UP","THUMBS_DOWN","MODIFIED_BY","MODIFIED_AT","INSERTED_INTO_TICKETS","URL","ARTICLE_TYPE","AGENT_ID","VIEWS","DESCRIPTION_TEXT"};
        public static final String[] SOLUTION_CATEGORIES = {"ID","CREATED_AT","UPDATED_AT","NAME","DESCRIPTION","DEFAULT_CATEGORY","POSITION","TRANSLATIONS","UNTRANSLATED_NAME","WORKSPACE_ID","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] SOLUTION_FOLDERS = {"ID","NAME","DESCRIPTION","CREATED_AT","UPDATED_AT","CATEGORY_ID","POSITION","VISIBILITY","APPROVAL_SETTINGS","DEFAULT_FOLDER","MANAGE_BY_GROUP_IDS","WORKSPACE_ID","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] TICKET_ACTIVITIES = {"ACTOR_ID","ACTOR_NAME","ACTOR_IS_AGENT", "TICKET_ID", "CONTENT","SUB_CONTENTS","CREATED_AT","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] TICKET_CONVERSATIONS = {"ID","BODY","BODY_TEXT","INCOMING","TICKET_CONVERSATIONS_PRIVATE","CREATED_AT","UPDATED_AT","USER_ID","SUPPORT_EMAIL","SOURCE","TICKET_ID","TO_EMAILS","FROM_EMAIL","CC_EMAILS","BCC_EMAILS","ATTACHMENTS","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] TICKET_FIELDS = {"ID","LABEL","DESCRIPTION","FIELD_TYPE","CREATED_AT","UPDATED_AT","POSITION","REQUIRED_FOR_CLOSURE","NAME","DEFAULT_FIELD","REQUIRED_FOR_AGENTS","CUSTOMERS_CAN_EDIT","LABEL_FOR_CUSTOMERS","REQUIRED_FOR_CUSTOMERS","DISPLAYED_TO_CUSTOMERS","BELONGS_TO_SECTION","CHOICES","NESTED_FIELDS","SECTIONS","WORKSPACE_ID","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] TICKET_TASKS = {"ID","PLANNED_START_DATE","PLANNED_END_DATE","PLANNED_EFFORT","AGENT_ID","STATUS","DUE_DATE","NOTIFY_BEFORE","TITLE","DESCRIPTION","CREATED_AT","UPDATED_AT","CLOSED_AT","GROUP_ID","TICKET_ID","DELETED","WORKSPACE_ID","CUSTOM_FIELDS","STACK_RANK","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] TICKET_TIME_ENTRIES = {"ID","CREATED_AT","UPDATED_AT","START_TIME","TIMER_RUNNING","BILLABLE","TIME_SPENT","EXECUTED_AT","TASK_ID","WORKSPACE_ID","NOTE","AGENT_ID", "TICKET_ID","CUSTOM_FIELDS","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] TICKETS = {"ID","CC_EMAILS","FWD_EMAILS","REPLY_CC_EMAILS","FR_ESCALATED","SPAM","EMAIL_CONFIG_ID","GROUP_ID","PRIORITY","REQUESTER_ID","REQUESTED_FOR_ID","RESPONDER_ID","SOURCE","STATUS","SUBJECT","TO_EMAILS","DEPARTMENT_ID","TICKETS_TYPE","DUE_BY","FR_DUE_BY","IS_ESCALATED","DESCRIPTION","DESCRIPTION_TEXT","CATEGORY","SUB_CATEGORY","ITEM_CATEGORY","CUSTOM_FIELDS","WORKSPACE_ID","CREATED_AT","UPDATED_AT","DELETED","TASK_DEPENDENCY_TYPE","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] VENDORS = {"ID","NAME","DESCRIPTION","CONTACT_NAME", "EMAIL", "PHONE", "MOBILE", "CUSTOM_FIELDS", "ADDRESS_LINE1","ADDRESS_CITY","ADDRESS_STATE","ADDRESS_COUNTRY","ADDRESS_ZIPCODE","CREATED_AT","UPDATED_AT","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};
        public static final String[] WORKSPACES = {"ID","CREATED_AT","DESCRIPTION","NAME","WORKSPACES_PRIMARY","RESTRICTED","WORKSPACES_STATE","TEMPLATE_NAME","WORKSPACES_TYPE","UPDATED_AT","__ROW_MD5","__DLH_IS_DELETED","__DLH_SYNC_TS","__DLH_START_TS","__DLH_FINISH_TS","__DLH_IS_ACTIVE"};

        private FreshServiceHeaders() {}
    }

    public static List<String> excludedEntities = List.of();

    public static final Map<String, String[]> HEADERS_BY_ENTITY = Map.ofEntries(
        Map.entry(FreshServiceEntityNames.AGENT_FIELDS, FreshServiceHeaders.AGENT_FIELDS),
        Map.entry(FreshServiceEntityNames.AGENTS, FreshServiceHeaders.AGENTS),
        Map.entry(FreshServiceEntityNames.ANNOUNCEMENTS, FreshServiceHeaders.ANNOUNCEMENTS),
        Map.entry(FreshServiceEntityNames.APPLICATION_INSTALLATIONS, FreshServiceHeaders.APPLICATION_INSTALLATIONS),
        Map.entry(FreshServiceEntityNames.APPLICATION_LICENSES, FreshServiceHeaders.APPLICATION_LICENSES),
        Map.entry(FreshServiceEntityNames.APPLICATION_RELATIONSHIPS, FreshServiceHeaders.APPLICATION_RELATIONSHIPS),
        Map.entry(FreshServiceEntityNames.APPLICATION_USERS, FreshServiceHeaders.APPLICATION_USERS),
        Map.entry(FreshServiceEntityNames.APPLICATIONS, FreshServiceHeaders.APPLICATIONS),
            Map.entry(FreshServiceEntityNames.ASSET_TYPES, FreshServiceHeaders.ASSET_TYPES),
            Map.entry(FreshServiceEntityNames.ASSETS_COMPONENTS, FreshServiceHeaders.ASSETS_COMPONENTS),
            Map.entry(FreshServiceEntityNames.ASSETS_REQUESTS, FreshServiceHeaders.ASSETS_REQUESTS),
            Map.entry(FreshServiceEntityNames.ASSETS_CONTRACTS, FreshServiceHeaders.ASSETS_CONTRACTS),
            Map.entry(FreshServiceEntityNames.ASSETS, FreshServiceHeaders.ASSETS),
            Map.entry(FreshServiceEntityNames.BUSINESS_HOURS, FreshServiceHeaders.BUSINESS_HOURS),
            Map.entry(FreshServiceEntityNames.CANNED_RESPONSES, FreshServiceHeaders.CANNED_RESPONSES),
            Map.entry(FreshServiceEntityNames.CANNED_RESPONSE_FOLDERS, FreshServiceHeaders.CANNED_RESPONSE_FOLDERS),
            Map.entry(FreshServiceEntityNames.CHANGES_FORM_FIELDS, FreshServiceHeaders.CHANGES_FORM_FIELDS),
            Map.entry(FreshServiceEntityNames.CHANGES_NOTES, FreshServiceHeaders.CHANGES_NOTES),
            Map.entry(FreshServiceEntityNames.CHANGES_TASKS, FreshServiceHeaders.CHANGES_TASKS),
            Map.entry(FreshServiceEntityNames.CHANGES_TIME_ENTRIES, FreshServiceHeaders.CHANGES_TIME_ENTRIES),
            Map.entry(FreshServiceEntityNames.CHANGES, FreshServiceHeaders.CHANGES),
            Map.entry(FreshServiceEntityNames.CONTRACT_ATTACHMENTS, FreshServiceHeaders.CONTRACT_ATTACHMENTS),
            Map.entry(FreshServiceEntityNames.CONTRACTS, FreshServiceHeaders.CONTRACTS),
            Map.entry(FreshServiceEntityNames.CSAT_RESPONSE, FreshServiceHeaders.CSAT_RESPONSE),
            Map.entry(FreshServiceEntityNames.CUSTOM_OBJECTS, FreshServiceHeaders.CUSTOM_OBJECTS),
            Map.entry(FreshServiceEntityNames.DEPARTMENT_FIELDS, FreshServiceHeaders.DEPARTMENT_FIELDS),
            Map.entry(FreshServiceEntityNames.DEPARTMENTS, FreshServiceHeaders.DEPARTMENTS),
            Map.entry(FreshServiceEntityNames.GROUPS, FreshServiceHeaders.GROUPS),
            Map.entry(FreshServiceEntityNames.LOCATIONS, FreshServiceHeaders.LOCATIONS),
            Map.entry(FreshServiceEntityNames.OBJECT_RECORDS, FreshServiceHeaders.OBJECT_RECORDS),
            Map.entry(FreshServiceEntityNames.POST_INCIDENT_REPORT_TEMPLATES, FreshServiceHeaders.POST_INCIDENT_REPORT_TEMPLATES),
            Map.entry(FreshServiceEntityNames.PROBLEM_FIELDS, FreshServiceHeaders.PROBLEM_FIELDS),
            Map.entry(FreshServiceEntityNames.PROBLEM_NOTES, FreshServiceHeaders.PROBLEM_NOTES),
            Map.entry(FreshServiceEntityNames.PROBLEM_TASKS, FreshServiceHeaders.PROBLEM_TASKS),
            Map.entry(FreshServiceEntityNames.PROBLEM_TIME_ENTRIES, FreshServiceHeaders.PROBLEM_TIME_ENTRIES),
            Map.entry(FreshServiceEntityNames.PROBLEMS, FreshServiceHeaders.PROBLEMS),
            Map.entry(FreshServiceEntityNames.PRODUCTS, FreshServiceHeaders.PRODUCTS),
            Map.entry(FreshServiceEntityNames.PROJECT_FIELDS, FreshServiceHeaders.PROJECT_FIELDS),
            Map.entry(FreshServiceEntityNames.PROJECT_SPRINTS, FreshServiceHeaders.PROJECT_SPRINTS),
            Map.entry(FreshServiceEntityNames.PROJECT_TASK_NOTES, FreshServiceHeaders.PROJECT_TASK_NOTES),
            Map.entry(FreshServiceEntityNames.PROJECT_TASK_PRIORITIES, FreshServiceHeaders.PROJECT_TASK_PRIORITIES),
            Map.entry(FreshServiceEntityNames.PROJECT_TASK_TYPE_FIELDS, FreshServiceHeaders.PROJECT_TASK_TYPE_FIELDS),
            Map.entry(FreshServiceEntityNames.PROJECT_TASKS, FreshServiceHeaders.PROJECT_TASKS),
            Map.entry(FreshServiceEntityNames.PROJECT_TEMPLATES, FreshServiceHeaders.PROJECT_TEMPLATES),
            Map.entry(FreshServiceEntityNames.PROJECT_VERSIONS, FreshServiceHeaders.PROJECT_VERSIONS),
            Map.entry(FreshServiceEntityNames.PROJECTS_MEMBERSHIPS, FreshServiceHeaders.PROJECTS_MEMBERSHIPS),
            Map.entry(FreshServiceEntityNames.PROJECTS_TASK_STATUES, FreshServiceHeaders.PROJECTS_TASK_STATUES),
            Map.entry(FreshServiceEntityNames.PROJECTS_TASK_TYPES, FreshServiceHeaders.PROJECTS_TASK_TYPES),
            Map.entry(FreshServiceEntityNames.PROJECTS, FreshServiceHeaders.PROJECTS),
            Map.entry(FreshServiceEntityNames.PURCHASE_ORDERS, FreshServiceHeaders.PURCHASE_ORDERS),
            Map.entry(FreshServiceEntityNames.RELATIONSHIP_TYPES, FreshServiceHeaders.RELATIONSHIP_TYPES),
            Map.entry(FreshServiceEntityNames.RELATIONSHIPS, FreshServiceHeaders.RELATIONSHIPS),
            Map.entry(FreshServiceEntityNames.RELEASE_FIELDS, FreshServiceHeaders.RELEASE_FIELDS),
            Map.entry(FreshServiceEntityNames.RELEASES_NOTES, FreshServiceHeaders.RELEASES_NOTES),
            Map.entry(FreshServiceEntityNames.RELEASES_TASKS, FreshServiceHeaders.RELEASES_TASKS),
            Map.entry(FreshServiceEntityNames.RELEASES_TIME_ENTRIES, FreshServiceHeaders.RELEASES_TIME_ENTRIES),
            Map.entry(FreshServiceEntityNames.RELEASES, FreshServiceHeaders.RELEASES),
            Map.entry(FreshServiceEntityNames.REQUESTER_FIELDS, FreshServiceHeaders.REQUESTER_FIELDS),
            Map.entry(FreshServiceEntityNames.REQUESTER_GROUPS, FreshServiceHeaders.REQUESTER_GROUPS),
            Map.entry(FreshServiceEntityNames.REQUESTERS, FreshServiceHeaders.REQUESTERS),
            Map.entry(FreshServiceEntityNames.ROLES, FreshServiceHeaders.ROLES),
            Map.entry(FreshServiceEntityNames.SERVICE_CATALOG_CATEGORIES, FreshServiceHeaders.SERVICE_CATALOG_CATEGORIES),
            Map.entry(FreshServiceEntityNames.SERVICE_CATALOG_ITEMS, FreshServiceHeaders.SERVICE_CATALOG_ITEMS),
            Map.entry(FreshServiceEntityNames.SLA_POLICIES, FreshServiceHeaders.SLA_POLICIES),
            Map.entry(FreshServiceEntityNames.SOLUTION_CATEGORIES, FreshServiceHeaders.SOLUTION_CATEGORIES),
            Map.entry(FreshServiceEntityNames.TICKET_ACTIVITIES, FreshServiceHeaders.TICKET_ACTIVITIES),
            Map.entry(FreshServiceEntityNames.TICKET_CONVERSATIONS, FreshServiceHeaders.TICKET_CONVERSATIONS),
            Map.entry(FreshServiceEntityNames.TICKET_FIELDS, FreshServiceHeaders.TICKET_FIELDS),
            Map.entry(FreshServiceEntityNames.TICKET_TASKS, FreshServiceHeaders.TICKET_TASKS),
            Map.entry(FreshServiceEntityNames.TICKET_TIME_ENTRIES, FreshServiceHeaders.TICKET_TIME_ENTRIES),
            Map.entry(FreshServiceEntityNames.TICKETS, FreshServiceHeaders.TICKETS),
            Map.entry(FreshServiceEntityNames.VENDORS, FreshServiceHeaders.VENDORS),
            Map.entry(FreshServiceEntityNames.WORKSPACES, FreshServiceHeaders.WORKSPACES)
    );

    /**
     * Entities that support delta sync with updated_since parameter.
     * These entities can be incrementally synced based on the last sync timestamp.
     */
    public static final Map<String, String[]> DELTA_HEADERS_BY_ENTITY = Map.ofEntries(
            Map.entry(FreshServiceEntityNames.TICKETS, FreshServiceHeaders.TICKETS),
            Map.entry(FreshServiceEntityNames.PROBLEMS, FreshServiceHeaders.PROBLEMS),
            Map.entry(FreshServiceEntityNames.CHANGES, FreshServiceHeaders.CHANGES),
            Map.entry(FreshServiceEntityNames.RELEASES, FreshServiceHeaders.RELEASES)
    );

    /**
     * Entities that do NOT support delta sync and require full refresh.
     * These are typically configuration/reference entities that don't change frequently.
     */
    public static final Map<String, String[]> NON_DELTA_HEADERS_BY_ENTITY = Map.ofEntries(
            Map.entry(FreshServiceEntityNames.ASSETS, FreshServiceHeaders.ASSETS),
            Map.entry(FreshServiceEntityNames.REQUESTERS, FreshServiceHeaders.REQUESTERS),
            Map.entry(FreshServiceEntityNames.AGENTS, FreshServiceHeaders.AGENTS),
            Map.entry(FreshServiceEntityNames.AGENT_FIELDS, FreshServiceHeaders.AGENT_FIELDS),
            Map.entry(FreshServiceEntityNames.ANNOUNCEMENTS, FreshServiceHeaders.ANNOUNCEMENTS),
            Map.entry(FreshServiceEntityNames.APPLICATION_INSTALLATIONS, FreshServiceHeaders.APPLICATION_INSTALLATIONS),
            Map.entry(FreshServiceEntityNames.APPLICATION_LICENSES, FreshServiceHeaders.APPLICATION_LICENSES),
            Map.entry(FreshServiceEntityNames.APPLICATION_RELATIONSHIPS, FreshServiceHeaders.APPLICATION_RELATIONSHIPS),
            Map.entry(FreshServiceEntityNames.APPLICATION_USERS, FreshServiceHeaders.APPLICATION_USERS),
            Map.entry(FreshServiceEntityNames.APPLICATIONS, FreshServiceHeaders.APPLICATIONS),
            Map.entry(FreshServiceEntityNames.ASSET_TYPES, FreshServiceHeaders.ASSET_TYPES),
            Map.entry(FreshServiceEntityNames.BUSINESS_HOURS, FreshServiceHeaders.BUSINESS_HOURS),
            Map.entry(FreshServiceEntityNames.CANNED_RESPONSES, FreshServiceHeaders.CANNED_RESPONSES),
            Map.entry(FreshServiceEntityNames.CANNED_RESPONSE_FOLDERS, FreshServiceHeaders.CANNED_RESPONSE_FOLDERS),
            Map.entry(FreshServiceEntityNames.CHANGES_FORM_FIELDS, FreshServiceHeaders.CHANGES_FORM_FIELDS),
            Map.entry(FreshServiceEntityNames.CONTRACT_ATTACHMENTS, FreshServiceHeaders.CONTRACT_ATTACHMENTS),
            Map.entry(FreshServiceEntityNames.CONTRACTS, FreshServiceHeaders.CONTRACTS),
            Map.entry(FreshServiceEntityNames.CSAT_RESPONSE, FreshServiceHeaders.CSAT_RESPONSE),
            Map.entry(FreshServiceEntityNames.CUSTOM_OBJECTS, FreshServiceHeaders.CUSTOM_OBJECTS),
            Map.entry(FreshServiceEntityNames.DEPARTMENT_FIELDS, FreshServiceHeaders.DEPARTMENT_FIELDS),
            Map.entry(FreshServiceEntityNames.DEPARTMENTS, FreshServiceHeaders.DEPARTMENTS),
            Map.entry(FreshServiceEntityNames.GROUPS, FreshServiceHeaders.GROUPS),
            Map.entry(FreshServiceEntityNames.LOCATIONS, FreshServiceHeaders.LOCATIONS),
            Map.entry(FreshServiceEntityNames.OBJECT_RECORDS, FreshServiceHeaders.OBJECT_RECORDS),
            Map.entry(FreshServiceEntityNames.POST_INCIDENT_REPORT_TEMPLATES, FreshServiceHeaders.POST_INCIDENT_REPORT_TEMPLATES),
            Map.entry(FreshServiceEntityNames.PROBLEM_FIELDS, FreshServiceHeaders.PROBLEM_FIELDS),
            Map.entry(FreshServiceEntityNames.PRODUCTS, FreshServiceHeaders.PRODUCTS),
            Map.entry(FreshServiceEntityNames.PROJECT_FIELDS, FreshServiceHeaders.PROJECT_FIELDS),
            Map.entry(FreshServiceEntityNames.PROJECT_SPRINTS, FreshServiceHeaders.PROJECT_SPRINTS),
            Map.entry(FreshServiceEntityNames.PROJECT_TASK_NOTES, FreshServiceHeaders.PROJECT_TASK_NOTES),
            Map.entry(FreshServiceEntityNames.PROJECT_TASK_PRIORITIES, FreshServiceHeaders.PROJECT_TASK_PRIORITIES),
            Map.entry(FreshServiceEntityNames.PROJECT_TASK_TYPE_FIELDS, FreshServiceHeaders.PROJECT_TASK_TYPE_FIELDS),
            Map.entry(FreshServiceEntityNames.PROJECT_TASKS, FreshServiceHeaders.PROJECT_TASKS),
            Map.entry(FreshServiceEntityNames.PROJECT_TEMPLATES, FreshServiceHeaders.PROJECT_TEMPLATES),
            Map.entry(FreshServiceEntityNames.PROJECT_VERSIONS, FreshServiceHeaders.PROJECT_VERSIONS),
            Map.entry(FreshServiceEntityNames.PROJECTS_MEMBERSHIPS, FreshServiceHeaders.PROJECTS_MEMBERSHIPS),
            Map.entry(FreshServiceEntityNames.PROJECTS_TASK_STATUES, FreshServiceHeaders.PROJECTS_TASK_STATUES),
            Map.entry(FreshServiceEntityNames.PROJECTS_TASK_TYPES, FreshServiceHeaders.PROJECTS_TASK_TYPES),
            Map.entry(FreshServiceEntityNames.PROJECTS, FreshServiceHeaders.PROJECTS),
            Map.entry(FreshServiceEntityNames.PURCHASE_ORDERS, FreshServiceHeaders.PURCHASE_ORDERS),
            Map.entry(FreshServiceEntityNames.RELATIONSHIP_TYPES, FreshServiceHeaders.RELATIONSHIP_TYPES),
            Map.entry(FreshServiceEntityNames.RELATIONSHIPS, FreshServiceHeaders.RELATIONSHIPS),
            Map.entry(FreshServiceEntityNames.RELEASE_FIELDS, FreshServiceHeaders.RELEASE_FIELDS),
            Map.entry(FreshServiceEntityNames.REQUESTER_FIELDS, FreshServiceHeaders.REQUESTER_FIELDS),
            Map.entry(FreshServiceEntityNames.REQUESTER_GROUPS, FreshServiceHeaders.REQUESTER_GROUPS),
            Map.entry(FreshServiceEntityNames.ROLES, FreshServiceHeaders.ROLES),
            Map.entry(FreshServiceEntityNames.SERVICE_CATALOG_CATEGORIES, FreshServiceHeaders.SERVICE_CATALOG_CATEGORIES),
            Map.entry(FreshServiceEntityNames.SERVICE_CATALOG_ITEMS, FreshServiceHeaders.SERVICE_CATALOG_ITEMS),
            Map.entry(FreshServiceEntityNames.SLA_POLICIES, FreshServiceHeaders.SLA_POLICIES),
            Map.entry(FreshServiceEntityNames.SOLUTION_CATEGORIES, FreshServiceHeaders.SOLUTION_CATEGORIES),
            Map.entry(FreshServiceEntityNames.TICKET_FIELDS, FreshServiceHeaders.TICKET_FIELDS),
            Map.entry(FreshServiceEntityNames.VENDORS, FreshServiceHeaders.VENDORS),
            Map.entry(FreshServiceEntityNames.WORKSPACES, FreshServiceHeaders.WORKSPACES)
    );

    /**
     * Common response wrapper keys used by FreshServices API.
     * The API typically wraps data in these keys.
     */
    public static final String[] COMMON_RESPONSE_KEYS = {
        "data",
        "items",
        "results",
        "records"
    };

    /**
     * Maps entity names to their expected response wrapper keys.
     * This allows entity-specific response key configurations.
     *
     * Format: entity_name -> response_wrapper_key
     * Example: "CONTRACTS" -> "contracts"
     */
    public static final Map<String, String> ENTITY_RESPONSE_KEY_MAP = Map.ofEntries(
        Map.entry(FreshServiceEntityNames.AGENTS, "agents"),
        Map.entry(FreshServiceEntityNames.ANNOUNCEMENTS, "announcements"),
        Map.entry(FreshServiceEntityNames.APPLICATIONS, "applications"),
        Map.entry(FreshServiceEntityNames.APPLICATION_INSTALLATIONS, "installations"),
        Map.entry(FreshServiceEntityNames.APPLICATION_USERS, "application_users"),
        Map.entry(FreshServiceEntityNames.APPLICATION_RELATIONSHIPS, "relationships"),
        Map.entry(FreshServiceEntityNames.APPLICATION_LICENSES, "licenses"),
        Map.entry(FreshServiceEntityNames.ASSETS, "assets"),
        Map.entry(FreshServiceEntityNames.ASSETS_COMPONENTS, "components"),
        Map.entry(FreshServiceEntityNames.ASSETS_CONTRACTS, "contracts"),
        Map.entry(FreshServiceEntityNames.ASSETS_REQUESTS, "requests"),
        Map.entry(FreshServiceEntityNames.CHANGES_FORM_FIELDS, "change_fields"),
        Map.entry(FreshServiceEntityNames.RELEASE_FIELDS, "release_fields"),
        Map.entry(FreshServiceEntityNames.AGENT_FIELDS, "agent_fields"),
        Map.entry(FreshServiceEntityNames.BUSINESS_HOURS, "business_hours"),
        Map.entry(FreshServiceEntityNames.CANNED_RESPONSES, "canned_responses"),
        Map.entry(FreshServiceEntityNames.CHANGES, "changes"),
        Map.entry(FreshServiceEntityNames.CHANGES_NOTES, "notes"),
        Map.entry(FreshServiceEntityNames.CHANGES_TASKS, "tasks"),
        Map.entry(FreshServiceEntityNames.CHANGES_TIME_ENTRIES, "time_entries"),
        Map.entry(FreshServiceEntityNames.CONTRACTS, "contracts"),
        Map.entry(FreshServiceEntityNames.CONTRACT_ATTACHMENTS, "attachments"),
        Map.entry(FreshServiceEntityNames.CSAT_RESPONSE, "csat_response"),
        Map.entry(FreshServiceEntityNames.CUSTOM_OBJECTS, "custom_objects"),
        Map.entry(FreshServiceEntityNames.DEPARTMENTS, "departments"),
        Map.entry(FreshServiceEntityNames.DEPARTMENT_FIELDS, "department_fields"),
        Map.entry(FreshServiceEntityNames.GROUPS, "groups"),
        Map.entry(FreshServiceEntityNames.LOCATIONS, "locations"),
        Map.entry(FreshServiceEntityNames.PROBLEMS, "problems"),
        Map.entry(FreshServiceEntityNames.PROBLEM_NOTES, "notes"),
        Map.entry(FreshServiceEntityNames.PROBLEM_TASKS, "tasks"),
        Map.entry(FreshServiceEntityNames.PROBLEM_TIME_ENTRIES, "time_entries"),
        Map.entry(FreshServiceEntityNames.PRODUCTS, "products"),
        Map.entry(FreshServiceEntityNames.PROJECTS, "projects"),
        Map.entry(FreshServiceEntityNames.PROJECT_FIELDS, "project_fields"),
        Map.entry(FreshServiceEntityNames.PROJECT_SPRINTS, "sprints"),
        Map.entry(FreshServiceEntityNames.PROJECT_TASKS, "tasks"),
        Map.entry(FreshServiceEntityNames.PROJECT_TASK_PRIORITIES, "task_priorities"),
        Map.entry(FreshServiceEntityNames.PROJECT_TEMPLATES, "project_templates"),
        Map.entry(FreshServiceEntityNames.PROJECT_VERSIONS, "versions"),
        Map.entry(FreshServiceEntityNames.PROJECTS_MEMBERSHIPS, "memberships"),
        Map.entry(FreshServiceEntityNames.PROJECTS_TASK_STATUES, "task_statuses"),
        Map.entry(FreshServiceEntityNames.PROJECTS_TASK_TYPES, "task_types"),
        Map.entry(FreshServiceEntityNames.RELEASES, "releases"),
        Map.entry(FreshServiceEntityNames.RELEASES_NOTES, "notes"),
        Map.entry(FreshServiceEntityNames.RELEASES_TASKS, "tasks"),
        Map.entry(FreshServiceEntityNames.RELEASES_TIME_ENTRIES, "time_entries"),
        Map.entry(FreshServiceEntityNames.RELATIONSHIP_TYPES, "relationship_types"),
        Map.entry(FreshServiceEntityNames.RELATIONSHIPS, "relationships"),
        Map.entry(FreshServiceEntityNames.REQUESTERS, "requesters"),
        Map.entry(FreshServiceEntityNames.REQUESTER_FIELDS, "requester_fields"),
        Map.entry(FreshServiceEntityNames.SERVICE_CATALOG_CATEGORIES, "service_categories"),
        Map.entry(FreshServiceEntityNames.SERVICE_CATALOG_ITEMS, "service_items"),
        Map.entry(FreshServiceEntityNames.SLA_POLICIES, "sla_policies"),
        Map.entry(FreshServiceEntityNames.SOLUTION_CATEGORIES, "categories"),
        Map.entry(FreshServiceEntityNames.ROLES, "roles"),
        Map.entry(FreshServiceEntityNames.TICKETS, "tickets"),
        Map.entry(FreshServiceEntityNames.TICKET_ACTIVITIES, "activities"),
        Map.entry(FreshServiceEntityNames.TICKET_CONVERSATIONS, "conversations"),
        Map.entry(FreshServiceEntityNames.TICKET_FIELDS, "ticket_fields"),
        Map.entry(FreshServiceEntityNames.TICKET_TASKS, "tasks"),
        Map.entry(FreshServiceEntityNames.TICKET_TIME_ENTRIES, "time_entries"),
        Map.entry(FreshServiceEntityNames.OBJECT_RECORDS, "records"),
        Map.entry(FreshServiceEntityNames.POST_INCIDENT_REPORT_TEMPLATES, "post_incident_report_templates"),
        Map.entry(FreshServiceEntityNames.VENDORS, "vendors"),
        Map.entry(FreshServiceEntityNames.WORKSPACES, "workspaces")
        // Add more mappings as needed
    );

    /**
     * Gets possible response wrapper keys for a given entity.
     * Returns entity-specific key if configured, otherwise returns common keys.
     *
     * @param entityName The entity name
     * @return Array of possible response wrapper keys to try
     */
    public static String[] getPossibleResponseKeys(String entityName) {
        List<String> keys = new ArrayList<>();

        // Add entity-specific key if configured
        if (ENTITY_RESPONSE_KEY_MAP.containsKey(entityName)) {
            keys.add(ENTITY_RESPONSE_KEY_MAP.get(entityName));
        }

        // Add normalized variations of entity name
        if (entityName != null) {
            keys.add(entityName.toLowerCase());
            keys.add(entityName.toLowerCase().replace("-", "_"));
            keys.add(entityName.toLowerCase().replace("/", "_"));
            keys.add(entityName.toUpperCase());
            keys.add(entityName); // Original case
        }

        // Add common response keys
        for (String commonKey : COMMON_RESPONSE_KEYS) {
            if (!keys.contains(commonKey)) {
                keys.add(commonKey);
            }
        }

        return keys.toArray(new String[0]);
    }

    /**
     * Gets the expected response wrapper key for an entity.
     * Returns null if not specifically configured.
     */
    public static String getEntityResponseKey(String entityName) {
        return ENTITY_RESPONSE_KEY_MAP.get(entityName);
    }

    public static String getUriPath(String entityName){
        return API_BASE_PATH + entityName.toLowerCase();
    }

    public static final Map<String, List<String>> ENTITY_DEPENDENCY_MAP = Map.ofEntries(
            Map.entry(FreshServiceEntityNames.APPLICATIONS, List.of(FreshServiceEntityNames.APPLICATION_INSTALLATIONS,
                    FreshServiceEntityNames.APPLICATION_LICENSES, FreshServiceEntityNames.APPLICATION_RELATIONSHIPS,
                    FreshServiceEntityNames.APPLICATION_USERS)),
            Map.entry(FreshServiceEntityNames.ASSETS, List.of(FreshServiceEntityNames.ASSETS_COMPONENTS, FreshServiceEntityNames.ASSETS_REQUESTS,
                    FreshServiceEntityNames.ASSETS_CONTRACTS)),
            Map.entry(FreshServiceEntityNames.CHANGES, List.of(FreshServiceEntityNames.CHANGES_NOTES,
                    FreshServiceEntityNames.CHANGES_TASKS, FreshServiceEntityNames.CHANGES_TIME_ENTRIES)),
            Map.entry(FreshServiceEntityNames.CONTRACTS, List.of(FreshServiceEntityNames.CONTRACT_ATTACHMENTS)),
            Map.entry(FreshServiceEntityNames.CUSTOM_OBJECTS, List.of(FreshServiceEntityNames.OBJECT_RECORDS)),
            Map.entry(FreshServiceEntityNames.PROBLEMS, List.of(FreshServiceEntityNames.PROBLEM_NOTES,
                    FreshServiceEntityNames.PROBLEM_TASKS, FreshServiceEntityNames.PROBLEM_TIME_ENTRIES)),
            Map.entry(FreshServiceEntityNames.PROJECTS, List.of(FreshServiceEntityNames.PROJECT_SPRINTS,
                    FreshServiceEntityNames.PROJECT_TASK_PRIORITIES, FreshServiceEntityNames.PROJECT_TASKS,
                    FreshServiceEntityNames.PROJECT_VERSIONS, FreshServiceEntityNames.PROJECTS_MEMBERSHIPS,
                    FreshServiceEntityNames.PROJECTS_TASK_STATUES, FreshServiceEntityNames.PROJECTS_TASK_TYPES)),
            Map.entry(FreshServiceEntityNames.RELEASES, List.of(FreshServiceEntityNames.RELEASES_NOTES,
                    FreshServiceEntityNames.RELEASES_TASKS, FreshServiceEntityNames.RELEASES_TIME_ENTRIES)),
            Map.entry(FreshServiceEntityNames.TICKETS, List.of(FreshServiceEntityNames.TICKET_ACTIVITIES,
                    FreshServiceEntityNames.TICKET_CONVERSATIONS, FreshServiceEntityNames.TICKET_TASKS,
                    FreshServiceEntityNames.TICKET_TIME_ENTRIES))
    );


    public static Map<String, String> ENTITY_API_PATH_MAP = new HashMap<>();

    public static Map<String, String> getEntityApiPathMap() {

        ENTITY_API_PATH_MAP.put(FreshServiceEntityNames.PROBLEM_FIELDS, API_BASE_PATH + "problem_form_fields");
        ENTITY_API_PATH_MAP.put(FreshServiceEntityNames.CHANGES_FORM_FIELDS, API_BASE_PATH + "change_form_fields");
        ENTITY_API_PATH_MAP.put(FreshServiceEntityNames.RELEASE_FIELDS, API_BASE_PATH + "release_form_fields");
        ENTITY_API_PATH_MAP.put(FreshServiceEntityNames.SOLUTION_CATEGORIES, API_BASE_PATH + "solutions/categories");
        ENTITY_API_PATH_MAP.put(FreshServiceEntityNames.SERVICE_CATALOG_CATEGORIES, API_BASE_PATH + "service_catalog/categories");
        ENTITY_API_PATH_MAP.put(FreshServiceEntityNames.APPLICATION_INSTALLATIONS, API_BASE_PATH + "applications/{application_id}/installations");
        ENTITY_API_PATH_MAP.put(FreshServiceEntityNames.APPLICATION_LICENSES, API_BASE_PATH + "applications/{application_id}/licenses");
        ENTITY_API_PATH_MAP.put(FreshServiceEntityNames.APPLICATION_USERS, API_BASE_PATH + "applications/{application_id}/users");
        ENTITY_API_PATH_MAP.put(FreshServiceEntityNames.APPLICATION_RELATIONSHIPS, API_BASE_PATH + "applications/{application_id}/relationships");
        ENTITY_API_PATH_MAP.put(FreshServiceEntityNames.ASSETS_COMPONENTS, API_BASE_PATH + "assets/{assets_display_id}/components");
        ENTITY_API_PATH_MAP.put(FreshServiceEntityNames.ASSETS_REQUESTS, API_BASE_PATH + "assets/{assets_display_id}/requests");
        ENTITY_API_PATH_MAP.put(FreshServiceEntityNames.ASSETS_CONTRACTS, API_BASE_PATH + "assets/{assets_display_id}/contracts");
        ENTITY_API_PATH_MAP.put(FreshServiceEntityNames.CHANGES_NOTES, API_BASE_PATH + "changes/{changes_id}/notes");
        ENTITY_API_PATH_MAP.put(FreshServiceEntityNames.CHANGES_TASKS, API_BASE_PATH + "changes/{changes_id}/tasks");
        ENTITY_API_PATH_MAP.put(FreshServiceEntityNames.CHANGES_TIME_ENTRIES, API_BASE_PATH + "changes/{changes_id}/time_entries");
        ENTITY_API_PATH_MAP.put(FreshServiceEntityNames.CONTRACT_ATTACHMENTS, API_BASE_PATH + "contracts/{contract_id}/attachments");
        ENTITY_API_PATH_MAP.put(FreshServiceEntityNames.DEPARTMENT_FIELDS, API_BASE_PATH + "department_fields");
        ENTITY_API_PATH_MAP.put(FreshServiceEntityNames.PROBLEM_NOTES, API_BASE_PATH + "problems/{problem_id}/notes");
        ENTITY_API_PATH_MAP.put(FreshServiceEntityNames.PROBLEM_TASKS, API_BASE_PATH + "problems/{problem_id}/tasks");
        ENTITY_API_PATH_MAP.put(FreshServiceEntityNames.PROBLEM_TIME_ENTRIES, API_BASE_PATH + "problems/{problem_id}/time_entries");
        ENTITY_API_PATH_MAP.put(FreshServiceEntityNames.PROJECTS, API_BASE_PATH + "pm/projects");
        ENTITY_API_PATH_MAP.put(FreshServiceEntityNames.PROJECT_FIELDS, API_BASE_PATH + "pm/project-fields");
        ENTITY_API_PATH_MAP.put(FreshServiceEntityNames.PROJECT_SPRINTS, API_BASE_PATH + "pm/projects/{projects_id}/sprints");
        ENTITY_API_PATH_MAP.put(FreshServiceEntityNames.PROJECT_TASK_PRIORITIES, API_BASE_PATH + "pm/projects/{projects_id}/task-priorities");
        ENTITY_API_PATH_MAP.put(FreshServiceEntityNames.PROJECT_TASKS, API_BASE_PATH + "pm/projects/{projects_id}/tasks");
        ENTITY_API_PATH_MAP.put(FreshServiceEntityNames.PROJECT_TEMPLATES, API_BASE_PATH + "pm/project_templates");
        ENTITY_API_PATH_MAP.put(FreshServiceEntityNames.PROJECT_VERSIONS, API_BASE_PATH + "pm/projects/{projects_id}/versions");
        ENTITY_API_PATH_MAP.put(FreshServiceEntityNames.PROJECTS_MEMBERSHIPS, API_BASE_PATH + "pm/projects/{projects_id}/memberships");
        ENTITY_API_PATH_MAP.put(FreshServiceEntityNames.PROJECTS_TASK_STATUES, API_BASE_PATH + "pm/projects/{projects_id}/task-statuses");
        ENTITY_API_PATH_MAP.put(FreshServiceEntityNames.PROJECTS_TASK_TYPES, API_BASE_PATH + "pm/projects/{projects_id}/task-types");
        ENTITY_API_PATH_MAP.put(FreshServiceEntityNames.RELEASES_NOTES, API_BASE_PATH + "releases/{release_id}/notes");
        ENTITY_API_PATH_MAP.put(FreshServiceEntityNames.RELEASES_TASKS, API_BASE_PATH + "releases/{release_id}/tasks");
        ENTITY_API_PATH_MAP.put(FreshServiceEntityNames.RELEASES_TIME_ENTRIES, API_BASE_PATH + "releases/{release_id}/time_entries");
        ENTITY_API_PATH_MAP.put(FreshServiceEntityNames.RELATIONSHIP_TYPES, API_BASE_PATH + "relationship_types");
        ENTITY_API_PATH_MAP.put(FreshServiceEntityNames.RELATIONSHIPS, API_BASE_PATH + "relationships");
        ENTITY_API_PATH_MAP.put(FreshServiceEntityNames.REQUESTER_FIELDS, API_BASE_PATH + "requester_fields");
        ENTITY_API_PATH_MAP.put(FreshServiceEntityNames.REQUESTERS, API_BASE_PATH + "requesters");
        ENTITY_API_PATH_MAP.put(FreshServiceEntityNames.TICKET_FIELDS, API_BASE_PATH + "ticket_form_fields");
        ENTITY_API_PATH_MAP.put(FreshServiceEntityNames.TICKET_ACTIVITIES, API_BASE_PATH + "tickets/{ticket_id}/activities");
        ENTITY_API_PATH_MAP.put(FreshServiceEntityNames.TICKET_CONVERSATIONS, API_BASE_PATH + "tickets/{ticket_id}/conversations");
        ENTITY_API_PATH_MAP.put(FreshServiceEntityNames.TICKET_TASKS, API_BASE_PATH + "tickets/{ticket_id}/tasks");
        ENTITY_API_PATH_MAP.put(FreshServiceEntityNames.TICKET_TIME_ENTRIES, API_BASE_PATH + "tickets/{ticket_id}/time_entries");
        ENTITY_API_PATH_MAP.put(FreshServiceEntityNames.CUSTOM_OBJECTS, API_BASE_PATH + "objects");
        ENTITY_API_PATH_MAP.put(FreshServiceEntityNames.OBJECT_RECORDS, API_BASE_PATH + "objects/{object_id}/records");
        ENTITY_API_PATH_MAP.put(FreshServiceEntityNames.SERVICE_CATALOG_ITEMS, API_BASE_PATH + "service_catalog/items");
        ENTITY_API_PATH_MAP.put(FreshServiceEntityNames.SLA_POLICIES, API_BASE_PATH + "sla_policies");
        ENTITY_API_PATH_MAP.put(FreshServiceEntityNames.POST_INCIDENT_REPORT_TEMPLATES, API_BASE_PATH + "post-incident-reports/templates");

        HEADERS_BY_ENTITY.keySet().forEach(entity -> ENTITY_API_PATH_MAP.putIfAbsent(entity, getUriPath(entity)));
        return ENTITY_API_PATH_MAP;
    }

    private FreshServiceConstants() {}
}
