package io.datalakehouse.common;

import java.util.List;
import java.util.Map;

public class PayCorConstants {

    public static final String CONNECTOR_NAME = "PAYCOR";
    public static final String[] ID_HEADERS = {"ID"};
    public static final String SUBSCRIPTION_KEY = "Ocp-Apim-Subscription-Key";
    public static final Integer PAGE_SIZE = 100;
    public static final long DEFAULT_HISTORICAL_DAYS = 30L;

    public static String getBaseUrl (String environment) {
        if (environment == null || environment.isBlank()) {
            return "https://apis-sandbox.paycor.com"; // default
        }

        return switch (environment.trim().toUpperCase()) {
            case "PROD", "PRODUCTION" -> "https://apis.paycor.com";
            case "DEMO", "SANDBOX" -> "https://apis-sandbox.paycor.com";
            default -> throw new IllegalArgumentException("Unsupported " + CONNECTOR_NAME + "environment: " + environment);
        };
    }

    public static final class PayCorEntityNames {

        public static final String LEGAL_ENTITY_TENANTS = "LEGAL_ENTITY_TENANTS";
        public static final String LEGAL_ENTITY_WORK_LOCATIONS = "LEGAL_ENTITY_WORK_LOCATIONS";
        public static final String EMPLOYEE_TAXES = "EMPLOYEE_TAXES";
        public static final String LEGAL_ENTITY_TIMEOFF_REQUESTS = "LEGAL_ENTITY_TIMEOFF_REQUESTS";
        public static final String EMPLOYEE_PAYSTUB_DOCUMENT_DATA = "EMPLOYEE_PAYSTUB_DOCUMENT_DATA";
        public static final String EMPLOYEE_CERTIFICATIONS = "EMPLOYEE_CERTIFICATIONS";
        public static final String LEGAL_ENTITY_DEDUCTIONS = "LEGAL_ENTITY_DEDUCTIONS";
        public static final String PAYROLL_CUSTOM_FIELD_VALUES = "PAYROLL_CUSTOM_FIELD_VALUES";
        public static final String EMPLOYEE_I9_VERIFICATION = "EMPLOYEE_I9_VERIFICATION";
        public static final String EMPLOYEE_DEDUCTION = "EMPLOYEE_DEDUCTION";
        public static final String LEGAL_ENTITY_DEPARTMENTS = "LEGAL_ENTITY_DEPARTMENTS";
        public static final String LEGAL_ENTITY_FORCASTING = "LEGAL_ENTITY_FORCASTING";
        public static final String LEGAL_ENTITY_SCHEDULING_SHIFTS = "LEGAL_ENTITY_SCHEDULING_SHIFTS";
        public static final String LEGAL_ENTITY_EMPLOYEES_IDENTIFYING_DATA = "LEGAL_ENTITY_EMPLOYEES_IDENTIFYING_DATA";
        public static final String LEGAL_ENTITY_MISSED_PUNCH_REQUESTS = "LEGAL_ENTITY_MISSED_PUNCH_REQUESTS";
        public static final String EMPLOYEE_PAYRATES = "EMPLOYEE_PAYRATES";
        public static final String LABOUR_CODES = "LABOUR_CODES";
        public static final String LEGAL_ENTITY_CERTIFICATION_ORGANIZATION = "LEGAL_ENTITY_CERTIFICATION_ORGANIZATION";
        public static final String EMPLOYEE_TAX_DOCUMENTS = "EMPLOYEE_TAX_DOCUMENTS";
        public static final String LEGAL_ENTITY_SCHEDULE_GROUPS = "LEGAL_ENTITY_SCHEDULE_GROUPS";
        public static final String LEGAL_ENTITY_PAY_ITEMS = "LEGAL_ENTITY_PAY_ITEMS";
        public static final String LEGAL_ENTITY_PAYSTUBS = "LEGAL_ENTITY_PAYSTUBS";
        public static final String LEGAL_ENTITY_PAYSCHEDULE = "LEGAL_ENTITY_PAYSCHEDULE";
        public static final String EMPLOYEE_TIMEOFF_ACCRUALS = "EMPLOYEE_TIMEOFF_ACCRUALS";
        public static final String EMPLOYEE_PUNCHES = "EMPLOYEE_PUNCHES";
        public static final String EMPLOYEE_HSA_ACCOUNT = "EMPLOYEE_HSA_ACCOUNT";
        public static final String EMPLOYEE_POLICY_GROUP_DATA = "EMPLOYEE_POLICY_GROUP_DATA";
        public static final String LEGAL_ENTITY_WORK_SITES = "LEGAL_ENTITY_WORK_SITES";
        public static final String LEGAL_ENTITY_PUNCHES = "LEGAL_ENTITY_PUNCHES";
        public static final String LEGAL_ENTITY_PAY_DATA = "LEGAL_ENTITY_PAY_DATA";
        public static final String EMPLOYEE_UNPAID_PAYRATES = "EMPLOYEE_UNPAID_PAYRATES";
        public static final String ATS_ACCOUNTS = "ATS_ACCOUNTS";
        public static final String HOURS = "HOURS";
        public static final String LEGAL_ENTITY_UNASSIGNED_PUNCHES = "LEGAL_ENTITY_UNASSIGNED_PUNCHES";
        public static final String LEGAL_ENTITY_SERVICES = "LEGAL_ENTITY_SERVICES";
        public static final String LEGAL_ENTITY_PAY_GROUPS = "LEGAL_ENTITY_PAY_GROUPS";
        public static final String LEGAL_ENTITY_MANAGER_PROFILES = "LEGAL_ENTITY_MANAGER_PROFILES";
        public static final String EMPLOYEE_PERSONAL_DATA = "EMPLOYEE_PERSONAL_DATA";
        public static final String EMPLOYEE_CUSTOM_FIELDS = "EMPLOYEE_CUSTOM_FIELDS";
        public static final String LEGAL_ENTITY_EARNINGS = "LEGAL_ENTITY_EARNINGS";
        public static final String ATS_JOBS = "ATS_JOBS";
        public static final String EMPLOYEE_HOURS = "EMPLOYEE_HOURS";
        public static final String LEGAL_ENTITY_REASON_CODES = "LEGAL_ENTITY_REASON_CODES";
        public static final String EMPLOYEE_TIMEOFF_PLAN_ASSIGNMENT = "EMPLOYEE_TIMEOFF_PLAN_ASSIGNMENT";
        public static final String LEGAL_ENTITY_LABOUR_PROFILES = "LEGAL_ENTITY_LABOUR_PROFILES";
        public static final String ATS_JOB_CANDIDATES = "ATS_JOB_CANDIDATES";
        public static final String LEGAL_ENTITY_CERTIFICATIONS = "LEGAL_ENTITY_CERTIFICATIONS";
        public static final String LEGAL_ENTITY_TIMEOFF_PLANS = "LEGAL_ENTITY_TIMEOFF_PLANS";
        public static final String LEGAL_ENTITY_RETIREMENT_DATA = "LEGAL_ENTITY_RETIREMENT_DATA";
        public static final String LABOUR_CATEGORIES = "LABOUR_CATEGORIES";
        public static final String LEGAL_ENTITY_ACTIVITY_TYPES = "LEGAL_ENTITY_ACTIVITY_TYPES";
        public static final String LEGAL_ENTITY_ON_DEMAND_PAY_DEDUCTION_INFORMATION = "LEGAL_ENTITY_ON_DEMAND_PAY_DEDUCTION_INFORMATION";
        public static final String LEGAL_ENTITY_EMPLOYEES = "LEGAL_ENTITY_EMPLOYEES";
        public static final String EMPLOYEE_PAY_SCHEDULE = "EMPLOYEE_PAY_SCHEDULE";
        public static final String EMPLOYEE_ONBOARDING = "EMPLOYEE_ONBOARDING";
        public static final String EMPLOYEE_BENEFIT_CLASSIFICATION = "EMPLOYEE_BENEFIT_CLASSIFICATION";
        public static final String EMPLOYEE_DIRECT_DEPOSITS = "EMPLOYEE_DIRECT_DEPOSITS";
        public static final String LEGAL_ENTITY = "LEGAL_ENTITY";
        public static final String LEGAL_ENTITY_TAXES = "LEGAL_ENTITY_TAXES";
        public static final String EMPLOYEE_PUNCH_PROFILE_DATA = "EMPLOYEE_PUNCH_PROFILE_DATA";
        public static final String LEGAL_ENTITY_PAYROLL_PROCESSING = "LEGAL_ENTITY_PAYROLL_PROCESSING";
        public static final String EMPLOYEE_TIME_CARD = "EMPLOYEE_TIME_CARD";
        public static final String EMPLOYEE_EARNINGS = "EMPLOYEE_EARNINGS";
        public static final String LEGAL_ENTITY_TIMEOFF_TYPES = "LEGAL_ENTITY_TIMEOFF_TYPES";
        public static final String LEGAL_ENTITY_SCHEDULING_JOBS = "LEGAL_ENTITY_SCHEDULING_JOBS";
        public static final String PERSONS = "PERSONS";

        private PayCorEntityNames() {}
    }

    public static final class PayCorHeaders {

        public static final String[] LEGAL_ENTITY_TENANTS = {"LEGAL_ENTITY_ID", "TENANT_ID", "__ROW_MD5", "__DLH_IS_DELETED", "__DLH_SYNC_TS", "__DLH_START_TS", "__DLH_FINISH_TS", "__DLH_IS_ACTIVE"};
        public static final String[] LEGAL_ENTITY_WORK_LOCATIONS = {"ID", "NAME", "ADDRESSES", "PHONES", "LOCATION_NUMBER", "STORE_ID", "IS_FMLA_ELIGIBLE", "PAYROLL_CUSTOM_VALUES_DEPARTMENT_TYPE", "__ROW_MD5", "__DLH_IS_DELETED", "__DLH_SYNC_TS", "__DLH_START_TS", "__DLH_FINISH_TS", "__DLH_IS_ACTIVE"};
        public static final String[] EMPLOYEE_TAXES = {"ID", "LEGAL_ENTITY_TAX_ID", "TAX_CODE", "DESCRIPTION", "TAX_TYPE", "RECIPROCITY_TYPE", "FILING_STATUS_CODE", "FILING_STATUS_DESCRIPTION", "WITHHOLDING_EFFECTIVE_START_DATE", "BLOCK_DATE", "NON_RESIDENT_ALIEN", "IS_PROBATIONARY_EMPLOYEE", "OCCUPATIONAL_CODE", "GEOGRAPHIC_CODE", "SOC_CODE", "SEASONAL_CODE", "COUNTY_CODE", "SPOUSE_WORK", "DEPENDENT_INSURANCE_ELIGIBLE", "DEPENDENT_INSURANCE_ELIGIBLE_DATE", "APPLICABLE_BIRTHYEAR", "ADJUST_WITHHOLDING", "AMOUNT", "EMPLOYEE_TAXES_PERCENTAGE", "NCCI_CODE", "PSD_CODE", "PSD_RATE", "ON_HOLD", "EXEMPTIONS_EXEMPTIONS", "EXEMPTIONS_EXEMPTION_AMOUNT", "EXEMPTIONS_EMPLOYEE_LOW_INCOME_EXEMPTION", "EXEMPTIONS_CURRENT_YEAR_EXEMPT", "EXEMPTIONS_NEXT_YEAR_EXEMPT", "TAX_CREDIT_NUMBER_OF_DEPENDENTS", "TAX_CREDIT_NUMBER_OF_OTHER_DEPENDENTS", "TAX_CREDIT_HAS_TWO_INCOMES", "TAX_CREDIT_ADDITIONAL_INCOME", "TAX_CREDIT_ADDITIONAL_DEDUCTION", "TAX_CREDIT_QUALIFIED_DEPENDENT_CREDIT", "TAX_CREDIT_OTHER_DEPENDENT_CREDIT", "TAX_CREDIT_TOTAL_CREDITS", "EMPLOYEE_ID", "__ROW_MD5", "__DLH_IS_DELETED", "__DLH_SYNC_TS", "__DLH_START_TS", "__DLH_FINISH_TS", "__DLH_IS_ACTIVE"};
        public static final String[] LEGAL_ENTITY_TIMEOFF_REQUESTS = {"TIME_OFF_REQUEST_ID", "LEGAL_ENTITY_ID", "BENEFIT_CODE", "TOTAL_HOURS", "LEGAL_ENTITY_TIMEOFF_REQUESTS_DAYS", "COMMENT", "STATUS", "CREATED_DATE", "STATUS_UPDATE_TIME", "STATUS_UPDATE_BY_EMPLOYEE_ID", "CREATED_BY_EMPLOYEE_ID", "EMPLOYEE_ID", "__ROW_MD5", "__DLH_IS_DELETED", "__DLH_SYNC_TS", "__DLH_START_TS", "__DLH_FINISH_TS", "__DLH_IS_ACTIVE"};
        public static final String[] EMPLOYEE_PAYSTUB_DOCUMENT_DATA = {"DOCUMENT_ID", "PAYROLL_ID", "PLANNER_ID", "CHECK_DATE", "PROCESS_DATE", "EMPLOYEE_ID", "LEGAL_ENTITY_ID", "FILE_NAME", "PAY_STUB_DOCUMENT_URL_ID", "__ROW_MD5", "__DLH_IS_DELETED", "__DLH_SYNC_TS", "__DLH_START_TS", "__DLH_FINISH_TS", "__DLH_IS_ACTIVE"};
        public static final String[] EMPLOYEE_CERTIFICATIONS = {"EMPLOYEE_CERTIFICATION_ID", "CERTIFICATION_ID", "CERTIFICATION_NAME", "CERTIFICATION_NUMBER", "CERTIFICATION_ORGANIZATION_NAME", "CERTIFICATION_ORGANIZATION_ID", "NOTES", "EFFECTIVE_DATE", "EXPIRATION_DATE", "__ROW_MD5", "__DLH_IS_DELETED", "__DLH_SYNC_TS", "__DLH_START_TS", "__DLH_FINISH_TS", "__DLH_IS_ACTIVE"};
        public static final String[] LEGAL_ENTITY_DEDUCTIONS = {"ID", "CODE", "GLOBAL_DEDUCTION_CODE", "DESCRIPTION", "LEGAL_ENTITY_DEDUCTIONS_TYPE", "LINKED_DEDUCTION_CODES", "AMOUNT", "RATE", "FREQUENCY", "IS_ON_W2", "ON_HOLD", "EFFECTIVE_START_DATE", "LEGAL_ENTITY_ID", "__ROW_MD5", "__DLH_IS_DELETED", "__DLH_SYNC_TS", "__DLH_START_TS", "__DLH_FINISH_TS", "__DLH_IS_ACTIVE"};
        public static final String[] PAYROLL_CUSTOM_FIELD_VALUES = {"PAYROLL_CUSTOM_FIELD_ID", "NAME", "PAYROLL_CUSTOM_FIELD_VALUES_VALUE", "__ROW_MD5", "__DLH_IS_DELETED", "__DLH_SYNC_TS", "__DLH_START_TS", "__DLH_FINISH_TS", "__DLH_IS_ACTIVE"};
        public static final String[] EMPLOYEE_I9_VERIFICATION = {"EMPLOYEE_ID", "CITIZEN_OF_COUNTRY", "WORK_ELIGIBILITY", "WORK_VISA_TYPE", "WORK_VISA_EXPIRATION_DATE", "ALIEN_ADMISSION_NUMBER", "ALIEN_ADMISSION_EXPIRATION_DATE", "LIST_A", "LIST_B", "LIST_C", "FOREIGN_PASSPORT_NUMBER", "COUNTRY_OF_ISSUANCE", "ADDITIONAL_INFORMATION", "HIRE_DATE", "DATE_MODIFIED", "__ROW_MD5", "__DLH_IS_DELETED", "__DLH_SYNC_TS", "__DLH_START_TS", "__DLH_FINISH_TS", "__DLH_IS_ACTIVE"};
        public static final String[] EMPLOYEE_DEDUCTION = {"ID", "CODE", "DESCRIPTION", "EMPLOYEE_DEDUCTION_TYPE", "FREQUENCY", "INCLUDE_IN_PAY", "ON_HOLD", "EFFECTIVE_START_DATE", "EFFECTIVE_END_DATE", "AMOUNT_DATA", "LIMITS", "EMPLOYEE_ID", "LEGAL_ENTITY_DEDUCTION_ID", "__ROW_MD5", "__DLH_IS_DELETED", "__DLH_SYNC_TS", "__DLH_START_TS", "__DLH_FINISH_TS", "__DLH_IS_ACTIVE"};
        public static final String[] LEGAL_ENTITY_DEPARTMENTS = {"ID", "CODE", "DESCRIPTION", "PARENT_ID", "LEGAL_ENTITY_DEPARTMENTS_LEVEL", "PAYROLL_ID", "PAYROLL_DESCRIPTION", "WORK_LOCATION_ID", "WORK_LOCATION_NAME", "CUSTOM_FIELD_VALUES", "__ROW_MD5", "__DLH_IS_DELETED", "__DLH_SYNC_TS", "__DLH_START_TS", "__DLH_FINISH_TS", "__DLH_IS_ACTIVE"};
        public static final String[] LEGAL_ENTITY_FORCASTING = {"LEGAL_ENTITY_ID", "TRANSACTION_DATE", "LEGAL_ENTITY_FORCASTING_VALUE", "SCHEDULE_GROUP_NAME", "__ROW_MD5", "__DLH_IS_DELETED", "__DLH_SYNC_TS", "__DLH_START_TS", "__DLH_FINISH_TS", "__DLH_IS_ACTIVE"};
        public static final String[] LEGAL_ENTITY_SCHEDULING_SHIFTS = {"ID", "EMPLOYEE_ID", "EMPLOYEE_NAME", "SCHEDULING_JOB_ID", "SCHEDULING_JOB_NAME", "SCHEDULE_GROUP_ID", "SCHEDULE_GROUP_NAME", "IS_PUBLISHED", "TITLE", "START_DATE_TIME", "END_DATE_TIME", "COLOR", "DEPARTMENT_ID", "DEPARTMENT_NAME", "NOTES", "BREAK_RULES", "NET_PAID_HOURS_ONLY", "WORK_SITE_ID", "WORK_SITE_NAME", "DISTANCE", "ACKNOWLEDGEMENT_STATUS", "ACTIVITY_TYPE_ID", "ACTIVITY_TYPE_NAME", "ACTIVITY_TYPE_COLOR", "LABOR_CODES", "WORK_LOCATION_ID", "WORK_LOCATION_NAME", "__ROW_MD5", "__DLH_IS_DELETED", "__DLH_SYNC_TS", "__DLH_START_TS", "__DLH_FINISH_TS", "__DLH_IS_ACTIVE"};
        public static final String[] LEGAL_ENTITY_EMPLOYEES_IDENTIFYING_DATA = {"EMPLOYEE_ID", "FIRST_NAME", "LAST_NAME", "SOCIAL_SECURITY_NUMBER", "EMPLOYEE_NUMBER", "BIRTH_DATE", "STATUS", "__ROW_MD5", "__DLH_IS_DELETED", "__DLH_SYNC_TS", "__DLH_START_TS", "__DLH_FINISH_TS", "__DLH_IS_ACTIVE"};
        public static final String[] LEGAL_ENTITY_MISSED_PUNCH_REQUESTS = {"EMPLOYEE_ID", "PUNCH_ID", "PUNCH_REF_ID", "PUNCH_DATE_TIME", "PUNCH_STATUS_TYPE", "IS_TRANSFER", "ACTIVITY_TYPE_ID", "DEPARTMENT_ID", "NOTE", "LABOR_CODES", "WORK_LOCATION_ID", "__ROW_MD5", "__DLH_IS_DELETED", "__DLH_SYNC_TS", "__DLH_START_TS", "__DLH_FINISH_TS", "__DLH_IS_ACTIVE"};
        public static final String[] EMPLOYEE_PAYRATES = {"ID", "EFFECTIVE_START_DATE", "EFFECTIVE_END_DATE", "SEQUENCE_NUMBER", "PAY_RATE", "ANNUAL_PAY_RATE", "DESCRIPTION", "ANNUAL_HOURS", "EMPLOYEE_PAYRATES_TYPE", "REASON", "NOTES", "EMPLOYEES_ID", "__ROW_MD5", "__DLH_IS_DELETED", "__DLH_SYNC_TS", "__DLH_START_TS", "__DLH_FINISH_TS", "__DLH_IS_ACTIVE"};
        public static final String[] LABOUR_CODES = {"LABOR_CODE_ID", "LABOR_CATEGORY_ID", "LEGAL_ENTITY_ID", "LABOR_CODE_NAME", "DESCRIPTION", "CODE", "EFFECTIVE_START_DATE", "EFFECTIVE_END_DATE", "__ROW_MD5", "__DLH_IS_DELETED", "__DLH_SYNC_TS", "__DLH_START_TS", "__DLH_FINISH_TS", "__DLH_IS_ACTIVE"};
        public static final String[] LEGAL_ENTITY_CERTIFICATION_ORGANIZATION = {"CERTIFICATION_ORGANIZATION_ID", "CERTIFICATION_ORGANIZATION_NAME", "__ROW_MD5", "__DLH_IS_DELETED", "__DLH_SYNC_TS", "__DLH_START_TS", "__DLH_FINISH_TS", "__DLH_IS_ACTIVE"};
        public static final String[] EMPLOYEE_TAX_DOCUMENTS = {"REPORT_TYPE", "EMPLOYEE_ID", "EMPLOYEE_TAX_DOCUMENTS_YEAR", "DOCUMENT_ID", "LEGAL_ENTITY_ID", "REPORT_NAME", "FILE_NAME", "TAX_DOCUMENT_URL_ID", "__ROW_MD5", "__DLH_IS_DELETED", "__DLH_SYNC_TS", "__DLH_START_TS", "__DLH_FINISH_TS", "__DLH_IS_ACTIVE"};
        public static final String[] LEGAL_ENTITY_SCHEDULE_GROUPS = {"ID", "NAME", "IS_ACTIVE", "__ROW_MD5", "__DLH_IS_DELETED", "__DLH_SYNC_TS", "__DLH_START_TS", "__DLH_FINISH_TS", "__DLH_IS_ACTIVE"};
        public static final String[] LEGAL_ENTITY_PAY_ITEMS = {"PAY_ITEM_ID", "PAY_ITEM_REF_ID", "EMPLOYEE_ID", "LEGAL_ENTITY_EARNING_ID", "AMOUNT", "DEPARTMENT_ID", "NOTE", "LABOR_CODES", "LEGAL_ENTITY_PAY_ITEMS_DATE", "WORK_LOCATION_ID", "__ROW_MD5", "__DLH_IS_DELETED", "__DLH_SYNC_TS", "__DLH_START_TS", "__DLH_FINISH_TS", "__DLH_IS_ACTIVE"};
        public static final String[] LEGAL_ENTITY_PAYSTUBS = {"EMPLOYEE_ID", "CLIENT_ID", "CHECK_NUMBER", "PLANNER_ID", "CHECK_TYPE", "PERIOD_START_DATE", "PERIOD_END_DATE", "GROSS_AMOUNT", "NET_AMOUNT", "EARNINGS_TOTAL_EARNINGS_AMOUNT", "EARNINGS_TOTAL_EARNINGS_HOURS", "EARNINGS_EARNINGS", "TAXES_TOTAL_TAXES_AMOUNT", "TAXES_TOTAL_EMPLOYEE_TAX_AMOUNT", "TAXES_TOTAL_EMPLOYER_TAX_AMOUNT", "TAXES_TAXES", "DEDUCTIONS_TOTAL_DEDUCTIONS_AMOUNT", "DEDUCTIONS_TOTAL_EMPLOYER_DEDUCTIONS_AMOUNT", "DEDUCTIONS_TOTAL_EMPLOYEE_DEDUCTIONS_AMOUNT", "DEDUCTIONS_DEDUCTIONS", "EMPLOYEE_ID", "LEGAL_ENTITY_ID", "__ROW_MD5", "__DLH_IS_DELETED", "__DLH_SYNC_TS", "__DLH_START_TS", "__DLH_FINISH_TS", "__DLH_IS_ACTIVE"};
        public static final String[] LEGAL_ENTITY_PAYSCHEDULE = {"LEGAL_ENTITY_ID", "PERIOD_START_DATE", "PERIOD_END_DATE", "CHECK_DATE", "PROCESS_DATE", "PLANNER_ID", "PAYROLL_STATUS", "__ROW_MD5", "__DLH_IS_DELETED", "__DLH_SYNC_TS", "__DLH_START_TS", "__DLH_FINISH_TS", "__DLH_IS_ACTIVE"};
        public static final String[] EMPLOYEE_TIMEOFF_ACCRUALS = {"EMPLOYEE_NAME", "EMPLOYEE_NUMBER", "EMPLOYEE_ID", "TYPE_BALANCES", "__ROW_MD5", "__DLH_IS_DELETED", "__DLH_SYNC_TS", "__DLH_START_TS", "__DLH_FINISH_TS", "__DLH_IS_ACTIVE"};
        public static final String[] EMPLOYEE_PUNCHES = {"PUNCH_ID", "PUNCH_REF_ID", "PUNCH_DATE_TIME", "PUNCH_STATUS_TYPE", "IS_TRANSFER", "ACTIVITY_TYPE_ID", "DEPARTMENT_ID", "NOTE", "LABOR_CODES", "WORK_LOCATION_ID", "__ROW_MD5", "__DLH_IS_DELETED", "__DLH_SYNC_TS", "__DLH_START_TS", "__DLH_FINISH_TS", "__DLH_IS_ACTIVE"};
        public static final String[] EMPLOYEE_HSA_ACCOUNT = {"ID", "ACCOUNT_TYPE", "MASKED_ACCOUNT_NUMBER", "UNMASKED_ACCOUNT_NUMBER", "ROUTING_NUMBER", "BANK_NAME", "FREQUENCY", "DEDUCTION_CODE", "DIRECT_DEPOSIT_TYPE", "ON_HOLD", "AMOUNT", "RATE", "EMPLOYEE_ID", "__ROW_MD5", "__DLH_IS_DELETED", "__DLH_SYNC_TS", "__DLH_START_TS", "__DLH_FINISH_TS", "__DLH_IS_ACTIVE"};
        public static final String[] EMPLOYEE_POLICY_GROUP_DATA = {"POLICY_NAME", "EMPLOYEE_ID", "POLICY_TYPE", "__ROW_MD5", "__DLH_IS_DELETED", "__DLH_SYNC_TS", "__DLH_START_TS", "__DLH_FINISH_TS", "__DLH_IS_ACTIVE"};
        public static final String[] LEGAL_ENTITY_WORK_SITES = {"ID", "LEGAL_ENTITY_ID", "NAME", "STREET_LINE1", "STREET_LINE2", "CITY", "LEGAL_ENTITY_WORK_SITES_STATE", "ZIP_CODE", "COUNTRY", "PHONE_NUMBER", "__ROW_MD5", "__DLH_IS_DELETED", "__DLH_SYNC_TS", "__DLH_START_TS", "__DLH_FINISH_TS", "__DLH_IS_ACTIVE"};
        public static final String[] LEGAL_ENTITY_PUNCHES = {"EMPLOYEE_ID", "BADGE_NUMBER", "DISPLAY_DATE", "PUNCH_IN", "PUNCH_OUT", "HOUR_AMOUNT", "DEPARTMENT_CODE", "DEPARTMENT_NAME", "EARNING_CODE", "ESTIMATED_GROSS_PAY", "LABOR_CODES", "EMPLOYEE_NUMBER", "__ROW_MD5", "__DLH_IS_DELETED", "__DLH_SYNC_TS", "__DLH_START_TS", "__DLH_FINISH_TS", "__DLH_IS_ACTIVE"};
        public static final String[] LEGAL_ENTITY_PAY_DATA = {"EMPLOYEE_ID", "CHECK_DATE", "PROCESS_DATE", "LEGAL_ENTITY_ID", "EMPLOYEE_PAYSTUB_ID", "__ROW_MD5", "__DLH_IS_DELETED", "__DLH_SYNC_TS", "__DLH_START_TS", "__DLH_FINISH_TS", "__DLH_IS_ACTIVE"};
        public static final String[] EMPLOYEE_UNPAID_PAYRATES = {"PAY_RATE_ID", "EMPLOYEE_ID", "ASSIGNMENT_ID", "EMPLOYEE_UNPAID_PAYRATES_SEQUENCE", "CURRENCY_CODE", "RATE", "ANNUAL_RATE", "DESCRIPTION", "EMPLOYEE_UNPAID_PAYRATES_TYPE", "PAY_FREQUENCY", "EFFECTIVE_START_DATE", "EFFECTIVE_END_DATE", "NOTES", "__ROW_MD5", "__DLH_IS_DELETED", "__DLH_SYNC_TS", "__DLH_START_TS", "__DLH_FINISH_TS", "__DLH_IS_ACTIVE"};
        public static final String[] ATS_ACCOUNTS = {"ID", "TITLE", "__ROW_MD5", "__DLH_IS_DELETED", "__DLH_SYNC_TS", "__DLH_START_TS", "__DLH_FINISH_TS", "__DLH_IS_ACTIVE"};
        public static final String[] HOURS = {"EMPLOYEE_ID", "DISPLAY_DATE", "IN_ACTUAL_PUNCH", "OUT_ACTUAL_PUNCH", "IN_ROUNDED_PUNCH", "OUT_ROUNDED_PUNCH", "HOURS_AMOUNT", "DEPARTMENT_CODE", "DEPARTMENT_NAME", "EARNING_CODE", "LABOR_CODES", "__ROW_MD5", "__DLH_IS_DELETED", "__DLH_SYNC_TS", "__DLH_START_TS", "__DLH_FINISH_TS", "__DLH_IS_ACTIVE"};
        public static final String[] LEGAL_ENTITY_UNASSIGNED_PUNCHES = {"PUNCH_ID", "BADGE_NUMBER", "EMPLOYEE_ID", "PUNCH_DATE_TIME", "DEPARTMENT_ID", "REASON", "ACTIVITY_TYPE_NAME", "ACTIVITY_TYPE_ID", "WORK_LOCATION_ID", "__ROW_MD5", "__DLH_IS_DELETED", "__DLH_SYNC_TS", "__DLH_START_TS", "__DLH_FINISH_TS", "__DLH_IS_ACTIVE"};
        public static final String[] LEGAL_ENTITY_SERVICES = {"LEGAL_ENTITY_ID", "TIME_SERVICE", "TIME_ON_DEMAND", "PERFORM_TIME", "PERFORM_TIME_SCHEDULING", "PAYCOR_SCHEDULING", "PAYCOR_SCHEDULING_PRO", "PERFORM_ACCRUALS", "RESELLER_ACCRUALS", "PERFORM_TIME_OFF", "INTEGRATION_PAYROLL_TIME_PARTNER", "WORKFORCE_MANAGEMENT", "JOB_COSTING", "ONBOARDING", "JOB_COSTING_REPORTING", "REPORTING", "HEALTHAND_BENEFITS_EMPLOYEE", "HEALTHAND_BENEFITS", "PAYCHEX_PAYMENTS", "PAYCHEX_BASE", "PAYCHEX_WORKERS_COMPENSATION", "PAYCHEX_INTEGRATION", "PAYCHEX401K_EMPLOYEE", "PAYCHEX401K_PROCESSING", "__ROW_MD5", "__DLH_IS_DELETED", "__DLH_SYNC_TS", "__DLH_START_TS", "__DLH_FINISH_TS", "__DLH_IS_ACTIVE"};
        public static final String[] LEGAL_ENTITY_PAY_GROUPS = {"PAY_GROUP_ID", "LEGAL_ENTITY_ID", "PAYROLL_ID", "PAYROLL_DESCRIPTION", "PAYROLL_CODE", "PAY_GROUP_NAME", "PAY_GROUP_FREQUENCY", "__ROW_MD5", "__DLH_IS_DELETED", "__DLH_SYNC_TS", "__DLH_START_TS", "__DLH_FINISH_TS", "__DLH_IS_ACTIVE"};
        public static final String[] LEGAL_ENTITY_MANAGER_PROFILES = {"PROFILE_ID", "PROFILE_NAME", "LAST_EDITED", "LAST_EDITED_BY", "USE_ONLY_SELECTED_DEPARTMENTS", "USE_ONLY_SELECTED_HOURS", "USE_ONLY_SELECTED_PAY_ITEMS", "USE_ONLY_SELECTED_LABOR_CODES", "USE_ONLY_SELECTED_WORK_LOCATIONS", "USE_ONLY_SELECTED_ACTIVITY_TYPES", "EMPLOYEE_ASSIGNED", "__ROW_MD5", "__DLH_IS_DELETED", "__DLH_SYNC_TS", "__DLH_START_TS", "__DLH_FINISH_TS", "__DLH_IS_ACTIVE"};
        public static final String[] EMPLOYEE_PERSONAL_DATA = {"EMPLOYEE_ID", "FIRST_NAME", "LAST_NAME", "MIDDLE_NAME", "PREFIX", "SUFFIX", "SOCIAL_SECURITY_NUMBER", "BIRTH_DATE", "GENDER", "VETERAN_STATUS", "DISABILITY_STATUS", "MARITAL_STATUS", "ETHNICITY", "__ROW_MD5", "__DLH_IS_DELETED", "__DLH_SYNC_TS", "__DLH_START_TS", "__DLH_FINISH_TS", "__DLH_IS_ACTIVE"};
        public static final String[] EMPLOYEE_CUSTOM_FIELDS = {"CUSTOM_FIELD_ID", "LEGAL_ENTITY_ID", "FIELD_NAME", "DATA_TYPE", "EMPLOYEE_CUSTOM_FIELDS_VALUE", "IS_REQUIRED", "CUSTOM_FIELDS_OPTIONS", "DATE_MODIFIED", "EMPLOYEE_ID", "__ROW_MD5", "__DLH_IS_DELETED", "__DLH_SYNC_TS", "__DLH_START_TS", "__DLH_FINISH_TS", "__DLH_IS_ACTIVE"};
        public static final String[] LEGAL_ENTITY_EARNINGS = {"ID", "CODE", "GLOBAL_EARNING_CODE", "DESCRIPTION", "LEGAL_ENTITY_EARNINGS_HOURS", "AMOUNT", "RATE", "FREQUENCY", "IS_ON_W2", "ON_HOLD", "EFFECTIVE_START_DATE", "FACTOR", "LEGAL_ENTITY_ID", "__ROW_MD5", "__DLH_IS_DELETED", "__DLH_SYNC_TS", "__DLH_START_TS", "__DLH_FINISH_TS", "__DLH_IS_ACTIVE"};
        public static final String[] ATS_JOBS = {"ID", "ATS_ACCOUNT_ID", "ATS_JOBS_NUMBER", "TITLE", "DESCRIPTION", "STATUS", "OPENINGS", "ATS_JOBS_PRIORITY", "CONFIDENTIAL", "INTERNAL", "TIME_TO_FILL", "REMOTE_STATUS", "EEO_CATEGORY", "PAY_RANGE_CURRENCY", "PAY_RANGE_MINIMUM", "PAY_RANGE_MAXIMUM", "PAY_RANGE_PAY_PERIOD", "ATS_LOCATION_ID", "ATS_LOCATION_ADDRESS1", "ATS_LOCATION_ADDRESS2", "ATS_LOCATION_CITY", "ATS_LOCATION_STATE", "ATS_LOCATION_POSTAL_CODE", "ATS_LOCATION_COUNTRY", "ATS_DEPARTMENT_ID", "ATS_DEPARTMENT_TITLE", "HIRING_MANAGERS", "RECRUITERS", "TEAM_MEMBERS", "EXECUTIVES", "ACTIVATED_DATE", "CREATED_DATE", "MODIFIED_DATE", "POSTED_TO_CAREERS", "POSTED_TO_INDEED", "POSTED_TO_SMART_SOURCING", "POSTED_TO_LINKED_IN", "POSTED_TO_ZIP_RECRUITER", "POSTED_TO_GRAVITY", "__ROW_MD5", "__DLH_IS_DELETED", "__DLH_SYNC_TS", "__DLH_START_TS", "__DLH_FINISH_TS", "__DLH_IS_ACTIVE"};
        public static final String[] EMPLOYEE_HOURS = {"HOUR_ID", "LEGAL_ENTITY_EARNING_ID", "DEPARTMENT_ID", "START_DATE_TIME", "TOTAL", "NOTE", "ACTIVITY_TYPE_ID", "HOUR_REF_ID", "LABOR_CODES", "WORK_LOCATION_ID", "__ROW_MD5", "__DLH_IS_DELETED", "__DLH_SYNC_TS", "__DLH_START_TS", "__DLH_FINISH_TS", "__DLH_IS_ACTIVE"};
        public static final String[] LEGAL_ENTITY_REASON_CODES = {"REASON_CODE_ID", "LEGAL_ENTITY_ID", "REASON_CODE_NAME", "EFFECTIVE_START_DATE", "EFFECTIVE_END_DATE", "__ROW_MD5", "__DLH_IS_DELETED", "__DLH_SYNC_TS", "__DLH_START_TS", "__DLH_FINISH_TS", "__DLH_IS_ACTIVE"};
        public static final String[] EMPLOYEE_TIMEOFF_PLAN_ASSIGNMENT = {"PLAN_ASSIGNMENT_ID", "EMPLOYEE_ID", "EMPLOYEE_NUMBER", "ENHANCED_EMPLOYEE_NUMBER", "LEGAL_ENTITY_ID", "TENANT_ID", "TIME_OFF_PLAN_ID", "TIME_OFF_PLAN_NAME", "START_DATE", "END_DATE", "ADJUSTED_ACCRUAL_DATE", "TIME_OFF_TYPE_ID", "TIME_OFF_TYPE_CODE", "TIME_OFF_TYPE_NAME", "STARTING_BALANCE", "CARRY_OVER_YTDSTART", "ACCRUED_YTDSTART", "USED_YTDSTART", "__ROW_MD5", "__DLH_IS_DELETED", "__DLH_SYNC_TS", "__DLH_START_TS", "__DLH_FINISH_TS", "__DLH_IS_ACTIVE"};
        public static final String[] LEGAL_ENTITY_LABOUR_PROFILES = {"LABOR_PROFILE_ID", "LEGAL_ENTITY_ID", "LABOR_PROFILE_NAME", "STATUS", "EMPLOYEE_COUNT", "LEGAL_ENTITY_LABOUR_PROFILES_TYPE", "__ROW_MD5", "__DLH_IS_DELETED", "__DLH_SYNC_TS", "__DLH_START_TS", "__DLH_FINISH_TS", "__DLH_IS_ACTIVE"};
        public static final String[] ATS_JOB_CANDIDATES = {"ID", "JOB_ID", "ATS_ACCOUNT_ID", "EMAIL", "FIRST_NAME", "LAST_NAME", "PREFERRED_NAME", "STARTING_STAGE", "STARTING_STATUS", "STAGE", "STATUS", "SOURCE", "MOBILE_PHONE", "ALT_PHONE", "ALT_EMAIL", "ADDRESS", "ADDRESS2", "CITY", "ATS_JOB_CANDIDATES_STATE", "POSTAL_CODE", "COUNTRY", "CREATED_DATE", "MODIFIED_DATE", "__ROW_MD5", "__DLH_IS_DELETED", "__DLH_SYNC_TS", "__DLH_START_TS", "__DLH_FINISH_TS", "__DLH_IS_ACTIVE"};
        public static final String[] LEGAL_ENTITY_CERTIFICATIONS = {"CERTIFICATION_ID", "CERTIFICATION_NAME", "__ROW_MD5", "__DLH_IS_DELETED", "__DLH_SYNC_TS", "__DLH_START_TS", "__DLH_FINISH_TS", "__DLH_IS_ACTIVE"};
        public static final String[] LEGAL_ENTITY_TIMEOFF_PLANS = {"TIME_OFF_PLAN_ID", "TIME_OFF_PLAN_NAME", "TIME_OFF_TYPE_ID", "LEGAL_ENTITY_ID", "TENANT_ID", "__ROW_MD5", "__DLH_IS_DELETED", "__DLH_SYNC_TS", "__DLH_START_TS", "__DLH_FINISH_TS", "__DLH_IS_ACTIVE"};
        public static final String[] LEGAL_ENTITY_RETIREMENT_DATA = {"LEGAL_ENTITY_ID", "PAYEE_NAME", "BUSINESS_NAME", "PENSION_PLAN_ID", "CHECK_DATE", "PERIOD_END_DATETIME", "PAYEE_CONTACT_NAME", "PAYEE_CONTACT_PHONE_NUMBER", "PAYEE_ADDRESS1", "PAYEE_ADDRESS2", "PAYEE_LOCAL", "PAYEE_STATE_CODE", "PAYEE_ZIP_CODE", "PAYEE_ZIP_CODE4", "RUN_TYPE", "PERIOD_START_DATE", "PAYEE_PAYGROUP_DESCRIPTION", "PAYROLL_ID", "PAYROLL_NAME", "FEDERAL_ID", "FISCAL_YEAR", "SSN", "FREQUENCY_CODE", "EMPLOYEE_LAST_NAME", "EMPLOYEE_FIRST_NAME", "EMPLOYEE_MIDDLE_NAME", "EMPLOYEE_ADDRESS1", "EMPLOYEE_ADDRESS2", "SUITE", "COUNTY", "EMPLOYEE_STATE_CODE", "EMPLOYEE_ZIP_CODE", "EMPLOYEE_ZIP_CODE4", "EMPLOYEE_ACCOUNT_NUMBER", "MARITAL_STATUS_CODE", "EMPLOYEE_PAY_GROUP_DESCRIPTION", "VESTING_DATE", "HIRE_DATE", "BIRTH_DATE", "EMPLOYEE_STATUS", "STATUS401K", "TERMINATION_DATE", "REHIRE_DATE", "WITHDRAW_DATE", "DISABILITY_DATE", "INACTIVE_DATE", "OFFICER_IND", "EMPLOYMENT_TYPE", "ORGANIZATION_CODE", "EMPLOYEE_ID", "GENDER_CODE", "WORK_PHONE", "HOME_PHONE_NUMBER", "MOBILE_PHONE", "PLAN_ID", "ADJUSTED_HIRE_DATE", "HOME_EMAIL", "RATE", "CURRENT_AMOUNT", "YTD_AMOUNT", "GLOBAL_DEDUCTION_CODE", "CLIENT_DEDUCTION_CODE", "TOTAL_GROSS", "TARGET_AMOUNT", "CURRENT_HOURS", "ELIGIBLE_WAGE", "YTD_ELIGIBLE_WAGE", "PLAN_ENTRY_DATE", "EMPLOYER_PLAN_WAGE", "CURRENT_PLAN_COMPENSATION", "YTD_PLAN_COMPENSATION", "EMPLOYER_PLAN_YEAR_PLAN_COMPENSATION", "ANNUALIZED_RATE", "TAX_CATEGORY_CODE", "R_DETAIL_TYPE", "YTD_GROSS", "YTD_HOURS", "TOTAL_NON_TAXABLE", "YTD_NON_TAXABLE", "PAYRATE", "FREQUENCY", "RATE_TYPE", "ANNUAL_HOURS", "PAYS_PER_YEAR", "SENIORITY_DATE", "PRIOR_TERM_DATE", "EMAIL", "EMPLOYEE_COUNTRY_CODE", "EMPLOYEE_COUNTRY_ZIP", "EMPLOYEE_COUNTRY", "EMPLOYEE_TRANS_IND", "FED_NUM_EXEMPTIONS", "NET_CHECK", "EMPLOYEE_PPUID", "LEGAL_ENTITY_RETIREMENT_DATA_LOCAL", "SPOUCE_BD", "EMPLOYEE_NUMBER", "FULL_TIME_FLAG", "ANNIVERSARY", "PERC_OWNER", "EMPLOYER_PLAN_ENTRY_DATE_CC", "EMPLOYER_PLAN_ENTRY_DATE_YY", "EMPLOYER_PLAN_ENTRY_DATE_MM", "EMPLOYER_PLAN_ENTRY_DATE_DD", "EMPLOYER_PLAN_YEAR_WAGES", "EMPLOYER_PLAN_YEAR_HOURS", "SOURCE", "BATCH_GROUP", "LOAN_IDENTIFICATION", "ADJUSTMENT_REASON", "ORIGINAL_PAYDATE", "THIRD_PARTY_IDENTIFIER", "GLOBAL_DEDUCTION_SUBTYPE", "DEDUCTION_DESCRIPTION", "FUND_CODE", "CLIENT_DEDUCTION_UID", "GLOBAL_DEDUCTION_UID", "R_DETAIL_START_DATE", "R_DETAIL_UID", "__ROW_MD5", "__DLH_IS_DELETED", "__DLH_SYNC_TS", "__DLH_START_TS", "__DLH_FINISH_TS", "__DLH_IS_ACTIVE"};
        public static final String[] LABOUR_CATEGORIES = {"LABOR_CATEGORY_ID", "LEGAL_ENTITY_ID", "LABOR_CATEGORY_NAME", "CATEGORY_LEVEL", "CATEGORY_ITEM_COUNT", "__ROW_MD5", "__DLH_IS_DELETED", "__DLH_SYNC_TS", "__DLH_START_TS", "__DLH_FINISH_TS", "__DLH_IS_ACTIVE"};
        public static final String[] LEGAL_ENTITY_ACTIVITY_TYPES = {"ID", "LEGAL_ENTITY_ID", "NAME", "COLOR", "LEGAL_ENTITY_ACTIVITY_TYPES_TYPE", "IS_CUSTOM", "__ROW_MD5", "__DLH_IS_DELETED", "__DLH_SYNC_TS", "__DLH_START_TS", "__DLH_FINISH_TS", "__DLH_IS_ACTIVE"};
        public static final String[] LEGAL_ENTITY_ON_DEMAND_PAY_DEDUCTION_INFORMATION = {"LEGAL_ENTITY_ID", "CHECK_DATE", "PAY_IMPORT_ID", "EMPLOYEE_ID", "EMPLOYEE_NUMBER", "ENHANCED_EMPLOYEE_NUMBER", "EMPLOYEE_NAME", "EMPLOYEE_STATUS_IS_FULL_TIME", "EMPLOYEE_STATUS_STATUS", "EMPLOYEE_STATUS_FLSA", "EMPLOYEE_STATUS_TYPE", "EMPLOYEE_STATUS_ELIGIBLE_FOR_REHIRE", "WAS_EMPLOYEE_PAID", "RECEIVED_AMOUNT", "PAID_AMOUNT", "SHORTFALL_AMOUNT", "PAYRUN_STATUS", "PAYRUN_PROCESS_DATE", "PERIOD_START_DATE", "PERIOD_END_DATE", "IMPOUND_PROCESS_DATE", "IMPOUND_REFERENCE_ID", "IMPOUNDED_AMOUNT", "IS_CLIENT_ACTIVE", "__ROW_MD5", "__DLH_IS_DELETED", "__DLH_SYNC_TS", "__DLH_START_TS", "__DLH_FINISH_TS", "__DLH_IS_ACTIVE"};
        public static final String[] LEGAL_ENTITY_EMPLOYEES = {"ID", "FIRST_NAME", "MIDDLE_NAME", "LAST_NAME", "EMAIL_TYPE", "EMAIL_EMAIL_ADDRESS", "EMPLOYMENT_DATE_DATA_HIRE_DATE", "EMPLOYMENT_DATE_DATA_ADJUSTED_HIRE_DATE", "EMPLOYMENT_DATE_DATA_TERMINATION_DATE", "EMPLOYMENT_DATE_DATA_TERMINATION_REASON", "EMPLOYMENT_DATE_DATA_RE_HIRE_DATE", "EMPLOYMENT_DATE_DATA_SENIORITY_DATE", "STATUS_DATA_IS_FULL_TIME", "STATUS_DATA_STATUS", "STATUS_DATA_FLSA", "STATUS_DATA_TYPE", "STATUS_DATA_ELIGIBLE_FOR_REHIRE", "WORK_LOCATION_ID", "WORK_LOCATION_NAME", "WORK_LOCATION_STREET_LINE1", "WORK_LOCATION_TYPE", "WORK_LOCATION_CITY", "WORK_LOCATION_COUNTY", "WORK_LOCATION_STATE", "WORK_LOCATION_ZIP_CODE", "WORK_LOCATION_COUNTRY", "EARNINGS_ID", "DEDUCTIONS_ID", "TAXES_ID", "DIRECT_DEPOSITS_ID", "PAY_RATES_ID", "LEGAL_ENTITY_ID", "PERSON_ID", "DEPARTMENT_ID", "POSITION_DATA_JOB_TITLE", "POSITION_DATA_JOB_CODE", "POSITION_DATA_EFFECTIVE_END_DATE", "POSITION_DATA_PAY_GROUP_ID", "POSITION_DATA_MANAGER_ID", "POSITION_DATA_MANAGER_EMPLOYEE_NUMBER", "POSITION_DATA_MANAGER_EMPLOYEE_ID", "EMPLOYEE_NUMBER", "WORK_COUNTRY_CODE", "LAST_NAME2", "WORKER_CATEGORY", "__ROW_MD5", "__DLH_IS_DELETED", "__DLH_SYNC_TS", "__DLH_START_TS", "__DLH_FINISH_TS", "__DLH_IS_ACTIVE"};
        public static final String[] EMPLOYEE_PAY_SCHEDULE = {"PERIOD_START_DATE", "PERIOD_END_DATE", "CHECK_DATE", "PROCESS_DATE", "PLANNER_ID", "PAYROLL_STATUS", "EMPLOYEE_ID", "__ROW_MD5", "__DLH_IS_DELETED", "__DLH_SYNC_TS", "__DLH_START_TS", "__DLH_FINISH_TS", "__DLH_IS_ACTIVE"};
        public static final String[] EMPLOYEE_ONBOARDING = {"ONBOARDING_EMPLOYEE_ID", "LEGAL_ENTITY_ID", "FIRST_NAME", "LAST_NAME", "FULL_NAME", "EMAIL_ADDRESS", "INVITED_DATE", "HAS_ONBOARDING_ACCESS", "HIRE_DATE", "STEPS_TOTAL", "STEPS_COMPLETED", "LAST_EMPLOYEE_STEP_COMPLETED", "LAST_EMPLOYEE_STEP_COMPLETED_DATE", "LAST_ADMIN_STEP_COMPLETED", "LAST_ADMIN_STEP_COMPLETED_DATE", "WORK_LOCATION", "WORK_LOCATION_ID", "MANAGER", "MANAGER_ID", "EMPLOYEE_NUMBER", "__ROW_MD5", "__DLH_IS_DELETED", "__DLH_SYNC_TS", "__DLH_START_TS", "__DLH_FINISH_TS", "__DLH_IS_ACTIVE"};
        public static final String[] EMPLOYEE_BENEFIT_CLASSIFICATION = {"LEGAL_ENTITY_ID", "EMPLOYEE_ID", "PRIMARY_ASSIGNMENT", "BENEFIT_CLASSIFICATION", "BENEFIT_CLASSIFICATION_DATE_EFFECTIVE_START_DATE", "BENEFIT_CLASSIFICATION_DATE_EFFECTIVE_END_DATE", "ASSIGNMENT_CHANGE_REASON", "__ROW_MD5", "__DLH_IS_DELETED", "__DLH_SYNC_TS", "__DLH_START_TS", "__DLH_FINISH_TS", "__DLH_IS_ACTIVE"};
        public static final String[] EMPLOYEE_DIRECT_DEPOSITS = {"ID", "ACCOUNT_TYPE", "MASKED_ACCOUNT_NUMBER", "UNMASKED_ACCOUNT_NUMBER", "ROUTING_NUMBER", "BANK_NAME", "FREQUENCY", "DEDUCTION_CODE", "DIRECT_DEPOSIT_TYPE", "ON_HOLD", "AMOUNT", "RATE", "EMPLOYEE_ID", "__ROW_MD5", "__DLH_IS_DELETED", "__DLH_SYNC_TS", "__DLH_START_TS", "__DLH_FINISH_TS", "__DLH_IS_ACTIVE"};
        public static final String[] LEGAL_ENTITY = {"ID", "NAME", "TAX_FILING_NAME", "FEDERAL_ID", "LEGAL_ENTITY_TYPE", "IS_LOST", "BUSINESS_NAMES", "TAX_FILING_BUSINESS_NAMES", "TENANT_ID", "__ROW_MD5", "__DLH_IS_DELETED", "__DLH_SYNC_TS", "__DLH_START_TS", "__DLH_FINISH_TS", "__DLH_IS_ACTIVE"};
        public static final String[] LEGAL_ENTITY_TAXES = {"LEGAL_ENTITY_TAX_ID", "LEGAL_ENTITY_ID", "TAX_CODE", "DESCRIPTION", "LEGAL_ENTITY_TAXES_TYPE", "TAX_AUTH_CODE", "DEPOSIT_FREQUENCY", "EFFECTIVE_START_DATE", "SEQUENCE_NUMBER", "RATE", "RECIPROCITY_TYPE", "OFFER_DEPENDENT_INSURANCE", "WAGE_PLAN", "ITEM_HOLD", "LEGAL_ENTITY_ID", "__ROW_MD5", "__DLH_IS_DELETED", "__DLH_SYNC_TS", "__DLH_START_TS", "__DLH_FINISH_TS", "__DLH_IS_ACTIVE"};
        public static final String[] EMPLOYEE_PUNCH_PROFILE_DATA = {"PUNCH_PROFILE_ID", "EMPLOYEE_ID", "HAS_ALL_DEPARMENTS_SELECTED", "HAS_ALL_WORK_LOCATIONS_SELECTED", "HAS_ALL_ACTIVITY_TYPES_SELECTED", "HAS_DETAIL_PUNCH", "DEPARTMENTS", "WORK_LOCATIONS", "LABOR_PROFILE_LABOR_PROFILE_ID", "LABOR_PROFILE_LABOR_PROFILE_NAME", "LABOR_PROFILE_LABOR_CATEGORIES", "ACTIVITY_TYPES", "__ROW_MD5", "__DLH_IS_DELETED", "__DLH_SYNC_TS", "__DLH_START_TS", "__DLH_FINISH_TS", "__DLH_IS_ACTIVE"};
        public static final String[] LEGAL_ENTITY_PAYROLL_PROCESSING = {"PLANNER_ID", "LEGAL_ENTITY_ID", "CHECK_DATE", "PROCESS_DATE", "PERIOD_START_DATE", "PERIOD_END_DATE", "PAY_GROUP", "RUN_TYPE", "__ROW_MD5", "__DLH_IS_DELETED", "__DLH_SYNC_TS", "__DLH_START_TS", "__DLH_FINISH_TS", "__DLH_IS_ACTIVE"};
        public static final String[] EMPLOYEE_TIME_CARD = {"DISPLAY_DATE", "IN_ACTUAL_PUNCH", "OUT_ACTUAL_PUNCH", "IN_ROUNDED_PUNCH", "OUT_ROUNDED_PUNCH", "HOURS_AMOUNT", "DEPARTMENT_CODE", "DEPARTMENT_NAME", "EARNING_CODE", "LABOR_CODES", "EMPLOYEE_ID", "EMPLOYEE_NUMBER", "BADGE_NUMBER", "__ROW_MD5", "__DLH_IS_DELETED", "__DLH_SYNC_TS", "__DLH_START_TS", "__DLH_FINISH_TS", "__DLH_IS_ACTIVE"};
        public static final String[] EMPLOYEE_EARNINGS = {"ID", "CODE", "DESCRIPTION", "EMPLOYEE_EARNINGS_TYPE", "FREQUENCY", "SEQUENCE_NUMBER", "INCLUDE_IN_PAY", "ON_HOLD", "EFFECTIVE_START_DATE", "EFFECTIVE_END_DATE", "AMOUNT_DATA", "EMPLOYEE_ID", "LEGAL_ENTITY_EARNING_ID", "__ROW_MD5", "__DLH_IS_DELETED", "__DLH_SYNC_TS", "__DLH_START_TS", "__DLH_FINISH_TS", "__DLH_IS_ACTIVE"};
        public static final String[] LEGAL_ENTITY_TIMEOFF_TYPES = {"ID", "LEGAL_ENTITY_ID", "NAME", "CODE", "__ROW_MD5", "__DLH_IS_DELETED", "__DLH_SYNC_TS", "__DLH_START_TS", "__DLH_FINISH_TS", "__DLH_IS_ACTIVE"};
        public static final String[] LEGAL_ENTITY_SCHEDULING_JOBS = {"SCHEDULING_JOB_ID", "SCHEDULING_JOB_NAME", "__ROW_MD5", "__DLH_IS_DELETED", "__DLH_SYNC_TS", "__DLH_START_TS", "__DLH_FINISH_TS", "__DLH_IS_ACTIVE"};
        public static final String[] PERSONS = {"ID", "LEGAL_ENTITY_ID", "PREFIX", "FIRST_NAME", "MIDDLE_NAME", "LAST_NAME", "SUFFIX", "LEGAL_FIRST_NAME", "LEGAL_LAST_NAME", "SOCIAL_SECURITY_NUMBER", "EMAIL_TYPE", "EMAIL_EMAIL_ADDRESS", "DEMOGRAPHIC_DATA", "BENEFIT_DATA", "EMERGENCY_CONTACT_DATA", "MILITARY_DATA", "SOCIAL_MEDIA_DATA", "EMPLOYEE_ASSIGNMENTS", "ADDRESSES", "PHONES", "CUSTOM_IDENTIFIERS", "__ROW_MD5", "__DLH_IS_DELETED", "__DLH_SYNC_TS", "__DLH_START_TS", "__DLH_FINISH_TS", "__DLH_IS_ACTIVE"};

        private PayCorHeaders() {}
    }


    public static final Map<String, List<String>> ENTITY_DEPENDENCY_MAP = Map.ofEntries(

            Map.entry(PayCorEntityNames.LEGAL_ENTITY_TENANTS, List.of(
                    PayCorEntityNames.LEGAL_ENTITY,
                    PayCorEntityNames.LEGAL_ENTITY_WORK_LOCATIONS,
                    PayCorEntityNames.LEGAL_ENTITY_TIMEOFF_REQUESTS,
                    PayCorEntityNames.LEGAL_ENTITY_DEDUCTIONS,
                    PayCorEntityNames.LEGAL_ENTITY_DEPARTMENTS,
                    PayCorEntityNames.LEGAL_ENTITY_FORCASTING,
                    PayCorEntityNames.LEGAL_ENTITY_SCHEDULING_SHIFTS,
                    PayCorEntityNames.LEGAL_ENTITY_EMPLOYEES_IDENTIFYING_DATA,
                    PayCorEntityNames.LEGAL_ENTITY_MISSED_PUNCH_REQUESTS,
                    PayCorEntityNames.LABOUR_CODES,
                    PayCorEntityNames.LEGAL_ENTITY_CERTIFICATION_ORGANIZATION,
                    PayCorEntityNames.LEGAL_ENTITY_SCHEDULE_GROUPS,
                    PayCorEntityNames.LEGAL_ENTITY_PAY_ITEMS,
                    PayCorEntityNames.LEGAL_ENTITY_PAYSTUBS,
                    PayCorEntityNames.EMPLOYEE_ONBOARDING,
                    PayCorEntityNames.LEGAL_ENTITY_PAYSCHEDULE,
                    PayCorEntityNames.LEGAL_ENTITY_WORK_SITES,
                    PayCorEntityNames.LEGAL_ENTITY_PUNCHES,
                    PayCorEntityNames.LEGAL_ENTITY_PAY_DATA,
                    PayCorEntityNames.LEGAL_ENTITY_UNASSIGNED_PUNCHES,
                    PayCorEntityNames.LEGAL_ENTITY_SERVICES,
                    PayCorEntityNames.LEGAL_ENTITY_PAY_GROUPS,
                    PayCorEntityNames.LEGAL_ENTITY_MANAGER_PROFILES,
                    PayCorEntityNames.LEGAL_ENTITY_EARNINGS,
                    PayCorEntityNames.LEGAL_ENTITY_REASON_CODES,
                    PayCorEntityNames.LEGAL_ENTITY_LABOUR_PROFILES,
                    PayCorEntityNames.LEGAL_ENTITY_CERTIFICATIONS,
                    PayCorEntityNames.LEGAL_ENTITY_TIMEOFF_PLANS,
                    PayCorEntityNames.LEGAL_ENTITY_RETIREMENT_DATA,
                    PayCorEntityNames.LABOUR_CATEGORIES,
                    PayCorEntityNames.LEGAL_ENTITY_ACTIVITY_TYPES,
                    PayCorEntityNames.LEGAL_ENTITY_ON_DEMAND_PAY_DEDUCTION_INFORMATION,
                    PayCorEntityNames.LEGAL_ENTITY_SCHEDULING_JOBS,
                    PayCorEntityNames.LEGAL_ENTITY_TAXES,
                    PayCorEntityNames.LEGAL_ENTITY_PAYROLL_PROCESSING,
                    PayCorEntityNames.LEGAL_ENTITY_TIMEOFF_TYPES,
                    PayCorEntityNames.LEGAL_ENTITY_EMPLOYEES,
                    PayCorEntityNames.PERSONS
                    )),
            Map.entry(PayCorEntityNames.LEGAL_ENTITY_EMPLOYEES, List.of(
                    PayCorEntityNames.EMPLOYEE_TAXES,
                    PayCorEntityNames.EMPLOYEE_PAYSTUB_DOCUMENT_DATA,
                    PayCorEntityNames.EMPLOYEE_CERTIFICATIONS,
                    PayCorEntityNames.EMPLOYEE_I9_VERIFICATION,
                    PayCorEntityNames.EMPLOYEE_DEDUCTION,
                    PayCorEntityNames.EMPLOYEE_PAYRATES,
                    PayCorEntityNames.EMPLOYEE_TAX_DOCUMENTS,
                    PayCorEntityNames.EMPLOYEE_TIMEOFF_ACCRUALS,
                    PayCorEntityNames.EMPLOYEE_PUNCHES,
                    PayCorEntityNames.EMPLOYEE_HSA_ACCOUNT,
                    PayCorEntityNames.EMPLOYEE_POLICY_GROUP_DATA,
                    PayCorEntityNames.EMPLOYEE_UNPAID_PAYRATES,
                    PayCorEntityNames.HOURS,
                    PayCorEntityNames.EMPLOYEE_PERSONAL_DATA,
                    PayCorEntityNames.EMPLOYEE_CUSTOM_FIELDS,
                    PayCorEntityNames.EMPLOYEE_HOURS,
                    PayCorEntityNames.EMPLOYEE_TIMEOFF_PLAN_ASSIGNMENT,
                    PayCorEntityNames.EMPLOYEE_PAY_SCHEDULE,
                    PayCorEntityNames.EMPLOYEE_BENEFIT_CLASSIFICATION,
                    PayCorEntityNames.EMPLOYEE_DIRECT_DEPOSITS,
                    PayCorEntityNames.EMPLOYEE_PUNCH_PROFILE_DATA,
                    PayCorEntityNames.EMPLOYEE_EARNINGS,
                    PayCorEntityNames.EMPLOYEE_TIME_CARD
                    )),
            Map.entry(PayCorEntityNames.ATS_ACCOUNTS, List.of(
                    PayCorEntityNames.ATS_JOBS
            ))
    );

    public static final Map<String, String[]> HEADERS_BY_ENTITY = Map.ofEntries(
            Map.entry(PayCorEntityNames.LEGAL_ENTITY_TENANTS, PayCorHeaders.LEGAL_ENTITY_TENANTS),
            Map.entry(PayCorEntityNames.LEGAL_ENTITY, PayCorHeaders.LEGAL_ENTITY),
            Map.entry(PayCorEntityNames.LEGAL_ENTITY_WORK_LOCATIONS, PayCorHeaders.LEGAL_ENTITY_WORK_LOCATIONS),
            Map.entry(PayCorEntityNames.LEGAL_ENTITY_EMPLOYEES, PayCorHeaders.LEGAL_ENTITY_EMPLOYEES),
            Map.entry(PayCorEntityNames.EMPLOYEE_TAXES, PayCorHeaders.EMPLOYEE_TAXES),
            Map.entry(PayCorEntityNames.LEGAL_ENTITY_TIMEOFF_REQUESTS, PayCorHeaders.LEGAL_ENTITY_TIMEOFF_REQUESTS),
            Map.entry(PayCorEntityNames.EMPLOYEE_PAYSTUB_DOCUMENT_DATA, PayCorHeaders.EMPLOYEE_PAYSTUB_DOCUMENT_DATA),
            Map.entry(PayCorEntityNames.EMPLOYEE_CERTIFICATIONS, PayCorHeaders.EMPLOYEE_CERTIFICATIONS),
            Map.entry(PayCorEntityNames.LEGAL_ENTITY_DEDUCTIONS, PayCorHeaders.LEGAL_ENTITY_DEDUCTIONS),
            Map.entry(PayCorEntityNames.PAYROLL_CUSTOM_FIELD_VALUES, PayCorHeaders.PAYROLL_CUSTOM_FIELD_VALUES),
            Map.entry(PayCorEntityNames.EMPLOYEE_I9_VERIFICATION, PayCorHeaders.EMPLOYEE_I9_VERIFICATION),
            Map.entry(PayCorEntityNames.EMPLOYEE_DEDUCTION, PayCorHeaders.EMPLOYEE_DEDUCTION),
            Map.entry(PayCorEntityNames.LEGAL_ENTITY_DEPARTMENTS, PayCorHeaders.LEGAL_ENTITY_DEPARTMENTS),
            Map.entry(PayCorEntityNames.LEGAL_ENTITY_FORCASTING, PayCorHeaders.LEGAL_ENTITY_FORCASTING),
            Map.entry(PayCorEntityNames.LEGAL_ENTITY_SCHEDULING_SHIFTS, PayCorHeaders.LEGAL_ENTITY_SCHEDULING_SHIFTS),
            Map.entry(PayCorEntityNames.LEGAL_ENTITY_EMPLOYEES_IDENTIFYING_DATA, PayCorHeaders.LEGAL_ENTITY_EMPLOYEES_IDENTIFYING_DATA),
            Map.entry(PayCorEntityNames.LEGAL_ENTITY_MISSED_PUNCH_REQUESTS, PayCorHeaders.LEGAL_ENTITY_MISSED_PUNCH_REQUESTS),
            Map.entry(PayCorEntityNames.EMPLOYEE_PAYRATES, PayCorHeaders.EMPLOYEE_PAYRATES),
            Map.entry(PayCorEntityNames.LABOUR_CODES, PayCorHeaders.LABOUR_CODES),
            Map.entry(PayCorEntityNames.LEGAL_ENTITY_CERTIFICATION_ORGANIZATION, PayCorHeaders.LEGAL_ENTITY_CERTIFICATION_ORGANIZATION),
            Map.entry(PayCorEntityNames.EMPLOYEE_TAX_DOCUMENTS, PayCorHeaders.EMPLOYEE_TAX_DOCUMENTS),
            Map.entry(PayCorEntityNames.LEGAL_ENTITY_SCHEDULE_GROUPS, PayCorHeaders.LEGAL_ENTITY_SCHEDULE_GROUPS),
            Map.entry(PayCorEntityNames.LEGAL_ENTITY_PAY_ITEMS, PayCorHeaders.LEGAL_ENTITY_PAY_ITEMS),
            Map.entry(PayCorEntityNames.LEGAL_ENTITY_PAYSTUBS, PayCorHeaders.LEGAL_ENTITY_PAYSTUBS),
            Map.entry(PayCorEntityNames.LEGAL_ENTITY_PAYSCHEDULE, PayCorHeaders.LEGAL_ENTITY_PAYSCHEDULE),
            Map.entry(PayCorEntityNames.EMPLOYEE_TIMEOFF_ACCRUALS, PayCorHeaders.EMPLOYEE_TIMEOFF_ACCRUALS),
            Map.entry(PayCorEntityNames.EMPLOYEE_PUNCHES, PayCorHeaders.EMPLOYEE_PUNCHES),
            Map.entry(PayCorEntityNames.EMPLOYEE_HSA_ACCOUNT, PayCorHeaders.EMPLOYEE_HSA_ACCOUNT),
            Map.entry(PayCorEntityNames.EMPLOYEE_POLICY_GROUP_DATA, PayCorHeaders.EMPLOYEE_POLICY_GROUP_DATA),
            Map.entry(PayCorEntityNames.LEGAL_ENTITY_WORK_SITES, PayCorHeaders.LEGAL_ENTITY_WORK_SITES),
            Map.entry(PayCorEntityNames.LEGAL_ENTITY_PUNCHES, PayCorHeaders.LEGAL_ENTITY_PUNCHES),
            Map.entry(PayCorEntityNames.LEGAL_ENTITY_PAY_DATA, PayCorHeaders.LEGAL_ENTITY_PAY_DATA),
            Map.entry(PayCorEntityNames.EMPLOYEE_UNPAID_PAYRATES, PayCorHeaders.EMPLOYEE_UNPAID_PAYRATES),
            Map.entry(PayCorEntityNames.ATS_ACCOUNTS, PayCorHeaders.ATS_ACCOUNTS),
            Map.entry(PayCorEntityNames.HOURS, PayCorHeaders.HOURS),
            Map.entry(PayCorEntityNames.LEGAL_ENTITY_UNASSIGNED_PUNCHES, PayCorHeaders.LEGAL_ENTITY_UNASSIGNED_PUNCHES),
            Map.entry(PayCorEntityNames.LEGAL_ENTITY_SERVICES, PayCorHeaders.LEGAL_ENTITY_SERVICES),
            Map.entry(PayCorEntityNames.LEGAL_ENTITY_PAY_GROUPS, PayCorHeaders.LEGAL_ENTITY_PAY_GROUPS),
            Map.entry(PayCorEntityNames.LEGAL_ENTITY_MANAGER_PROFILES, PayCorHeaders.LEGAL_ENTITY_MANAGER_PROFILES),
            Map.entry(PayCorEntityNames.EMPLOYEE_PERSONAL_DATA, PayCorHeaders.EMPLOYEE_PERSONAL_DATA),
            Map.entry(PayCorEntityNames.EMPLOYEE_CUSTOM_FIELDS, PayCorHeaders.EMPLOYEE_CUSTOM_FIELDS),
            Map.entry(PayCorEntityNames.LEGAL_ENTITY_EARNINGS, PayCorHeaders.LEGAL_ENTITY_EARNINGS),
            Map.entry(PayCorEntityNames.ATS_JOBS, PayCorHeaders.ATS_JOBS),
            Map.entry(PayCorEntityNames.EMPLOYEE_HOURS, PayCorHeaders.EMPLOYEE_HOURS),
            Map.entry(PayCorEntityNames.LEGAL_ENTITY_REASON_CODES, PayCorHeaders.LEGAL_ENTITY_REASON_CODES),
            Map.entry(PayCorEntityNames.EMPLOYEE_TIMEOFF_PLAN_ASSIGNMENT, PayCorHeaders.EMPLOYEE_TIMEOFF_PLAN_ASSIGNMENT),
            Map.entry(PayCorEntityNames.LEGAL_ENTITY_LABOUR_PROFILES, PayCorHeaders.LEGAL_ENTITY_LABOUR_PROFILES),
            Map.entry(PayCorEntityNames.ATS_JOB_CANDIDATES, PayCorHeaders.ATS_JOB_CANDIDATES),
            Map.entry(PayCorEntityNames.LEGAL_ENTITY_CERTIFICATIONS, PayCorHeaders.LEGAL_ENTITY_CERTIFICATIONS),
            Map.entry(PayCorEntityNames.LEGAL_ENTITY_TIMEOFF_PLANS, PayCorHeaders.LEGAL_ENTITY_TIMEOFF_PLANS),
            Map.entry(PayCorEntityNames.LEGAL_ENTITY_RETIREMENT_DATA, PayCorHeaders.LEGAL_ENTITY_RETIREMENT_DATA),
            Map.entry(PayCorEntityNames.LABOUR_CATEGORIES, PayCorHeaders.LABOUR_CATEGORIES),
            Map.entry(PayCorEntityNames.LEGAL_ENTITY_ACTIVITY_TYPES, PayCorHeaders.LEGAL_ENTITY_ACTIVITY_TYPES),
            Map.entry(PayCorEntityNames.LEGAL_ENTITY_ON_DEMAND_PAY_DEDUCTION_INFORMATION, PayCorHeaders.LEGAL_ENTITY_ON_DEMAND_PAY_DEDUCTION_INFORMATION),
            Map.entry(PayCorEntityNames.EMPLOYEE_PAY_SCHEDULE, PayCorHeaders.EMPLOYEE_PAY_SCHEDULE),
            Map.entry(PayCorEntityNames.EMPLOYEE_ONBOARDING, PayCorHeaders.EMPLOYEE_ONBOARDING),
            Map.entry(PayCorEntityNames.EMPLOYEE_BENEFIT_CLASSIFICATION, PayCorHeaders.EMPLOYEE_BENEFIT_CLASSIFICATION),
            Map.entry(PayCorEntityNames.EMPLOYEE_DIRECT_DEPOSITS, PayCorHeaders.EMPLOYEE_DIRECT_DEPOSITS),
            Map.entry(PayCorEntityNames.LEGAL_ENTITY_TAXES, PayCorHeaders.LEGAL_ENTITY_TAXES),
            Map.entry(PayCorEntityNames.EMPLOYEE_PUNCH_PROFILE_DATA, PayCorHeaders.EMPLOYEE_PUNCH_PROFILE_DATA),
            Map.entry(PayCorEntityNames.LEGAL_ENTITY_PAYROLL_PROCESSING, PayCorHeaders.LEGAL_ENTITY_PAYROLL_PROCESSING),
            Map.entry(PayCorEntityNames.EMPLOYEE_TIME_CARD, PayCorHeaders.EMPLOYEE_TIME_CARD),
            Map.entry(PayCorEntityNames.EMPLOYEE_EARNINGS, PayCorHeaders.EMPLOYEE_EARNINGS),
            Map.entry(PayCorEntityNames.LEGAL_ENTITY_TIMEOFF_TYPES, PayCorHeaders.LEGAL_ENTITY_TIMEOFF_TYPES),
            Map.entry(PayCorEntityNames.LEGAL_ENTITY_SCHEDULING_JOBS, PayCorHeaders.LEGAL_ENTITY_SCHEDULING_JOBS),
            Map.entry(PayCorEntityNames.PERSONS, PayCorHeaders.PERSONS)
    );

    public static final Map<String, String[]> DELTA_HEADERS_BY_ENTITY = Map.ofEntries(
            Map.entry(PayCorEntityNames.ATS_JOBS, PayCorHeaders.ATS_JOBS),
            Map.entry(PayCorEntityNames.EMPLOYEE_HOURS, PayCorHeaders.EMPLOYEE_HOURS),
            Map.entry(PayCorEntityNames.LEGAL_ENTITY_REASON_CODES, PayCorHeaders.LEGAL_ENTITY_REASON_CODES),
            Map.entry(PayCorEntityNames.EMPLOYEE_TIMEOFF_PLAN_ASSIGNMENT, PayCorHeaders.EMPLOYEE_TIMEOFF_PLAN_ASSIGNMENT),
            Map.entry(PayCorEntityNames.LEGAL_ENTITY_LABOUR_PROFILES, PayCorHeaders.LEGAL_ENTITY_LABOUR_PROFILES),
            Map.entry(PayCorEntityNames.ATS_JOB_CANDIDATES, PayCorHeaders.ATS_JOB_CANDIDATES),
            Map.entry(PayCorEntityNames.LEGAL_ENTITY_CERTIFICATIONS, PayCorHeaders.LEGAL_ENTITY_CERTIFICATIONS),
            Map.entry(PayCorEntityNames.LEGAL_ENTITY_TIMEOFF_PLANS, PayCorHeaders.LEGAL_ENTITY_TIMEOFF_PLANS),
            Map.entry(PayCorEntityNames.LEGAL_ENTITY_RETIREMENT_DATA, PayCorHeaders.LEGAL_ENTITY_RETIREMENT_DATA),
            Map.entry(PayCorEntityNames.LABOUR_CATEGORIES, PayCorHeaders.LABOUR_CATEGORIES),
            Map.entry(PayCorEntityNames.LEGAL_ENTITY_ACTIVITY_TYPES, PayCorHeaders.LEGAL_ENTITY_ACTIVITY_TYPES),
            Map.entry(PayCorEntityNames.LEGAL_ENTITY_ON_DEMAND_PAY_DEDUCTION_INFORMATION, PayCorHeaders.LEGAL_ENTITY_ON_DEMAND_PAY_DEDUCTION_INFORMATION),
            Map.entry(PayCorEntityNames.LEGAL_ENTITY_EMPLOYEES, PayCorHeaders.LEGAL_ENTITY_EMPLOYEES),
            Map.entry(PayCorEntityNames.EMPLOYEE_PAY_SCHEDULE, PayCorHeaders.EMPLOYEE_PAY_SCHEDULE),
            Map.entry(PayCorEntityNames.EMPLOYEE_ONBOARDING, PayCorHeaders.EMPLOYEE_ONBOARDING),
            Map.entry(PayCorEntityNames.EMPLOYEE_BENEFIT_CLASSIFICATION, PayCorHeaders.EMPLOYEE_BENEFIT_CLASSIFICATION),
            Map.entry(PayCorEntityNames.EMPLOYEE_DIRECT_DEPOSITS, PayCorHeaders.EMPLOYEE_DIRECT_DEPOSITS),
            Map.entry(PayCorEntityNames.LEGAL_ENTITY, PayCorHeaders.LEGAL_ENTITY),
            Map.entry(PayCorEntityNames.LEGAL_ENTITY_TAXES, PayCorHeaders.LEGAL_ENTITY_TAXES),
            Map.entry(PayCorEntityNames.EMPLOYEE_PUNCH_PROFILE_DATA, PayCorHeaders.EMPLOYEE_PUNCH_PROFILE_DATA),
            Map.entry(PayCorEntityNames.LEGAL_ENTITY_PAYROLL_PROCESSING, PayCorHeaders.LEGAL_ENTITY_PAYROLL_PROCESSING),
            Map.entry(PayCorEntityNames.EMPLOYEE_TIME_CARD, PayCorHeaders.EMPLOYEE_TIME_CARD),
            Map.entry(PayCorEntityNames.EMPLOYEE_EARNINGS, PayCorHeaders.EMPLOYEE_EARNINGS),
            Map.entry(PayCorEntityNames.LEGAL_ENTITY_TIMEOFF_TYPES, PayCorHeaders.LEGAL_ENTITY_TIMEOFF_TYPES),
            Map.entry(PayCorEntityNames.LEGAL_ENTITY_SCHEDULING_JOBS, PayCorHeaders.LEGAL_ENTITY_SCHEDULING_JOBS),
            Map.entry(PayCorEntityNames.PERSONS, PayCorHeaders.PERSONS)
    );

    public static final Map<String, String> ENTITY_API_PATH_MAP = Map.ofEntries(
            Map.entry(PayCorEntityNames.EMPLOYEE_TAXES, "v1/employees/{employeeId}/taxes"),
            Map.entry(PayCorEntityNames.LEGAL_ENTITY_TENANTS, "v1/legalentities/ActivatedLegalEntityTenantList"),
            Map.entry(PayCorEntityNames.LEGAL_ENTITY_WORK_LOCATIONS, "v1/legalentities/{legalEntityId}/worklocations"),
            Map.entry(PayCorEntityNames.LEGAL_ENTITY_TIMEOFF_REQUESTS, "v1/legalentities/{legalEntityId}/timeoffrequests"),
            Map.entry(PayCorEntityNames.LEGAL_ENTITY_FORCASTING, "v1/legalentities/{legalEntityId}/forecasting"),
            Map.entry(PayCorEntityNames.LEGAL_ENTITY_SCHEDULING_SHIFTS, "v1/legalentities/{legalEntityId}/schedulingshifts"),
            Map.entry(PayCorEntityNames.LEGAL_ENTITY_EMPLOYEES_IDENTIFYING_DATA, "v2/legalentities/{legalEntityId}/employeesIdentifyingData"),
            Map.entry(PayCorEntityNames.LEGAL_ENTITY_MISSED_PUNCH_REQUESTS, "v1/legalentities/{legalEntityId}/missedpunchrequests"),
            Map.entry(PayCorEntityNames.LEGAL_ENTITY_DEDUCTIONS, "v1/legalentities/{legalEntityId}/deductions"),
            Map.entry(PayCorEntityNames.LEGAL_ENTITY_DEPARTMENTS, "v1/legalentities/{legalEntityId}/departments"),
            Map.entry(PayCorEntityNames.LEGAL_ENTITY_CERTIFICATION_ORGANIZATION, "v1/legalentities/{legalEntityId}/certificationorganizations"),
            Map.entry(PayCorEntityNames.LEGAL_ENTITY_SCHEDULE_GROUPS, "v1/legalentities/{legalEntityId}/schedulegroups"),
            Map.entry(PayCorEntityNames.LEGAL_ENTITY_PAY_ITEMS, "v1/legalentities/{legalEntityId}/payitems"),
            Map.entry(PayCorEntityNames.LEGAL_ENTITY_PAYSTUBS, "v1/legalentities/{legalEntityId}/paystubs"),
            Map.entry(PayCorEntityNames.LEGAL_ENTITY_PAYSCHEDULE, "v1/legalentities/{legalEntityId}/payschedules"),
            Map.entry(PayCorEntityNames.LEGAL_ENTITY_WORK_SITES, "v1/legalentities/{legalEntityId}/worksites"),
            Map.entry(PayCorEntityNames.LEGAL_ENTITY_PUNCHES, "v1/legalentities/{legalEntityId}/punches"),
            Map.entry(PayCorEntityNames.LEGAL_ENTITY_PAY_DATA, "v1/legalentities/{legalEntityId}/paydata"),
            Map.entry(PayCorEntityNames.LEGAL_ENTITY_UNASSIGNED_PUNCHES, "v1/legalentities/{legalEntityId}/unassignedpunches"),
            Map.entry(PayCorEntityNames.LEGAL_ENTITY_SERVICES, "v1/legalentities/{legalEntityId}/services"),
            Map.entry(PayCorEntityNames.LEGAL_ENTITY_PAY_GROUPS, "v1/legalentities/{legalEntityId}/paygroups"),
            Map.entry(PayCorEntityNames.LEGAL_ENTITY_MANAGER_PROFILES, "v1/legalentities/{legalEntityId}/managerprofiles"),
            Map.entry(PayCorEntityNames.LEGAL_ENTITY_REASON_CODES, "v1/legalentities/{legalEntityId}/reasonCodes"),
            Map.entry(PayCorEntityNames.LEGAL_ENTITY_LABOUR_PROFILES, "v1/legalentities/{legalEntityId}/laborprofiles"),
            Map.entry(PayCorEntityNames.LEGAL_ENTITY_CERTIFICATIONS, "v1/legalentities/{legalEntityId}/certifications"),
            Map.entry(PayCorEntityNames.LEGAL_ENTITY_TIMEOFF_PLANS, "v1/legalentities/{legalEntityId}/timeoffplans"),
            Map.entry(PayCorEntityNames.LEGAL_ENTITY_RETIREMENT_DATA, "v1/legalentities/{legalEntityId}/retirementdata"),
            Map.entry(PayCorEntityNames.LEGAL_ENTITY_EARNINGS, "v1/legalentities/{legalEntityId}/earnings"),
            Map.entry(PayCorEntityNames.LEGAL_ENTITY_ACTIVITY_TYPES, "v1/legalentities/{legalEntityId}/activitytypes"),
            Map.entry(PayCorEntityNames.LEGAL_ENTITY_ON_DEMAND_PAY_DEDUCTION_INFORMATION, "v1/legalentities/{legalEntityId}/ondemandpaydeductions"),
            Map.entry(PayCorEntityNames.LEGAL_ENTITY_EMPLOYEES, "v2/legalentities/{legalEntityId}/employees"),
            Map.entry(PayCorEntityNames.LEGAL_ENTITY, "v1/legalentities/{legalEntityId}"),
            Map.entry(PayCorEntityNames.LEGAL_ENTITY_TAXES, "v1/legalentities/{legalEntityId}/taxes"),
            Map.entry(PayCorEntityNames.LEGAL_ENTITY_PAYROLL_PROCESSING, "v1/legalentities/{legalEntityId}/payrollProcessing"),
            Map.entry(PayCorEntityNames.LEGAL_ENTITY_TIMEOFF_TYPES, "v1/legalentities/{legalEntityId}/timeofftypes"),
            Map.entry(PayCorEntityNames.LEGAL_ENTITY_SCHEDULING_JOBS, "v1/legalentities/{legalEntityId}/schedulingjobs"),
            Map.entry(PayCorEntityNames.LABOUR_CODES, "v1/legalentities/{legalEntityId}/laborcodes"),
            Map.entry(PayCorEntityNames.EMPLOYEE_PAYSTUB_DOCUMENT_DATA, "v1/employees/{employeeId}/paystubDocumentData"),
            Map.entry(PayCorEntityNames.EMPLOYEE_CERTIFICATIONS, "v1/employees/{employeeId}/certifications"),
            Map.entry(PayCorEntityNames.PAYROLL_CUSTOM_FIELD_VALUES, "v1/payroll/customfieldvalues"),
            Map.entry(PayCorEntityNames.EMPLOYEE_I9_VERIFICATION, "v1/employees/{employeeId}/i9verification"),
            Map.entry(PayCorEntityNames.EMPLOYEE_DEDUCTION, "v1/employees/{employeeId}/deductions"),
            Map.entry(PayCorEntityNames.EMPLOYEE_PAYRATES, "v1/employees/{employeeId}/payrates"),
            Map.entry(PayCorEntityNames.EMPLOYEE_TAX_DOCUMENTS, "v1/employees/{employeeId}/taxdocuments"),
            Map.entry(PayCorEntityNames.EMPLOYEE_TIMEOFF_ACCRUALS, "v1/employees/{employeeId}/timeoffaccruals"),
            Map.entry(PayCorEntityNames.EMPLOYEE_PUNCHES, "v1/employees/{employeeId}/employeePunches"),
            Map.entry(PayCorEntityNames.EMPLOYEE_HSA_ACCOUNT, "v1/employees/{employeeId}/hsaaccounts"),
            Map.entry(PayCorEntityNames.EMPLOYEE_POLICY_GROUP_DATA, "v1/employees/{employeeId}/employeePolicyGroupData"),
            Map.entry(PayCorEntityNames.EMPLOYEE_UNPAID_PAYRATES, "v1/employees/{employeeId}/unpaidpayrates"),
            Map.entry(PayCorEntityNames.ATS_ACCOUNTS, "v1/legalentities/{legalEntityId}/ats/accounts"),
            Map.entry(PayCorEntityNames.HOURS, "v1/employees/{employeeId}/hours"),
            Map.entry(PayCorEntityNames.EMPLOYEE_PERSONAL_DATA, "v1/employees/{employeeId}/personaldetails"),
            Map.entry(PayCorEntityNames.EMPLOYEE_CUSTOM_FIELDS, "v1/employees/{employeeId}/customfields"),
            Map.entry(PayCorEntityNames.ATS_JOBS, "v1/ats/jobs"),
            Map.entry(PayCorEntityNames.EMPLOYEE_HOURS, "v1/employees/{employeeId}/hours"),
            Map.entry(PayCorEntityNames.EMPLOYEE_TIMEOFF_PLAN_ASSIGNMENT, "v1/employees/{employeeId}/timeoffplanassignment"),
            Map.entry(PayCorEntityNames.ATS_JOB_CANDIDATES, "v1/ats/jobcandidates"),
            Map.entry(PayCorEntityNames.LABOUR_CATEGORIES, "v1/legalentities/{legalEntityId}/laborcategories"),
            Map.entry(PayCorEntityNames.EMPLOYEE_PAY_SCHEDULE, "v1/employees/{employeeId}/payschedule"),
            Map.entry(PayCorEntityNames.EMPLOYEE_ONBOARDING, "v2/legalentities/{legalEntityId}/onboardingemployees"),
            Map.entry(PayCorEntityNames.EMPLOYEE_BENEFIT_CLASSIFICATION, "v1/employees/{employeeId}/BenefitClassification"),
            Map.entry(PayCorEntityNames.EMPLOYEE_DIRECT_DEPOSITS, "v1/employees/{employeeId}/directdeposits"),
            Map.entry(PayCorEntityNames.EMPLOYEE_PUNCH_PROFILE_DATA, "v1/employees/{employeeId}/employeePunchProfileData"),
            Map.entry(PayCorEntityNames.EMPLOYEE_TIME_CARD, "v1/employees/{employeeId}/timecard"),
            Map.entry(PayCorEntityNames.EMPLOYEE_EARNINGS, "v1/employees/{employeeId}/earnings"),
            Map.entry(PayCorEntityNames.PERSONS, "v1/legalentities/{legalEntityId}/persons")
    );

    public static List<String> excludedEntities = List.of();

    public static final Map<String, List<String>> CUSTOM_QUERY_PARAM_BY_ENTITY = Map.ofEntries(
            Map.entry(PayCorEntityNames.EMPLOYEE_PAYSTUB_DOCUMENT_DATA, List.of("startDate", "endDate")),
            Map.entry(PayCorEntityNames.HOURS, List.of("startDate", "endDate")),
            Map.entry(PayCorEntityNames.LEGAL_ENTITY_SCHEDULING_SHIFTS, List.of("startDate", "endDate")),
            Map.entry(PayCorEntityNames.EMPLOYEE_TIME_CARD, List.of("startDate", "endDate")),
            Map.entry(PayCorEntityNames.EMPLOYEE_PUNCHES, List.of("startDate", "endDate")),
            Map.entry(PayCorEntityNames.LEGAL_ENTITY_PUNCHES, List.of("startDate", "endDate")),
            Map.entry(PayCorEntityNames.LEGAL_ENTITY_TIMEOFF_REQUESTS, List.of("startDate", "endDate")),
            Map.entry(PayCorEntityNames.LEGAL_ENTITY_FORCASTING, List.of("startDate", "endDate")),
            Map.entry(PayCorEntityNames.LEGAL_ENTITY_PAY_DATA, List.of("fromCheckDate", "toCheckDate")),
            Map.entry(PayCorEntityNames.LEGAL_ENTITY_PAYROLL_PROCESSING, List.of("fromCheckDate", "toCheckDate")),
            Map.entry(PayCorEntityNames.LEGAL_ENTITY_PAYSCHEDULE, List.of("asOfDate", "untilDate")),
            Map.entry(PayCorEntityNames.LEGAL_ENTITY_PAY_ITEMS, List.of("startDate", "endDate")),
            Map.entry(PayCorEntityNames.LEGAL_ENTITY_UNASSIGNED_PUNCHES, List.of("startDate", "endDate")),
            Map.entry(PayCorEntityNames.EMPLOYEE_HOURS, List.of("startDate", "endDate")),
            Map.entry(PayCorEntityNames.LEGAL_ENTITY_MISSED_PUNCH_REQUESTS, List.of("startDate", "endDate"))
    );

    private PayCorConstants() {}
}
